### PR TITLE
Refactor DotNetAliases: Extract methods into a separate partial class

### PR DESCRIPTION
**Pull request by Marusyk**
[discussion](https://github.com/cake-build/cake/pull/4392#discussion_r1838854200)
This pull request refactors the DotNetAliases class by extracting its methods into separate partial classes. The methods have been moved to individual files based on their functionality.

By refactoring the code into separate partial classes, we address these issues and create a more modular and maintainable codebase.

The original [DotNetAliases.cs](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/DotNet/DotNetAliases.cs) file had become too large and difficult to manage. By splitting the methods into separate partial classes, we achieve the following benefits:
 - improved code organization: Each file now contains methods related to a specific functionality, making it easier to navigate, understand, fix.
 - enhanced maintainability: Smaller, focused files are easier to maintain and modify. This reduces the risk of merge conflicts and makes it simpler to track changes.
- better readability: Developers can quickly locate the methods they need without sifting through a large file.

### CODE REVIEW

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by Marusyk** [comment]
#4392 should be merged first, then I'll add Remove to DotNetAliases .Sln.cs

**Comment by devlead** [comment]
@Marusyk https://github.com/cake-build/cake/pull/4392 is now merged.

**Comment by Marusyk** [comment]
Updated

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by devlead** [comment]
@Marusyk your changes have been merged, thanks for your contribution 👍

**Pull request merged**
