### PR TITLE
GH1653: Adding Before and After options

### PR DESCRIPTION
**Pull request by phillipsj**
Adding Before and After options for NUnit3Labels enum with tests.
Relates to #1653.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
Thanks for putting this in @phillipsj! 😄

**Comment by gep13** [comment]
@phillipsj are you in a position to rebase this PR?  If not, let me know, and I will do it.

**Comment by phillipsj** [comment]
@gep13 I may be able to do it in the morning.

**Comment by phillipsj** [comment]
@gep13  rebased.

**Comment by gep13** [comment]
@phillipsj your changes have been merged, thanks for your contribution 👍

**Pull request merged**
