### PR TITLE
GH895: Adds minClientVersion to support developmentDependency flag

### PR DESCRIPTION
**Pull request by daveaglick**
As recommended in #895

### CODE REVIEW

**Comment by devlead** [comment]
@daveaglick LGTM :+1: Could you rebase against latest develop and ping us back when done.

**Comment by daveaglick** [comment]
No prob, done :)

**Comment by gep13** [comment]
Since this only has a related issue, and not a specific issue, I have added this PR directly to milestone 0.13.0.

**Comment by devlead** [comment]
@daveaglick thanks, merged 👍

**Pull request merged**
