### PR TITLE
GH1292: Roundhouse Improvements

### PR DESCRIPTION
**Pull request by phillipsj**
Made changes as discussed in the ticket.

### CODE REVIEW

**Comment by phillipsj** [comment]
@gep13 Thanks for changing the title, something I was going to do this morning.

**Comment by patriksvensson** [comment]
LGTM!

**Comment by gep13** [comment]
Relates to #1292

**Comment by gep13** [comment]
@phillipsj I have just rebased your branch against the latest develop.  Assuming all the CI's pass, I will merge this into develop.

Thanks!

**Pull request merged**
