### PR TITLE
(GH-875) Added Cake.pdb to zip file

### PR DESCRIPTION
**Pull request by gep13**
Relates to #875

### CODE REVIEW

**Comment by gep13** [comment]
@patriksvensson it was a quick fix, so thought I would just do it :smile:

**Comment by devlead** [comment]
@gep13 looks good I'll merge when CI finishes. :+1:

**Comment by devlead** [comment]
@gep13 Confirmed appveyor artifacts :+1: 
image

Just mac travis left and I'll merge.

**Comment by devlead** [comment]
@gep13 merged :+1:

**Pull request merged**
