### PR TITLE
Added options to skip analysis

### PR DESCRIPTION
**Pull request by janniksam**
I've added an option to skip the analysis part after the command line tool is done.

In our situation we will do not need logging of the errors at that moment of time, we do the analysis of the result at a later stage. That's why we needed an possibility to skip it.

### CODE REVIEW

**Comment by gep13** [comment]
@janniksam apologies for not getting back to you sooner about this.  Was this PR associated with an issue that was raised on the repository?  Our contributing guidelines mention that an issue should first be created, prior to opening a PR.

**Comment by janniksam** [comment]
Hey, I am sorry for not creating an issue for the PR. It came from a personal experience using both "jetbrains tools".

I will have to recreate the PR anyways, because the repository was deleted by accident. But for now, do you have any opinion about the code?

**Comment by gep13** [comment]
From a brief inspection of the code, I have no objections to it getting merged in.  It would help if you could provide a bit more information in the issue that you create as to why exactly you want/need this.  That will help the PR review that will then be done.

Thanks

**Comment by janniksam** [comment]
I will recreate this pullrequest later. #2768

**Comment by janniksam** [comment]
Pullrequest reopened with #2769

**Pull request closed without merging**
