### PR TITLE
Clarify behaviour in summary of CopyDirectory method alias

### PR DESCRIPTION
**Pull request by UnbelievablyRitchie**
Simple clarification of wording to resolve issue #769

### CODE REVIEW

**Comment by devlead** [comment]
@UnbelievablyRitchie LGTM :+1: I'll merge once CI's finished.

**Comment by UnbelievablyRitchie** [comment]
Hope I've done this correctly; my first git hub commit. I'm hoping to run through issue #750 and tidy up the remainder of the missing examples.

**Comment by devlead** [comment]
@UnbelievablyRitchie to be picky would've liked a feature branch(`feature/GH769`) :wink: But issue created& referenced so that's good. I'll just wait for Travis to complete.

**Comment by devlead** [comment]
@UnbelievablyRitchie merged, thanks for you contribution:+1:

**Comment by UnbelievablyRitchie** [comment]
Cool; will do for next one. Thanks for the feedback.

**Comment by devlead** [comment]
@UnbelievablyRitchie excellent :+1:

**Pull request merged**
