### PR TITLE
Fix for "Input string was not in a correct format." exception.

### PR DESCRIPTION
**Pull request by olivier-spinelli**
Fix for "Input string was not in a correct format." exception when logging a JSON string.

Considering the {} placeholder only when actual arguments are provided easily fixes it.
The second commit avoids to keep {{ in log output: an escaped {{ is transformed into one {.

### CODE REVIEW

**Comment by olivier-spinelli** [comment]
Oups! Sorry, this breaks a test! I couldn't imagine this (that is clearly a fix for me) would break a test. I'll try to find some time to investigate this strange test,

**Comment by patriksvensson** [comment]
Yes, it looks like your fix broke something :(
The tests doesn't run on Travis at the moment due to problems with xUnit on Mono.

**Comment by devlead** [comment]
@olivier-spinelli had any time to look at above yet? Branch also out of date and needs to be rebased.

**Comment by patriksvensson** [comment]
Closing this PR for now.

**Pull request closed without merging**
