### PR TITLE
Added missing ReportGenerator parameter validation

### PR DESCRIPTION
**Pull request by devlead**
Fix missing context parameter validation.

### CODE REVIEW

**Comment by yvschmid** [comment]
@devlead What's the point of this? Does this generate a more meaningfull error message (stacktrace)? :confused:

**Comment by devlead** [comment]
Correct,  catches error in right place, if you build release you would've gotten errors on these as that triggers our StyleCop rules.I missed this on the review.

**Comment by yvschmid** [comment]
How do you build release locally? `cake -configuration=Release` doesn't seem to do the same thing, at least for me.

**Comment by devlead** [comment]
Release config in studio will trigger it.

**Comment by yvschmid** [comment]
:+1: building with visual studio, I forgot about that :laughing:

**Pull request merged**
