### PR TITLE
GH1040: Added new GitReleaseManager

### PR DESCRIPTION
**Pull request by gep13**
Relates to #1040

### CODE REVIEW

**Comment by devlead** [comment]
Wonder if we to make sure no caching issues for tools on AppVeyor should change dependency from package.config to build.cake in appveyor.yml?

**Comment by gep13** [comment]
@devlead sorry, not sure I follow your line of thinking. Are you talking about removing this?

https://github.com/cake-build/cake/blob/develop/appveyor.yml#L24-L25

**Comment by devlead** [comment]
Not removing but changing cache dependency from `tools\packages.config` to `build.cake`

**Comment by gep13** [comment]
@devlead ok, now I see what you mean...

**Comment by gep13** [comment]
@devlead added a new commit.  Let me know what you think, and I can rebase the PR ready for merging.

**Comment by devlead** [comment]
@gep13 LGTM, it skipped restoring tools 👍 please rebase and I'll merge.

**Pull request merged**
