### PR TITLE
Reverted build.sh from changes in commit eb1c4e9

### PR DESCRIPTION
**Pull request by mholo65**
build.sh is broken, can be seen here https://travis-ci.org/cake-build/cake/jobs/145653224

### CODE REVIEW

**Comment by gep13** [comment]
Relates to #1077

**Comment by gep13** [comment]
@mholo65 thank you for doing this.  I went through the process of rationalising the various bootstrappers that we have across the cake-build organisation last night, and this was contained within one of them, so I thought I should also add it here.  I didn't realise that it would have this result.

**Comment by mholo65** [comment]
@gep13 np, but there is still something fishy with Linux / osx builds... Travis seems to use v0.13.0 of Cake while building + some unit tests fail. Bitrise, I can't acces...

**Comment by gep13** [comment]
Yip, I "think" I have just fixed the problems with the Unit Tests.

**Comment by gep13** [comment]
@mholo65 yip, Travis CI just passed, and will now wait to see if Bitrise does as well.

**Comment by gep13** [comment]
@mholo65 and now the Bitrise CI is passing again.  Thanks again for all your help!

**Pull request merged**
