### PR TITLE
Adds support for collapsing "." in paths

### PR DESCRIPTION
**Pull request by daveaglick**
As discussed (briefly) on Gitter. Feel free to suggest additional tests or changes.

### CODE REVIEW

**Comment by gep13** [comment]
@daveaglick any chance you can rebase on latest develop?  Thanks!

**Comment by daveaglick** [comment]
Np

**Comment by patriksvensson** [comment]
@daveaglick Did you rebase this PR? If so, someone must have merged something else after you rebased it. If so, can I bother you to rebase it once more? Sorry!

**Comment by daveaglick** [comment]
No problem - the NuGet powershell PR got merged after, so should be an easy rebase.

**Comment by patriksvensson** [comment]
@daveaglick Perfect. Will merge this after CI pass. Thanks! :+1:

**Comment by patriksvensson** [comment]
Merged! Thanks! :+1:

**Pull request merged**
