### PR TITLE
Fix typos in GitVersion documentation

### PR DESCRIPTION
**Pull request by molehillrocker**

### CODE REVIEW

**Comment by gep13** [comment]
@molehillrocker ooops!  That was likely my fat fingers, and then copy/pasta 😄 

Thanks for catching that.  Will merge once the CI builds pass.

**Comment by gep13** [comment]
@molehillrocker thank you again for your contribution!

**Comment by molehillrocker** [comment]
You're welcome! :+1:

**Comment by gep13** [comment]
@molehillrocker **NOTE:** Should have said... This change won't appear on the site until we release 0.18.0, as the documentation is driven from the currently released version of Cake.

**Pull request merged**
