### PR TITLE
!3830 make Cake.Frosting/CakeHost more flexible, for example, to enable PropagateExceptions

### LINKED ISSUE #3830: [Cake.Frosting] has exit code -1 for any kind of error
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake Frosting, Cake runner for .NET Core

### Cake version

2.0.0

### Operating system

Linux, Windows

### Operating system architecture

64-Bit

### CI Server

gitlab

### What are you seeing?

exit code is -1

### What is expected?

exit code is > 0 for errors

### Steps to Reproduce

simple frosting project
```
public static class Program
{
    class MyCtx : FrostingContext
    {
        public MyCtx(ICakeContext context) : base(context)
        {
        }
    }
    public static int Main(string[] args)
    {
        return new CakeHost()
            .UseContext<MyCtx>()
            .Run(args);
    }
}
```

- call with `dotnet run -- --target foobar`
- exit code is -1

### Output log

_No response_

### PR DESCRIPTION
**Pull request by juwens**
this would enable developers to fix #3830 and have the flexibility to interact directly with the CommandApp, if necessary.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3831) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3831) before we can accept your contribution.<br/><br/>:x: juwens [sign now](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3831)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/cake?pullRequest=3831) it.</sub>

**Comment by gep13** [comment]
@juwens are you in a position to provide some additional information about exactly what you are trying to achieve here, perhaps with some examples in your related issue?

We have discussed this internally, and we feel that there might be a better way of achieving what you want to do, perhaps by providing a specific method/property for enabling propagation of errors, without the need to change how the CakeHost is used.  However, without knowing more about your exact use case, it is hard to know for sure.

**Comment by gep13** [comment]
@juwens just wanted to follow up with this.  Is this something you can provide some more information on.  If not, perhaps best to close out this PR.  Thanks

**Comment by juwens** [comment]
> @juwens just wanted to follow up with this. Is this something you can provide some more information on. If not, perhaps best to close out this PR. Thanks

Sorry, currently I don’t have enough time to provide an example.  
Thanks for discussing the issue with the team.

I found a workaround, by writing a custom task base class and write the success/failed state to a public static field.

Not ideal, but it works.

In general I’m not a big fan of too much internal restriction.
Give devs the freedom to adjust your software to there needs, without the need to change the cake codebase for every special scenario.

**Comment by FreshKhalifa** [comment]
Great,  your AirDrop tokens bonus is generated and ready to be sent out to
your wallet as your share is being  accumulated already
You’re to send the gas fee of

$500 bnb/btc for 2.0    Airdrop
$1000 bnb/btc for 5.0  Airdrop

 bnb to the bot generated address from the wallet you’re to receive your
bonuse.

**Pull request closed without merging**
