### PR TITLE
GH1138: Custom vstest loggers

### PR DESCRIPTION
**Pull request by Jericho**
Allow custom loggers to be specified when running unit tests with VSTest. This was discussed in gitter on 8/2016 and is also discussed in issue #1138

### CODE REVIEW

**Comment by patriksvensson** [comment]
@Jericho I have some thoughts about the new `LoggerName` property.

I don't think it needs to be kept in sync with `Logger` and vice versa, but simply make `LoggerName` take precedence over `Logger`, so if both are specified, `LoggerName` is used. Since `Logger` is obsoleted, both documentation and compiling the script will indicate that it should not be used so I don't think it's necessary with this fallback.

I'm thinking something like this:

```csharp
if(!string.IsNullOrEmpty(LoggerName))
{
  // Use LoggerName
}
else 
{
  if(Logger != null) 
  {
    // Convert Logger to a string representation
  }
}
```

**Comment by Jericho** [comment]
I agree that `LoggerName` should take precedence, that's how I implemented it. As far as where the conversion Logger to/from a string representation should take place, I thought it made more sense to group this logic in the getter and setter of the ~Logger~ property because this logic is only needed as long as we keep the obsolete property around. When we decide to remove the property, the conversion logic needs to also be removed and I think it's make sense to have all the code located in one single file as opposed to be in two separate files.

**Comment by patriksvensson** [comment]
@Jericho Hello again. Sorry for the late reply.

We've been discussing this change in the Cake maintainer team and decided that it's OK for the project to take a breaking change and simply change `Logger` to be a `string`. We don't think this will affect a lot of projects, and the change is trivial to make when updating to latest Cake. We would also keep the names of the properties in the settings class in sync with the actual tool which we want.

Would you want to make the change for this?

**Comment by Jericho** [comment]
Sure no problem, I'll take care of it

**Comment by Jericho** [comment]
yes no problem. Will take care of it late today.

**Comment by Jericho** [comment]
Hopefully I squashed correctly, let me know...

**Comment by gep13** [comment]
>@Jericho said...
Hopefully I squashed correctly, let me know...

So, looks like you still have 29 commits in this branch.  Would you like me to squash this down for you?

**Comment by Jericho** [comment]
Sure

**Comment by gep13** [comment]
@Jericho ah, looks like you got at least part of the way there.  Perhaps all that was missing was a `git push -f`.  Doing a normal push wouldn't work, and the changes would have been rejected.

Regardless though, I have just finished squashing and merging the changes that you made.  You can find them here: https://github.com/cake-build/cake/commit/ac8c58509db1c30388d752af8fe105523440949a

Due to the fact that I have done this, I will need to manually close this PR, however, correct attribution remains in place for the work that you carried out.

Thanks again for your help on this.

**Comment by Jericho** [comment]
Thank you!

**Pull request closed without merging**
