### PR TITLE
InferRuntimes does not require arguments

### PR DESCRIPTION
**Pull request by RehanSaeed**
More details can be found [here](https://github.com/dotnet/cli/issues/2278) and [here](https://github.com/dotnet/cli/issues/2372). This is currently blocking us [here](https://github.com/RehanSaeed/Serilog.Exceptions/pull/7).

### CODE REVIEW

**Comment by gep13** [comment]
@RehanSaeed was there a reason that you closed this?

**Comment by RehanSaeed** [comment]
I tried add using `--infer-runtimes` without Cake but it didn't help.

It turns out that the root cause is a known dotnet CLI issue (See the linked issue https://github.com/cake-build/cake/issues/1261 for details). There is a very nasty workaround but no fix on the horizon :(.

**Comment by gep13** [comment]
@RehanSaeed understood. However, is the change you suggested still a correct change in terms of usage of the cli?

**Comment by RehanSaeed** [comment]
Yes, it is correct but the docs for this option state:
> Temporary option to allow NuGet to infer RIDs for legacy repositories
I have spent some time googling this option but there isn't much info on what this means. To me it means that at some point fairly soon when the tooling matures, this option will go away. So is it still worth it?

**Comment by gep13** [comment]
@RehanSaeed I see what you mean.  Yes, perhaps best to leave this until it settles down.

**Pull request closed without merging**
