### PR TITLE
Added EnsureDirectoryExists alias

### PR DESCRIPTION
**Pull request by Redth**
This is for #821

Simply wraps the `DirectoryExists` and `CreateDirectory` aliases to create a directory if it doesn't already exist.

### CODE REVIEW

**Comment by gep13** [comment]
@Redth looks good to me.  If we can get some tests around this, this will make a great addition to Cake.  Thanks!

**Comment by devlead** [comment]
@Redth just checking for our release planning is this something you'll be able to look at in near future or should we postpone it to next release?

**Comment by Redth** [comment]
I'll try and do this on my flight tomorrow

**Comment by devlead** [comment]
@Redth superb :+1:

**Comment by Redth** [comment]
@devlead anything else you want to see here?

**Comment by devlead** [comment]
@Redth looks good to me 👍 , could you squash/rebase into single commit, rebase against latest develop

**Comment by Redth** [comment]
Closing this, will create a new PR with changes

**Comment by devlead** [comment]
@Redth ok!

**Pull request closed without merging**
