### PR TITLE
Removed extra apostrophe in TeamCity sanitization tokens

### PR DESCRIPTION
**Pull request by mholo65**
Fixes issue #725 

TeamCity lacks Unit Tests, I'll add some in PR #714 

//cc @gep13

### CODE REVIEW

**Comment by gep13** [comment]
@mholo65 perfect, thank you!

**Comment by gep13** [comment]
@mholo65 with regard to adding Unit Tests to an existing PR, I think we would prefer to keep the PR's as focused as possible on the subject of the PR.  i.e. add Unit Tests for the new functionality being added in that PR, but perhaps a separate PR for Unit Tests for existing functionality.

**Comment by mholo65** [comment]
@gep13 Sounds good!

**Comment by RichiCoder1** [comment]
Oops. Thanks for catching this!

**Pull request merged**
