### PR TITLE
(GH-1301) Adds DotCover Merge

### LINKED ISSUE #1301: Add DotCover Merge
Taken from #724

### PR DESCRIPTION
**Pull request by mholo65**
Adds DotCover Merge Alias

Fixes #1301

### CODE REVIEW

**Comment by mholo65** [comment]
Please don't merge yet

Getting following error when testing
**Failed to merge snapshots. Unknown storage type**

I'm also hitting same error message when running **dotcover merge** directly from commandline. Needs some investigation still from my side.

**Comment by mholo65** [comment]
ping @devlead tested with NUnit, everything working fine... 😄 

here's a small sample

```
#tool nuget:?package=NUnit.ConsoleRunner&version=3.2.0
#tool nuget:?package=JetBrains.dotCover.CommandLineTools

var target = Argument("target", "Default");

Task("Default")
  .Does(() =>
{
  CleanDirectory("./build");

  MSBuild("./foo.sln", new MSBuildSettings().WithProperty("OutDir", MakeAbsolute(new DirectoryPath("build")).FullPath));

  DotCoverCover(
    tool => tool.NUnit3("./build/Foo.Test1.dll"),
    new FilePath("./build/1.dcvr"),
    null
  );

  DotCoverCover(
    tool => tool.NUnit3("./build/Foo.Test2.dll"),
    new FilePath("./build/2.dcvr"),
    null
  );

  DotCoverMerge(new [] {
    new FilePath("./build/1.dcvr"),
    new FilePath("./build/2.dcvr")
  },
  new FilePath("./build/merged.dcvr"));

  DotCoverReport(
    "./build/merged.dcvr",
    "./build/merged.html",
    new DotCoverReportSettings {
      ReportType = DotCoverReportType.HTML
    }
  );
});

RunTarget(target);
```

**Comment by mholo65** [comment]
...and rebased

**Comment by devlead** [comment]
@mholo65 ...and merged! Thanks for contributing 👍

**Pull request merged**
