### PR TITLE
GH2850: Bump .NET Core SDK to 3.1.402

### LINKED ISSUE #2850: Bump .NET Core SDK to 3.1.402
See [release notes](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.8/3.1.402-download.md).

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #2850.

### CODE REVIEW

**Comment by gitfool** [comment]
Unrelated [failure](https://github.com/cake-build/cake/pull/2851/checks?check_run_id=1090381399#step:5:1316) in `Build / Build (macos-latest) (pull_request)`:
```
Error: An error occurred while retrieving package metadata for 'Cake.Kudu.Client.0.9.0' from source 'nuget.org'.While testing: /Users/runner/work/cake/cake/tests/integration/tools/Cake.Tool/tools/netcoreapp2.1/any/Cake.dll
Cake.Core.CakeException: .NET Core CLI: Process returned an error (exit code 255).
```

**Comment by devlead** [comment]
> 
> 
> Unrelated [failure](https://github.com/cake-build/cake/pull/2851/checks?check_run_id=1090381399#step:5:1316) in `Build / Build (macos-latest) (pull_request)`:
> 
> ```
> Error: An error occurred while retrieving package metadata for 'Cake.Kudu.Client.0.9.0' from source 'nuget.org'.While testing: /Users/runner/work/cake/cake/tests/integration/tools/Cake.Tool/tools/netcoreapp2.1/any/Cake.dll
> Cake.Core.CakeException: .NET Core CLI: Process returned an error (exit code 255).
> ```

@gitfool I've retriggered a new build.

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by devlead** [comment]
@gitfool your changes have been merged, thanks for your contribution 👍

**Pull request merged**
