### PR TITLE
GH2449: Add ARM64 target platform

### PR DESCRIPTION
**Pull request by GeertvanHorrik**

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
I'll pick this one up on Monday, I thought it was a simple fix.

**Comment by devlead** [comment]
@GeertvanHorrik is there an issue to go along with this PR?

**Comment by GeertvanHorrik** [comment]
@devlead nope, I just needed it for ARM64 compilation for UWP :)

**Comment by devlead** [comment]
Relates to #2449

**Comment by devlead** [comment]
@GeertvanHorrik your changes have been merged, thanks for your contribution 👍

**Pull request merged**
