### PR TITLE
GH1112: Refactor AppVeyorProvider to be a Tool<TSettings>-based tool

### LINKED ISSUE #1112: Change appveyor.exe to be run as a tool
Right now, Cake simply shells out to the the underlying appveyor.exe.  As a result, silent failures in things like UploadTestResults are not caught.

We should correctly handle appveyor.exe as a Tool, so that exit codes are correctly handled.

This was discussed here: https://github.com/cake-build/cake/issues/1097#issuecomment-234791625

### PR DESCRIPTION
**Pull request by agc93**
This resolves #1112 which was raised in response to #1097 .

This is "minimum required" refactoring of `AppVeyorProvider` to correctly inherit from `Tool<TSettings>` mostly to enable correct exit code handling etc.

I have also removed the constructor tests since those null checks are now happening in the base class.

Let me know if any changes need to be made, or if you'd prefer to wait and do a more holistic refactoring.

### CODE REVIEW

**Comment by devlead** [comment]
@agc93 FYI the tests are failing. Also seems first PR since we introduced a cla via .NET Foundation you can sign it here:
https://cla2.dotnetfoundation.org/

**Comment by agc93** [comment]
Ah damn, must have got something wrong. I'll have a look and try and clean it up

**Comment by agc93** [comment]
Oh I see what's happened now. I think this is going to need more serious changes than I originally thought. Any objection to closing this PR and I'll reopen again once I've actually got it working properly?

**Comment by devlead** [comment]
@agc93 sure or you could just force push over this branch and ping us here when you're done.

**Comment by gep13** [comment]
@agc93 the other thing to bear in mind is, I am planning on releasing 0.15.0 tonight, at which point we will start merging in the work that @patriksvensson has been doing on CoreClr support, so you might want to hold off on any other PR's until that work is complete.

**Comment by agc93** [comment]
Okay, I'll hold off on this one as I've worked out that properly refactoring the test classes around `ToolFixture` is probably the best way to go.

I'll wait until all those CoreCLR changes have been merged in and then revisit

**Comment by Philo** [comment]
Should this be refactored as a tool within Cake.Common or refactored out as a separate addin to support AppVeyor build worker api?

The appveyor.exe features feel like thery should live as a separate addin to Cake, but this then leads to a question of whether all the build system providers should go the same way.

**Comment by gep13** [comment]
@philo there already is an AppVeyor addin which further extends the DSL for AppVeyor:

https://github.com/Redth/Cake.AppVeyor

**Comment by devlead** [comment]
@agc93 are you in a position to rebase/refactor this towards current develop?

**Comment by agc93** [comment]
@devlead I probably *could*, but looking at this again, it's not a very good solution. Any objections to closing this PR and revisiting the issue, but doing it properly, when I get a chance?

**Comment by devlead** [comment]
@agc93 no issue, I'll just bump the issue to next release then.

**Pull request closed without merging**
