### PR TITLE
GH919: Feature/parse solutionfolder from sln

### PR DESCRIPTION
**Pull request by endrton**

### CODE REVIEW

**Comment by devlead** [comment]
Refers to #919

**Comment by devlead** [comment]
@endrton PR can't be merged with current develop, please rebase and ping us when you think it's ready for review.

**Comment by endrton** [comment]
@devlead I did the rebase, so i think it's ready for review.
It's my first PR, so be frank about it, no sugarcoating. :)

**Comment by devlead** [comment]
@endrton seems it's merged and not rebased, in it's current state it can't be merged automatically, I'll see if I can take a closer look in a couple of hours and provide some feedback.

**Comment by endrton** [comment]
Interesting, i've followed this document: [about-git-rebase](https://help.github.com/articles/about-git-rebase).
Not sure if it matters, but I squashed the commits, thou.

**Comment by devlead** [comment]
@endrton There's still 9 commits including a merge commit in this PR so something didn't go as planned 😉 I'm not at computer now, but no worries I'll check more closely ounce I'm at the keyboard.

**Comment by gep13** [comment]
@endrton it might help if you step through the instructions here:

https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md#respond-to-feedback-on-pull-request

If those steps aren't clear, then we really need to get them updated, so would be interested in your feedback here.

**Comment by endrton** [comment]
@gep13: Thanks, will do.
Does this also means that this [guide](http://cakebuild.net/docs/contributing/guidelines) is outdated?

**Comment by gep13** [comment]
@endrton yes, I think you are right, we need to update that page.  Could I get you to create an issue on the website repository to get that path synced with the contributing.md from the GitHub repo?  Thanks!

**Comment by endrton** [comment]
@gep13 done: [#92](https://github.com/cake-build/website/issues/92)

**Comment by gep13** [comment]
@endrton thank you for taking the time to make this contribution to Cake.  I have taken the liberty to rebase and merge this PR here: https://github.com/cake-build/cake/commit/23e44cd89788124c992591fe51e87a9f5d25454c As a result, I am going to manually close this PR, however, your work has been correctly attributed.

Thanks!

**Pull request closed without merging**
