### PR TITLE
GH-2790: Don't write CI service messages using log

### LINKED ISSUE #2790: Cake 0.38.1 is failing to write messages to TeamCity
### What You Are Seeing?
Cake is failing to write messages to TeamCity. Cake 0.37.0 works well.

### What is Expected?
Cake should write messages to TeamCity successfully

### What version of Cake are you using?
0.38.1

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Mac

### Are you running on a CI Server?  If so, which one?
TeamCity

### How Did You Get This To Happen? (Steps to Reproduce)
Running cake script from TeamCity with Cake 0.38.1
We're using methods:
```
TeamCity.WriteStartBuildBlock
TeamCity.WriteStartProgress
TeamCity.WriteEndProgress
TeamCity.WriteEndBuildBlock
TeamCity.SetBuildNumber
TeamCity.WriteProgressMessage
TeamCity.PublishArtifacts
```

### Output Log
All the calls has pretty the same output: 
~~~sh
[23:26:21][Step 6/6] Executing custom task setup action (CleanArtifactsFolder)...
[23:26:21][Step 6/6] 
[23:26:21][Step 6/6] ##teamcity[compilationStarted compiler='CleanArtifactsFolder']
[23:26:23][Step 6/6] Error while parsing TeamCity service message: Incorrect property name "[0mcompilationStarted compiler": should not contain spaces. Valid service message has a form of "##teamcity[messageName name1='escaped_value' name2='escaped_value']" where escaped_value uses substitutions: '->|', [->|[, ]->|], |->||, newline->|n
[23:26:21][Step 6/6] 
[23:26:21][Step 6/6] 
[23:26:21][Step 6/6] ##teamcity[progressStart 'CleanArtifactsFolder']
[23:26:23][Step 6/6] Error while parsing TeamCity service message: Property value not found (no "=" character). Valid service message has a form of "##teamcity[messageName name1='escaped_value' name2='escaped_value']" where escaped_value uses substitutions: '->|', [->|[, ]->|], |->||, newline->|n
[23:26:21][Step 6/6] 
[23:26:21][Step 6/6] 
[23:26:21][Step 6/6] ========================================
[23:26:21][Step 6/6] CleanArtifactsFolder
[23:26:21][Step 6/6] ========================================
[23:26:21][Step 6/6] Executing task: CleanArtifactsFolder
...
[23:26:21][Step 6/6] Finished executing task: CleanArtifactsFolder
[23:26:21][Step 6/6] Executing custom task teardown action (CleanArtifactsFolder)...
[23:26:21][Step 6/6] 
[23:26:21][Step 6/6] ##teamcity[progressFinish 'CleanArtifactsFolder']
[23:26:23][Step 6/6] Error while parsing TeamCity service message: Property value not found (no "=" character). Valid service message has a form of "##teamcity[messageName name1='escaped_value' name2='escaped_value']" where escaped_value uses substitutions: '->|', [->|[, ]->|], |->||, newline->|n
[23:26:21][Step 6/6] 
[23:26:21][Step 6/6] 
[23:26:21][Step 6/6] ##teamcity[compilationFinished compiler='CleanArtifactsFolder']
[23:26:23][Step 6/6] Error while parsing TeamCity service message: Incorrect property name "[0mcompilationFinished compiler": should not contain spaces. Valid service message has a form of "##teamcity[messageName name1='escaped_value' name2='escaped_value']" where escaped_value uses substitutions: '->|', [->|[, ]->|], |->||, newline->|n
~~~

~~~sh
[23:26:25][Step 6/6] ##teamcity[buildNumber '1.0.0_1332']
[23:26:28][Step 6/6] Error while parsing TeamCity service message: Property value not found (no "=" character). Valid service message has a form of "##teamcity[messageName name1='escaped_value' name2='escaped_value']" where escaped_value uses substitutions: '->|', [->|[, ]->|], |->||, newline->|n
~~~

~~~sh
[08:35:45][Step 6/6] ##teamcity[progressMessage 'Uploading to TestFlight']
[08:35:48][Step 6/6] Error while parsing TeamCity service message: Property value not found (no "=" character). Valid service message has a form of "##teamcity[messageName name1='escaped_value' name2='escaped_value']" where escaped_value uses substitutions: '->|', [->|[, ]->|], |->||, newline->|n
~~~

~~~sh
[08:46:52][Step 6/6] ##teamcity[publishArtifacts './artifacts']
[08:46:52][Step 6/6] Error while parsing TeamCity service message: Property value not found (no "=" character). Valid service message has a form of "##teamcity[messageName name1='escaped_value' name2='escaped_value']" where escaped_value uses substitutions: '->|', [->|[, ]->|], |->||, newline->|n
~~~

### PR DESCRIPTION
**Pull request by patriksvensson**
Also cleans up the CI provider code a bit.

Closes #2790

### CODE REVIEW

**Comment by patriksvensson** [comment]
@cake-build/cake-team Could someone review this?

**Comment by patriksvensson** [comment]
@mholo65 Can't help that. Nothing should have dependencies on that though so should be fine.

**Comment by gep13** [comment]
@mholo65 I just had a quick check of the obvious candidate for issues, which is the Cake.BuildSystems.Module from @agc93 and I "think" this should be ok.

**Comment by gep13** [comment]
@patriksvensson thanks for getting this done.  I have merged this into a hotfix branch, so I am going to go ahead and close out this PR.

**Pull request closed without merging**
