### PR TITLE
GH-4128: Fix Inconsistent determination of positional Argument when using context.Arguments versus context.Argument

### PR DESCRIPTION
**Pull request by EdLichtman**
…Arguments versus context.Argument

### CODE REVIEW

**Comment by augustoproiete** [comment]
Thanks for the PR @EdLichtman. Could you please reply to this as per the instructions here: https://github.com/cake-build/cake/pull/4139#issuecomment-1496141739 ?

**Comment by EdLichtman** [comment]
@augustoproiete I can do that, but it's not the complete changelist you have, and like I mentioned in Issue #4128 I haven't yet been able to run the tests. Would it be alright for me to perform the checks and get my change in without it? It looks like I haven't fully implemented the changes you implemented, so it's still an incomplete change.

**Comment by augustoproiete** [comment]
@EdLichtman That's fine. I can merge your changes and mine on the same PR - or you can bring the missing changes I did to this MR, and we close mine

**Comment by EdLichtman** [comment]
> 

@microsoft-github-policy-service agree

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by augustoproiete** [comment]
@EdLichtman your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
