### PR TITLE
GH2292: Remove all obsolete members

### LINKED ISSUE #2292: Remove obsolete methods and properties
This should be done when version 1.0.0 is released. So not yet 😄

### PR DESCRIPTION
**Pull request by patriksvensson**
This commit removes all obsolete members such as properties
and methods in preparation for the 1.0 release of Cake.

Closes #2292

### CODE REVIEW

**Comment by gep13** [comment]
@patriksvensson any thoughts on the failing CI builds as a result of these changes?

**Comment by patriksvensson** [comment]
Will take a look

**Comment by devlead** [comment]
> 
> 
> Will take a look

I've addressed the failing integration tests.

**Review by devlead — APPROVED** [review]
LGMT, I'll merge if CI passes.

**Comment by devlead** [comment]
Ok something references `DotNetBuildSettings`, failing at leas on mono. Will se of I see something obvious.

**Comment by devlead** [comment]
Probably it's because `Cake.Incubator` used in integration tests provides extension methods for `DotNetBuildSettings`.

**Comment by devlead** [comment]
@patriksvensson your changes have been merged, thanks for your contribution 👍

**Pull request merged**
