### PR TITLE
GH971: Added mono and experimental flags to CakeOptions

### PR DESCRIPTION
**Pull request by patriksvensson**

### CODE REVIEW

**Comment by gep13** [comment]
@patriksvensson this looks good to me, is there still things you wanted to add to this?  Also, is there an issue that this relates to?

**Comment by gep13** [comment]
Relates to #971

**Comment by gep13** [comment]
@patriksvensson never mind, found it :-D

**Comment by patriksvensson** [comment]
@cake-build/team This is ready for review.

**Comment by gep13** [comment]
@patriksvensson this looks good to me.  Can you rebase and I will get it merged.

**Comment by patriksvensson** [comment]
@gep13 Done :smile:

**Comment by gep13** [comment]
@patriksvensson thank you for your contribution :smile_cat:

**Pull request merged**
