### PR TITLE
WIP: (GH-1561) Add methods for argument checking

### LINKED ISSUE #1561: Add helper for argument validation
Each Cake addin requires some kind of argument validation (or at least should :). Instead of having to implement this in every addin it would be nice if this could be provided for common cases (null check, empty string check, ...) by Cake.Core.

### PR DESCRIPTION
**Pull request by pascalberger**
Adds a class for argument validation as discussed in #1561.

Implemented it myself instead of using the [ASP.NET version](https://github.com/aspnet/EntityFramework/blob/dev/src/Shared/Check.cs) but should provide very similar capabilities.

Fixes #1561

### CODE REVIEW

**Comment by pascalberger** [comment]
@mholo65 While making the methods available to Cake scripts makes sense, my main goal was also to provide this functionality to addins which wouldn't work with your proposal

**Comment by mholo65** [comment]
@pascalberger 
> my main goal was also to provide this functionality to addins which wouldn't work with your proposal

I understand your concerns, but at this point we would not like to have this as exposed as `public` functionality in `Cake.Core`. We however like the idea of changing all occurrences of `if (foo == null) { throw ... }` to the more convenient  `_foo = Check.NotNull(foo, nameof(foo))`. Additionally we would also like to expose it as _aliases_.

However, to have this _boilerplate_ code available also for `addin` developers, there are several possibilities:
* We provide a _source only_ NuGet package (`Cake.Shared.Source`) which would contain helpful boilerplate code (like this). Only problem is that as of VS2017, there seem to be some issue regarding tooling and _source only_ NuGet packages (both me and @patriksvensson have failed getting e.g. [XUnit.Assert.Source](https://www.nuget.org/packages/xunit.assert.source) to work in VS2017 with `*.csproj`).
* You include the source in you projects using a tool like [T4Include](https://github.com/mrange/T4Include)
* You download the source manually and include it in your projects.

**Comment by pascalberger** [comment]
@mholo65 OK, but in this case its not my priority to implement this functionality and I'll leave it to someone else to do so.

**Comment by mholo65** [comment]
@pascalberger ok. We are looking into different possibilities on how to expose this kind of functionality for addin-developers. A source only NuGet (once VS2017 tooling supports it) or a support library might be best solution.

**Pull request closed without merging**
