### PR TITLE
Update ReleaseNotesParser.cs

### LINKED ISSUE #1669: Release notes does not tolerate prerelease versions
### What You Are Seeing?
Release notes does not tolerate prerelease versions

### What is Expected?
Allow prerelease version in release notes

### What version of Cake are you using?
0.20

The problem is in this regex here => https://github.com/cake-build/cake/blob/08907d1a5d97b66f58c01ae82506280882dcfacc/src/Cake.Common/ReleaseNotesParser.cs#L25

To fix this just use the following regex =>
`(?<Version>\d+(\s*\.\s*\d+){0,3})(?<Release>-[a-z][0-9a-z-]*)?`

### PR DESCRIPTION
**Pull request by ManasviGoyal**
Fixes #1669

### CODE REVIEW

**Comment by augustoproiete** [comment]
Hi @ManasviGoyal thanks for the PR. Could you please add a reference to the issue that you're addressing with this PR?

ps: Also, let us know when it's ready for review by marking it as non-draft.

**Comment by ManasviGoyal** [comment]
@augustoproiete hi. can you pls tell what is the mistake in the change i made? it is showing build error

**Comment by augustoproiete** [comment]
@ManasviGoyal Are you able to see the list of builds that failed and a "Details" link on each one? (I ask because it's your first contribution, so I'm not sure GitHub is hiding this from you), but in case you can see that link, it should take you to the build log and you should be able to spot the error messages below:

```
/Users/runner/work/1/s/src/Cake.Common/ReleaseNotesParser.cs(25,33): error CS0246: The type or namespace name 'RegexRegex' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/src/Cake.Common/Cake.Common.csproj]
/Users/runner/work/1/s/src/Cake.Common/ReleaseNotesParser.cs(25,33): error CS0246: The type or namespace name 'RegexRegex' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/src/Cake.Common/Cake.Common.csproj]
/Users/runner/work/1/s/src/Cake.Common/ReleaseNotesParser.cs(25,33): error CS0246: The type or namespace name 'RegexRegex' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/src/Cake.Common/Cake.Common.csproj]
    0 Warning(s)
```

---

image

image

**Comment by ManasviGoyal** [comment]
@augustoproiete yes i can see. how can i fix it?

**Comment by augustoproiete** [comment]
@ManasviGoyal If you compile the code in Visual Studio, you should see the same error message. Double-clicking the error message should take you to the block of code that's causing the error and might help you spot the issue.

**Pull request closed without merging**
