### PR TITLE
Fix possible null dereference and remove excessive operator '?.'

### PR DESCRIPTION
**Pull request by Marusyk**
Here are small improvements

possible NRE
https://github.com/cake-build/cake/blob/0abc10c7a260320e92c81b799abf5d7f909f19d3/src/Cake.Core/IO/FilePath.cs#L76-L77

and remove the operator '?.' when expression is always not null

https://github.com/cake-build/cake/blob/0abc10c7a260320e92c81b799abf5d7f909f19d3/src/Cake.Core.Tests/Unit/CakeEngineTests.cs#L810-L812

Please review
Thank you in advance

### CODE REVIEW

**Comment by Marusyk** [comment]
can anybody fix the build?

**Comment by patriksvensson** [comment]
@Marusyk Triggered a rebuild for you. Ping again if it fails.

**Comment by Marusyk** [comment]
@patriksvensson what is plan about it? Close/Review?

**Comment by gep13** [comment]
@Marusyk apologies for not getting back to you sooner about this.  We will hopefully be reviewing all PR's soon.  Was there an issue created for the work in this PR?  Our contributing guidelines mention that you should first create an issue, and then work on the PR.

**Comment by Marusyk** [comment]
No, there is no related issue to it. Can I close it then?

**Comment by Marusyk** [comment]
@gep13 should I close it?

**Comment by gep13** [comment]
@Marusyk there is no need to close the PR, no.  Rather, create an issue, with some information about the change that is being made here, then we can use that issue when generating the release notes for the project.

**Comment by Marusyk** [comment]
I would close. It was a long time ago and I don't remember a case to reproduce it

**Pull request closed without merging**
