### PR TITLE
GH2203: Feature/octo promote

### PR DESCRIPTION
**Pull request by MichaelSL**
Added Octopus Deploy Promote release support.

### CODE REVIEW

**Comment by gep13** [comment]
@MichaelSL thank you for taking the time to submit this PR.  Was there an issue associated with this work?  If so, can you link it to this PR?

Thanks

**Comment by MichaelSL** [comment]
@gep13 nope there was no issue - only gitter request.
How could I check what is wrong in bitrise CI?

**Comment by devlead** [comment]
@MichaelSL i suspect rebasing against latest develop will sort that, you can read more about how to do that at
https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md#respond-to-feedback-on-pull-request

**Comment by MichaelSL** [comment]
Thank you! I will try to sort it out.

**Comment by MichaelSL** [comment]
@gep13 @devlead  could you please review the request? I still think that settings for 'Deploy' and 'Promote'  should be different (CodeFactor issue).

**Comment by devlead** [comment]
@MichaelSL your changes have been merged, thanks for your contribution 👍

**Pull request merged**
