### PR TITLE
GH2056: Added "FindFilesInDirectory"

### PR DESCRIPTION
**Pull request by Kralizek**
Added FindFilesInDirectory in GlobbingAliases.

Allows to retrieve all files matching a given pattern within a specified directory. Optionally it supports the possibility to recursively search in all subdirectories.

Usage sample
```csharp
Task("Test")
    .IsDependentOn("Build")
    .Does(() => 
{
    var testProjects = FindFilesInDirectory(testDirectory, "*.csproj", SearchScope.Recursive);

    foreach (var project in testProjects)
    {
        DotNEtCoreTest(project.FullPath);
    }
});
```

### CODE REVIEW

**Comment by Kralizek** [comment]
@devlead I couldn't find any test fixture I could use as a guideline for the specific case. Waiting for instructions to add tests.

**Comment by patriksvensson** [comment]
@Kralizek Thank you for your contribution.
I can't see an approved issue for this PR. What is the issue number?

**Comment by Kralizek** [comment]
@patriksvensson no issue created, I had a chat with @devlead on Gitter.

**Comment by patriksvensson** [comment]
@Kralizek All PR:s require an approved issue regardless. We need this for our release process.

**Comment by gep13** [comment]
Relates to #2056

**Pull request closed without merging**
