### PR TITLE
GH-750 Remaining documentation

### PR DESCRIPTION
**Pull request by phillipsj**
This finishes the list that is posted by adding XBuild, XUnit, MakeNSIS, and Roundhouse.

### CODE REVIEW

**Comment by devlead** [comment]
@phillipsj thanks for contributing :+1: , could you rebase against latest develop so the 8a3bce56bb0c73734f280d9ec9356a32fb285468  merge commit is removed, ping when done and we'll do a final review before merging.

**Comment by phillipsj** [comment]
Sorry about that, I will get it fixed.

**Comment by phillipsj** [comment]
@devlead I believe I got it fixed.  Again, I apologize for the mistake.

**Comment by devlead** [comment]
@phillipsj no worries, LGTM 👍 your changes have now been merged, thanks for your contribution!

**Pull request merged**
