### PR TITLE
GH-1349: OctoPack not passing --format to octo.exe

### PR DESCRIPTION
**Pull request by jjschlesinger**
Updated OctopusDeployPacker to include the --format switch if the Format property is set to OctopackFormat.Zip. If OctopusDeployPacker.NuPkg is set, then the switch is not added and uses the default format by octo.exe.

### CODE REVIEW

**Comment by jjschlesinger** [comment]
done.

**Comment by devlead** [comment]
@jjschlesinger thanks 👍 , could you please rebase against latest develop branch, then I'll look at doing a final review.

**Comment by devlead** [comment]
@jjschlesinger your changes have been merged, thanks for contributing 👍

**Comment by devlead** [comment]
Relates to #1349

**Pull request merged**
