### PR TITLE
Added support for packing NuGet project files (#637)

### PR DESCRIPTION
**Pull request by daveaglick**
This is based on pending PR #662, but wanted to get the changes in for review. Once that PR is merged, I'll rebase to develop and remove the WIP label.

### CODE REVIEW

**Comment by patriksvensson** [comment]
@daveaglick Sorry for not getting back sooner about this PR, but all of us have been busy the last couple of weeks and the PR backlog has been suffering for it.

Is this PR still WIP?

**Comment by patriksvensson** [comment]
@daveaglick Sorry, I just realized this was based on PR #662.

**Comment by daveaglick** [comment]
@patriksvensson No sweat - it's working fine right now by just calling the exe directly with `StartProcess()` so there's no rush on this one.

**Comment by patriksvensson** [comment]
@daveaglick PR #662 has been merged so it should not be blocking you anymore :smile:

**Comment by daveaglick** [comment]
Awesome! I'll clean this up on the flip side and let you know when it's ready.

**Comment by daveaglick** [comment]
Okay, this should be ready to merge. I rebased to the tip of the develop branch so you should be good to go (assuming CI gives the green light).

Once this gets pulled in I'll rebase and clean up my code for #666 and submit a PR for that one.

**Comment by patriksvensson** [comment]
Merged! Thanks for this! :+1:

**Pull request merged**
