### PR TITLE
Initial work on Mono.CSharp scripting support

### PR DESCRIPTION
**Pull request by Redth**
This is a work-in-progress PR for supporting Mono.

I took some advice from #81 and created an implementation of `IScriptSession` and `IScriptEngine` which use the `Mono.CSharp` script hosting.

This doesn't work yet, there's some obvious issues to work through, but the scaffolding is there for someone to help jump in who might be more familiar with `Mono.CSharp`.

Currently the code is generated almost identically to how the Roslyn generator works.  The `Evaluator` doesn't like this, and I believe things like the aliases will have to be wrapped up in a class to make work.

Any input is appreciated.

### CODE REVIEW

**Comment by devlead** [comment]
Cool, mono support is high on my wish list!

Hopefully at one point we'll be able to leverage the Roslyn work done for Mono/XamarinStudio
https://github.com/mono/roslyn

There are a few StyleCop issues in the code, think that's one reason it fails on AppVeyor now.

Really cool to see someone's starting to pursue this :+1:

**Comment by gep13** [comment]
@Redth I noticed in the Gitter Chat that you mentioned you are using xBuild to run the build under Mono.  As a result, you might not see the StyleCop errors that are being generated.  You can however seen them listed out in the MSBuild log, which starts here:

https://ci.appveyor.com/project/cakebuild/cake/build/0.4.2-build-524#L283

Hope that helps!

**Comment by Redth** [comment]
@gep13 Thanks, it also appears that the StyleCop addin for Xamarin Studio does the job too :)

**Comment by gep13** [comment]
> @Redth said...
Thanks, it also appears that the StyleCop addin for Xamarin Studio does the job too :)

Good to know, thanks! :smile_cat:

**Comment by Redth** [comment]
Closing in favour of #280

**Pull request closed without merging**
