### PR TITLE
detect msbuild17 path: typo fixed

### PR DESCRIPTION
**Pull request by blackmore466**
QIP Shot - Screen 015

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3736) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3736) before we can accept your contribution.<br/><br/>:x: blackmore466 [sign now](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3736)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/cake?pullRequest=3736) it.</sub>

**Review by devlead — CHANGES_REQUESTED** [review]
Windows filesystems aren't generally case sensitive, but right should be right, that said on my machine the casing is MSBuild, are we sure this is correct?

image

Looking at docs it's cased like `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe`
https://docs.microsoft.com/en-us/visualstudio/msbuild/whats-new-msbuild-17-0?view=vs-2022

**Comment by augustoproiete** [comment]
I can confirm the casing that @blackmore466 is seeing... Looks like it might be a difference in VS Community vs Enterprise:

Latest VS2022 Community as of now (17.0.2) just installed on a clean Windows 11 VM:

image

**Comment by blackmore466** [comment]
> Windows filesystems aren't generally case sensitive

@devlead yes, you're right. I think `IFileSystem.GetDirectory(string path)` is case sensitive because explicitly defining 
`ToolVersion = MSBuildToolVersion.VS2022` don't produce error. 
Problem with only `MSBuildToolVersion.Default` .

@augustoproiete thanks, I dont know that Enterprise has "MSBuild" in path. I will close pull request.

**Pull request closed without merging**
