### PR TITLE
Add script parameter back

### PR DESCRIPTION
**Pull request by adamhathcock**
(Not) discussed here :) https://github.com/cake-build/cake/issues/1207

### CODE REVIEW

**Comment by kcamp** [comment]
I would also like to see this returned to the script as I am making use of the script parameter to separate concerns.  i.e., `build.cake` for build tasks, `integration.cake` to automate running integration suites.
`integration.cake` loads `build.cake` as a dependency, but otherwise keeps the set of tasks for running the integrations [and additional helpers/utilities in a `utils.cake`] out of the context of the main build script.

**Comment by devlead** [comment]
@adamhathcock @kcamp what's the use case when building Cake?

The recommended bootstrapper still has this parameter:
[cake-build/resources/build.ps1#L43](https://github.com/cake-build/resources/blob/develop/build.ps1#L43)

**Comment by kcamp** [comment]
@devlead -- yes.  i misread the comments/situation.  the redistributed version of the script is what i took this to refer to.  my mistake, disregard.

**Comment by adamhathcock** [comment]
I didn't realize the "recommended" one is different from the official one.  Oops.

**Comment by gep13** [comment]
The recommended one has always came from a known URL, as documented here:

http://cakebuild.net/docs/tutorials/setting-up-a-new-project

The one used in the Cake repo is the same as every other bootstrapper in that it is customized as per requirements for the project that it is being used on.

**Pull request closed without merging**
