### PR TITLE
GH2443: Fix Erroneous "Target path must be an absolute path" when preserveFolderStructure is used with CopyFiles

### PR DESCRIPTION
**Pull request by ToMee99**
Fixed: #2443 

@augustoproiete I think I have a fix for you, but unfortunately I wasn't able to test it. There wasn't any documentation about testing my changes. And I had a hard time figuring out anything about building my solution. 

I tested all the edge cases and as it was stated in the issue #2443 **destinationPath** is always absolute, but **FilePaths** aren't. 

When **preserverFolderStructure** was set true, the function wanted to find the common path between all paths and create directories according the **FilePaths**. But when all the paths are not absolute (e. g. "CommonPath/File1.txt" and "source/file10.txt"), the function wasn't able to find a common directory and threw an Error. 

In my solution I'm converting all the **FilePaths** to absolute, so it is able to find a common directory.

Note:
Error is not thrown when you give the full path to the file (e. g. "C:/example/CommonPath/File1.txt" and "C:/example/source/file10.txt")

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3597) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3597) before we can accept your contribution.<br/><br/>:x: ToMee99 [sign now](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3597)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/cake?pullRequest=3597) it.</sub>

**Comment by ToMee99** [comment]
Hi, thank you @nils-a for making tests for this issue. But my sole problem is that I don't know how to attach a new cake enviroment with my altered cake scripts. I think I have to build the solution through the build.ps1 file, but then I have no idea how can i try out my editted cake tool in a cake enviroment.

Anyways I looked more closely into the CopyFiles function and I made "IEnumarable FilePath" absolute before passing it through the function. The previous solution was altering just one peace of the function, that's why it was not fucntioning.

**Comment by ToMee99** [comment]
Hi, I fixed the issue with one file copying!

I have two things that I'm not sure about:

1. I don't know if you are able to copy files out of the cake enviroment directory, so I added this in the if statement: `absoluteFilePaths.First().ToString().Contains(context.Environment.WorkingDirectory.FullPath)`
So if you are copying files out of cake enviroment it will copy the single file directly to 'dst' folder as it was prevously

2. In your suggestion:
`var result = Record.Exception(() => FileCopier.CopyFiles(context, null, new DirectoryPath(""), true));`
The code was giving an error, because the function has an overload and the argument we want to null, couldn't decide what overload to use, so I edited your suggestions to this:
`var result = Record.Exception(() => FileCopier.CopyFiles(context, (List<FilePath>)null, new DirectoryPath(""), true));`

Other thing that I want to mention is that the way I fixed sigle file copying, was subtracting the variable `commonPath` with the path from the 'src' folder. So then it has to create all the directories that are not in the `commonPath` variable.

@nils-a  I hope it is all good now.

**Comment by ToMee99** [comment]
I'm sorry, I almost forgot about copying a single file with absolte path, so that's fixed. I also added a test for single file copying with absolute path.

**Comment by augustoproiete** [comment]
@ToMee99 If you have a Twitter account _and_ want us to give you a [shout out](https://twitter.com/cakebuildnet/status/1446484388477345801) when this gets released, let us know your Twitter handle.

**Pull request merged**
