### PR TITLE
TeamCity Messages Enhancements

### PR DESCRIPTION
**Pull request by BlythMeister**
* Add function which sends the the build statistic servie message to TeamCity
* Add function to build status message with status to TeamCity (Append to existing, Prepend, or replace)

Fix: #4018
Fix: #4019

### CODE REVIEW

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by gep13** [comment]
@BlythMeister is there an issue associated with this PR? i.e. was this change already discussed somewhere?

**Comment by gep13** [comment]
> @BlythMeister said...
I can raise an issue to go with this if needed?

Yes, if you could, that would be appreciated.  This will mean that the issue can be assigned to the next milestone, and ideally, the commit messages in this PR would be updated to mention the issue, so that there is complete traceability for the changes.

**Comment by BlythMeister** [comment]
Ok, no worries, I'll make the changes before the weekend and raise the linked issue.

**Comment by BlythMeister** [comment]
@gep13 discussions raised (#4002 and #4003)

**Comment by BlythMeister** [comment]
@augustoproiete @gep13 This should be ready now with 2 issues (for some reason i can't get them to link) and the commits have the hash for them in too :)

**Comment by BlythMeister** [comment]
not sure what's going on with the build failure, but doesn't look related

**Comment by gep13** [comment]
@BlythMeister can you please see the message above regarding the CLA?  Is this something that you are in a position to sign?

**Comment by gep13** [comment]
@BlythMeister I have taken the liberty of making changes to your commit messages.  You created two discussions, when what we normally make use of are issues.  I have converted your discussions to issues, and I have updated the commit messages to point to the new issues.

Let me know if you have any questions.

**Comment by BlythMeister** [comment]
@microsoft-github-policy-service agree

**Comment by gep13** [comment]
> @BlythMeister said...
not sure what's going on with the build failure, but doesn't look related

Due to the rebase, the CI builds are being kicked off again, so we can see if things build this time.

**Comment by BlythMeister** [comment]
@gep13 I thought I already had when I contributed here before.

**Comment by gep13** [comment]
> @BlythMeister said...
I thought I already had when I contributed here before.

I believe that there has been a change to the CLA bot that we are making use of on this repository, as @devlead also had to sign it recently again. I don't have any other details on this at the minute though.

**Comment by BlythMeister** [comment]
@microsoft-github-policy-service agree [company=15below]

**Comment by BlythMeister** [comment]
@microsoft-github-policy-service agree

**Comment by BlythMeister** [comment]
@microsoft-github-policy-service agree company="15below"

**Comment by BlythMeister** [comment]
@gep13 I have no idea if those commands worked 🤣🤣
Hopefully they have

**Comment by gep13** [comment]
@BlythMeister fingers crossed!

Just had a quick chat with @devlead and he was working on cutting over to a new version of CLA bot, and that work has just finished.  Going forward, other folks shouldn't need to re-sign the CLA if they already have, but unfortunately, you were in the middle to the transition, which is why you had to do it.

Apologies about that!

**Comment by devlead** [comment]
> @gep13 I have no idea if those commands worked 🤣🤣 Hopefully they have
It worked🎉
image

**Comment by BlythMeister** [comment]
> @BlythMeister fingers crossed!
> 
> Just had a quick chat with @devlead and he was working on cutting over to a new version of CLA bot, and that work has just finished.  Going forward, other folks shouldn't need to re-sign the CLA if they already have, but unfortunately, you were in the middle to the transition, which is why you had to do it.
> 
> Apologies about that!

No need to apologise.
It's all good!

**Pull request merged**
