### PR TITLE
Obsolete unused NUnit3 arguments

### LINKED ISSUE #1651: NUnit3Settings ``Verbose`` flag obsoleted by NUnit console runner
### What You Are Seeing?
The NUnit3 test runner tool's ``NUnit3Settings `` has a ``Verbose`` flag, the NUnit console runner's command line argument this represents was removed.

### What is Expected?
Initially I was thinking the ``Verbose`` flag should set set the ``--trace=LEVEL`` command line argument.
However it looks like the functionality is different. Maybe just remove the ``Verbose`` flag completely.

[NUnit console runner command line.](https://github.com/nunit/docs/wiki/Console-Command-Line)

### What version of Cake are you using?
0.17

### What environment are you running on?  Windows? Linux? Mac?
Windows.

### Other

Link to NUnit console runner where argument was removed:
https://github.com/nunit/nunit-console/pull/170

Link to Cake's NUnit3Runner where argument is parsed:
https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NUnit/NUnit3Runner.cs#L166

### PR DESCRIPTION
**Pull request by akamud**
Closes #1651, NUnit3 [removed](https://github.com/nunit/nunit-console/issues/99) the `verbose` and `full` attributes.

I just added the `Obsolete` attributes to them.

### CODE REVIEW

**Comment by akamud** [comment]
Done and rebased on new changes on `develop`

**Comment by akamud** [comment]
Can't see why the OSX build failed.

**Comment by devlead** [comment]
@akamud  nuget issue, I've restarted the build.

**Comment by devlead** [comment]
@akamud your changes have been merged, thanks for your contribution 👍

**Pull request merged**
