### PR TITLE
Add Rager releases badge to README.md

### PR DESCRIPTION
**Pull request by blachniet**
[Rager.io](http://rager.io) is a service that makes it easy for developers to keep up-to-date with projects they use. When you publish a new releases of this project on NuGet, users that have signed up to receive notifications on [Rager.io](http://rager.io) will receive an email notification with a link to the new release.

### CODE REVIEW

**Comment by gep13** [comment]
@blachniet thank you for this PR.  I haven't heard about Rager.io before, so please excuse my ignorance...

How exactly does this work?  Is this addition to the readme.md required in order to enable notifications to be sent?

**Comment by blachniet** [comment]
No worries, it's new, so it's not surprising that you haven't heard of it.

You do not need to add the badge in order for users to receive notifications of new releases. Users can search for "cake" on http://rager.io/ and start watching from there as well.

The badge makes it a little easier for users to start watching for release, and...promotes the new service a little bit :relaxed:.

**Comment by devlead** [comment]
@blachniet looking at the service, badges just does a 302 to /?redirect_to=%2Fbadges (testet multiple browsers don't none end up at a badge generator as FAQ suggests), http://rager.io/faq & http://rager.io/privacy gives an invalid 302 on Edge & Explorer. There's no Location header so suspect that's the issue. Chrome/FireFox will abort the redirect so kinda works there. But you should take a look at that.
I haven't logged in yet so could be something related to that, but still not optimal first impression :wink:

**Comment by blachniet** [comment]
Wow, those are some pretty serious problems. I apologize for that, and will resolve them promptly. I'm sorry for taking up your time, but I really appreciate the detailed feedback!

**Comment by devlead** [comment]
@blachniet oh no worries, didn't want to come of as too negative :wink: Just som initial feedback. Haven't tried the service my self yet, but will do :+1:

**Pull request closed without merging**
