### PR TITLE
Add MSTest option for providing the tool (MSTest.exe) location

### PR DESCRIPTION
**Pull request by brettkc**
I was trying to use Cake to setup a build process and ran into issues running the MSTest tool. The issue is my Visual Studio is installed in an alternate location so Cake wouldn't find my MSTest.exe. I've altered it to allow a user defined path to be passed to MSTestSettings.

### CODE REVIEW

**Comment by patriksvensson** [comment]
@brettkc Thanks for your contribution, but if you want to provide the location to `mstest.exe`, this is already possible via the `ToolPath` property on `ToolSettings` (which `MSBuildSettings` inherit from). 

```csharp
MSTest("./**/*.Tests.dll", new MSTestSettings
{
  ToolPath = "./tools/mstest.exe"
});
```

**Comment by brettkc** [comment]
Ah, missed that -- thanks.

**Comment by patriksvensson** [comment]
@brettkc No problem. We should make this more clear in the documentation. Updating it now :smile:

**Comment by patriksvensson** [comment]
Added a fix for the homepage to show inherited methods and properties: http://cakebuild.net/api/cake.common.tools.msbuild/04799b3e

**Comment by brettkc** [comment]
Thanks @patriksvensson. Slightly related issue, would it make sense to add a TestCategory setting to the MSTestSettings object? (see: https://msdn.microsoft.com/en-us/library/ms182489.aspx#category).

**Comment by patriksvensson** [comment]
@brettkc Absolutely! Create a new issue for that so we're able to track it :smile:

**Pull request closed without merging**
