### PR TITLE
GH1924: Set User Agent string for in-process NuGet

### LINKED ISSUE #1924: Set UserAgent for in process nuget
Set to e.g. `Cake (C# Make)`...

Here are some hints.. https://github.com/NuGet/NuGet.Client/blob/4eed67e7e159796ae486d2cca406b283e23b6ac8/src/NuGet.Core/NuGet.Protocol/UserAgent.cs#L10

https://github.com/NuGet/NuGet.Client/blob/c282092fc575891b30186d7baa1962ce3fb1d4b4/src/NuGet.Core/NuGet.Protocol/UserAgentStringBuilder.cs#L27

### PR DESCRIPTION
**Pull request by mholo65**
- Fixes #1924

### CODE REVIEW

**Comment by gep13** [comment]
@mholo65 can you do a rebase of this PR, and I will get it merged?  Thanks!

**Comment by devlead** [comment]
@mholo65 @gep13 I've rebased this against latest develop and will take it for a spin.

**Comment by gep13** [comment]
@devlead :+1:

**Comment by devlead** [comment]
@mholo65  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
