### PR TITLE
GH1874: NuGet script load: Do not add include for all cake scripts when include already specified

### LINKED ISSUE #1874: NuGet script load: Do not add include for all cake scripts when include already specified
As discussed in #1527 the `NuGetLoadDirectiveProvider` should not add an include directive when already specified one in the script.

E.g.
`#load nuget:?package=BuildScripts.Cake&version=1.0.0.115109&include=Content/Defaults.cake`
will become
`#load nuget:?package=BuildScripts.Cake&version=1.0.0.115109&include=Content/Defaults.cake&include=./**/*.cake`

### PR DESCRIPTION
**Pull request by Sam13**
Fixes #1874

### CODE REVIEW

**Comment by Sam13** [comment]
Bitrise says: not authorized

**Comment by patriksvensson** [comment]
@Sam13 You've got StyleCop violations. Run the build locally to see the errors.

**Comment by devlead** [comment]
```
Extensions\UriExtensions.cs(12,25): error CS1591: Missing XML comment for publicly visible type or member 'UriExtensions' [C:\projects\cake\src\Cake.Core\Cake.Core.csproj]
Extensions\UriExtensions.cs(14,74): error CS1591: Missing XML comment for publicly visible type or member 'UriExtensions.GetQueryString(Uri)' [C:\projects\cake\src\Cake.Core\Cake.Core.csproj]
```

**Comment by Sam13** [comment]
Sorry bout that, too long since my last contribution. I have to compile in release 😲 

If I execute `PS D:\Projects\OpenSource\Cake> .\build.ps1` I get the following error

```
The term 'Get-CimInstance' is not recognized as the name of a cmdlet, function,
 script file, or operable program. Check the spelling of the name, or if a path
 was included, verify that the path is correct and try again.
At D:\Projects\OpenSource\Cake\.dotnet\dotnet-install.ps1:481 char:24
+ $free = Get-CimInstance <<<<  -Class win32_logicaldisk | where Deviceid -eq "
${installDrive}:"
    + CategoryInfo          : ObjectNotFound: (Get-CimInstance:String) [], Par
   entContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by Sam13** [comment]
What is still failing? Any chance to see the bitrise output myself?

**Comment by devlead** [comment]
@Sam13 unfortunately Bitrise doesn't offer public access, but this is the unit test that's failing
```
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: Cake.NuGet.Tests
  Discovered:  Cake.NuGet.Tests
  Starting:    Cake.NuGet.Tests
    Cake.NuGet.Tests.Unit.NuGetModuleTests+TheRegisterMethod.Should_Not_Register_The_NuGet_Load_Directive_Provider_When_Not_Using_In_Process_Client [SKIP]
      .NET Core test.
    Cake.NuGet.Tests.Unit.NuGetModuleTests+TheRegisterMethod.Should_Register_The_NuGet_Load_Directive_Provider_When_Using_In_Process_Client [SKIP]
      .NET Core test.
    Cake.NuGet.Tests.Unit.NuGetLoadDirectiveProviderTests+TheLoadMethod.Should_Install_Package_With_Other_Query [FAIL]
      Assert.Equal() Failure
                      ↓ (pos 6)
      Expected: nuget:?package=Cake.Recipe&exclude=test/main.ca···
      Actual:   nuget:/?package=Cake.Recipe&exclude=test/main.c···
                      ↑ (pos 6)
      Stack Trace:
          at Cake.NuGet.Tests.Unit.NuGetLoadDirectiveProviderTests+TheLoadMethod.Should_Install_Package_With_Other_Query () <0x41ca70c0 + 0x00067> in <filename unknown>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x41b5e7a0 + 0x000b7> in <filename unknown>:0 
    Cake.NuGet.Tests.Unit.NuGetLoadDirectiveProviderTests+TheLoadMethod.Should_Install_Package_Without_Include_Query [FAIL]
      Assert.Equal() Failure
                      ↓ (pos 6)
      Expected: nuget:?package=Cake.Recipe&include=./**/*.cake
      Actual:   nuget:/?package=Cake.Recipe&include=./**/*.cake
                      ↑ (pos 6)
      Stack Trace:
          at Cake.NuGet.Tests.Unit.NuGetLoadDirectiveProviderTests+TheLoadMethod.Should_Install_Package_Without_Include_Query () <0x41cc0bc0 + 0x0005f> in <filename unknown>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x41b5e7a0 + 0x000b7> in <filename unknown>:0 
  Finished:    Cake.NuGet.Tests
```

**Comment by Sam13** [comment]
Anyone? The build is passing locally...

**Comment by devlead** [comment]
@Sam13 could you rebase it against latest develop and we'll check the logs against that commit.

**Comment by Sam13** [comment]
@devlead Rebase done

**Comment by devlead** [comment]
@Sam13 your changes have been merged, thanks for your contribution 👍

**Pull request merged**
