### PR TITLE
GH2198: Adds settings for globber

### LINKED ISSUE #2198: Add GlobberSettings
Add overload to IGlobber that accepts a GlobberSettings.
The current method on the IGlobber interface should be deprecated with a warning.

```csharp
public sealed class GlobberSettings
{
    public DirectoryPath WorkingDirectory { get; set; }
    public Func<IDirectory, bool> Predicate { get; set; }
    public PathComparer Comparer { get; set; }
}
```

### PR DESCRIPTION
**Pull request by patriksvensson**
Closes #2198

### CODE REVIEW

**Comment by patriksvensson** [comment]
Accidentally made aliases obsolete with error. Will fix.

**Comment by patriksvensson** [comment]
Should be fixed now and ready for review.

**Comment by patriksvensson** [comment]
@devlead Rebased and resolved merge conflicts.

**Comment by devlead** [comment]
@patriksvensson  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
