### PR TITLE
GH1377: Support for uninstall packages using Chocolatey 

### PR DESCRIPTION
**Pull request by phillipsj**

### CODE REVIEW

**Comment by phillipsj** [comment]
@gep13 Yep I will, it may be tomorrow.

**Comment by gep13** [comment]
Perfect thanks!

**Comment by phillipsj** [comment]
@gep13 It has been rebased and squashed.

**Comment by gep13** [comment]
@phillipsj would you be in a position to correct the duplication error that CodeFactor is throwing?  I think correcting this is justified, as quite a few of the runners have the same properties.  You should be able to find examples in the code base where a common base class is used between runners.

**Comment by phillipsj** [comment]
@gep13 Yep I will fix it this week, I have seen the other locations.

**Comment by phillipsj** [comment]
@gep13 According to CodeFactor I need to implement more, but wanted to push so you could review.  Am I going in a good direction or would you prefer a different approach.

**Comment by gep13** [comment]
@phillipsj the approach you are following here looks good to me!

**Comment by gep13** [comment]
@phillipsj at some point can you rebase, and I will take a final look over it. Thanks!

**Comment by devlead** [comment]
Relates to #1377

**Pull request merged**
