### PR TITLE
Fix two typos in GitReleaseManagerAliases documentation

### PR DESCRIPTION
**Pull request by nils-a**

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Review by pascalberger — CHANGES_REQUESTED** [review]
Can you please also create an issue for it to have it tracked for release notes. Otherwise LGTM.

**Comment by gep13** [comment]
> Can you please also create an issue for it to have it tracked for release notes. Otherwise LGTM.

For a simple documentation chance like this, I tend to just add the PR directly onto the milestone and add the `Documentation` label.  This will then flow through into the Release Notes.

**Review by pascalberger — APPROVED** [review]

**Comment by devlead** [comment]
@nils-a your changes have been merged, thanks for your contribution 👍

**Pull request merged**
