### PR TITLE
GH2325: Added aliases for creating/updating .nuspec files 

### PR DESCRIPTION
**Pull request by arturcic**
Implements https://github.com/cake-build/cake/issues/2325

Some details on implementation:

- extracted the common parts from NuGetPackSettings and ChocolateyPackSettings into NuSpecSettings

- added the missing NuSpec elements as defined in the  [latest nuspec.xsd](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd)

- NuGetPackSettings and ChocolateyPackSettings use internally NuSpecSettings

- both NugetPacker and ChocolateyPacker use NuSpecProcessor 

- added 2 aliases : 
   1. ```NuSpec("./nuspec/TestNuget.nuspec", nuGetPackSettings);```
   2. ```NuSpec(nuGetPackSettings);```

### CODE REVIEW

**Comment by arturcic** [comment]
@pascalberger thank you for the feedback. I will take in consideration to keep the implementation separate for Chocolatey and Nuget specs. 

In this case, based on the [#1037 (comment)](https://github.com/cake-build/cake/issues/1037#issuecomment-255378318) I suggest we have such aliases:
- NuSpec(FilePath nuspecFilePath, NuGetPackSettings settings) - update the nuget nuspec
- NuSpec(FilePath nuspecFilePath, ChocolateyPackSettings settings)  - update the chocolatey nuspec
- NuSpec(NuGetPackSettings settings) -  add nuget nuspec
- NuSpec(ChocolateyPackSettings settings) -  add chocolatey nuspec

I will review the changes and will try to not introduce breaking changes.

**Comment by gep13** [comment]
@arturcic apologies for the delay in getting back to you about this one.  We just wanted to pick up on this one.  Are you still interested in working on this?  If not, should we go ahead and close it?

**Comment by arturcic** [comment]
I'll close it for now

**Comment by gep13** [comment]
@arturcic thanks for following up.  We can definitely discuss this later if you want to continue with it.

**Comment by arturcic** [comment]
Sure, there is still a need to create valid nuspec files, but for now I don't have the time to work on it

**Pull request closed without merging**
