### PR TITLE
GH-2831: AssemblyInfoParser

### LINKED ISSUE #2831: ParseAssemblyInfo does not detect lines with extra spaces
Loss of AssemblyInfo data when reading from an AssemblyInfo with spaces at the end of lines (outside the quotes)

When parsing the AssemblyInfo files, a regular expression is used, which reads in the lines, such as InternalsVisibleTo()
If a line has a space at the end, but outside the quotes, that line is not read in (and subsequently lost on re-write).

This is on Window 10, Cake 0.38, 64 bit.

I suspect that it just needs an adjustment to the Regex in order to identify lines with additional whitespace.

image

### PR DESCRIPTION
**Pull request by daveMueller**
closes #2831

### CODE REVIEW

**Review by devlead — CHANGES_REQUESTED** [review]
Hi @daveMueller,

Thanks for your contribution! 

There seems to be an issue with our CLA bot, so we can't accept this PR just yet.

Meanwhile some feedback, please add integration tests too

"fixtures" are located at

- [ ] https://github.com/cake-build/cake/tree/develop/tests/integration/resources/Cake.Common/Solution/Project/Properties

and integration tests using them at

- [ ] https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Common/Solution/Project/Properties/AssemblyInfoAliases.cake

Also please rebase away the merge commits against the latest upstream develop branch, so only commits related to the contribution are present in PR.

**Comment by daveMueller** [comment]
Ok I adapted the existing integration test to cover this bugfix and rebased the branch.

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by devlead** [comment]
@daveMueller your changes have been merged, thanks for your contribution 👍

**Pull request merged**
