### PR TITLE
GH2272: Update NuGet to 4.9.1

### LINKED ISSUE #2272: Update in-process NuGet client to support offline environments
NuGet.exe 4.8.1 supports possibility to [disable revocation check](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#revocation-check-mode) to avoid timeouts in revocation checks which takes approximately 4 minutes. Cakes in-proc NuGet client should also support environments in networks with access to internet blocked by a firewall.

### PR DESCRIPTION
**Pull request by mholo65**
- Fixes #2272

Didn't have time to fix the tests... At least @pascalberger can test the artifact.

### CODE REVIEW

**Comment by patriksvensson** [comment]
@pascalberger Did this PR solve the issue?

**Comment by pascalberger** [comment]
@patriksvensson Yes, this solves addin restoring in offline environments for me

**Comment by mholo65** [comment]
Rebased and fixed tests. I went the "easy" (only?!?) route and used reflection to create a instance of `VirtualSettingSection` for the tests. I'm a bad person, and I should feel bad 😄

**Comment by devlead** [comment]
@mholo65 your changes have been merged, thanks for your contribution 👍

**Pull request merged**
