### PR TITLE
Add alias for dotnet format command

### PR DESCRIPTION
**Pull request by Marusyk**
Issue #3479

Can have conflicts with #3341

@augustoproiete please check if I'm on the proper way.

Could you please help me with testing it? How can I use the new Alias in a real cake file to test it?

### CODE REVIEW

**Comment by augustoproiete** [comment]
@Marusyk For simple manual testing and debugging, you can update the [`Program.cs`](https://github.com/cake-build/cake/blob/v1.3.0/src/Cake/Program.cs) of Cake to run a specific `.cake` file that you have on your machine. e.g. Assuming you have a file `C:\marusyk\test-dotnet-format.cake` that calls your new `DotNetFormat` alias:

```diff
public static async Task<int> Main(string[] args)
{
+.   Environment.CurrentDirectory = @"C:\marusyk\";
+    args = new[] { "test-dotnet-format.cake" };
    return await new Program().Run(args);
}
```

ps: As part of the PR, you'll need to add integration tests to [`/tests/integration/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cake`](https://github.com/cake-build/cake/blob/v1.3.0/tests/integration/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cake), and they'll automatically run in the CI build when you push.

If you want to run the integration tests locally on your machine, you can call `./build.ps1 --target=Run-Integration-Tests`

**Comment by Marusyk** [comment]
Cannot debug it
```
public static async Task<int> Main(string[] args)
{
    Environment.CurrentDirectory = @"C:\marusyk\";
    args = new[] { "test-dotnet-format.cake" };
    return await new Program().Run(args);
}
```
Could you please advise?
image

**Comment by augustoproiete** [comment]
@Marusyk This is something we need to fix (will create an issue shortly), but if you press `F5` after seeing this exception, the debugging session will continue and should work as expected.

**Comment by augustoproiete** [comment]
@Marusyk You can create `DotNetCoreFormatSettings` to make it work right now, but this is fixed by https://github.com/cake-build/cake/pull/3696 so depending on when you come back to this one, it might not be an issue for you anymore

**Comment by augustoproiete** [comment]
> Cannot debug it
> 
> ```
> public static async Task<int> Main(string[] args)
> {
>     Environment.CurrentDirectory = @"C:\marusyk\";
>     args = new[] { "test-dotnet-format.cake" };
>     return await new Program().Run(args);
> }
> ```
> 
> Could you please advise? image
> 

This has been fixed by https://github.com/cake-build/cake/pull/3698

If you rebase your branch on top of `develop` you won't see this error anymore

**Comment by augustoproiete** [comment]
> Should I also create the `DotNetCoreFormatSettings` to make it work? image

@Marusyk https://github.com/cake-build/cake/pull/3696 has been merged and fixes the need for creating a `DotNetCoreFormatSettings`. If you rebase your branch on top of `develop` you should be good to go

**Comment by Marusyk** [comment]
Sorry for the late response, I'm going to close the PR. I don't have enough time and I will close it to not block it because maybe someone else wants to implement it

**Pull request closed without merging**
