### PR TITLE
Specifying Dependencies  for Multi Target package

### PR DESCRIPTION
**Pull request by MohsenAra**
Specifying Dependencies for Multi Target package like this 
[http://docs.nuget.org/Create/NuSpec-Reference](url)

&lt;dependencies&gt; 
   &lt;group&gt;
      &lt;dependency id=&quot;RouteMagic&quot; version=&quot;1.1.0&quot; /&gt;
   &lt;/group&gt;

   &lt;group targetFramework=&quot;net40&quot;&gt;
      &lt;dependency id=&quot;jQuery&quot; /&gt;
      &lt;dependency id=&quot;WebActivator&quot; /&gt;
   &lt;/group&gt;

   &lt;group targetFramework=&quot;sl30&quot;&gt;
   &lt;/group&gt;
&lt;/dependencies&gt;

for this porpose i add  TargetFramework  to NuSpecDependency
and change NuspecTransformer.cs for create grouped dependencies

### CODE REVIEW

**Comment by gep13** [comment]
Hello @MohsenAra, thank you for taking the time to contribute to Cake! For the most part, the changes that you are suggesting look good, and we should be able to incorporate them into Cake.  However, I need to ask, have you read through our [Contributing Guide](https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md).  In order to start to accept this PR, we are going to need a few things from you, i.e:

* Submit a new PR, using a feature branch, rather than the develop branch
* Create an issue to be associated with this PR
* Update your feature branch to use the latest version of develop branch

Please read through the contributing guide, and let me know if you have any questions.

**Comment by gep13** [comment]
@MohsenAra also, are you in a position to sign our CLA?

**Comment by MohsenAra** [comment]
@gep13 
hi i sign that

**Comment by gep13** [comment]
@MohsenAra thank you for signing the agreement.  Did you see my other comments about re-submitting this PR?  Thanks!

**Comment by devlead** [comment]
You could rebase current PR by following commands
```PowerShell
git remote add upstream https://github.com/cake-build/cake.git
git fetch upstream develop
git rebase upstream/develop
git push -f
```
We would also need some tests for these changes.

**Comment by devlead** [comment]
@MohsenAra are you in a position to address the suggested changes?

**Comment by devlead** [comment]
Relates to #1324

**Comment by devlead** [comment]
@MohsenAra your changes have been merged, thanks for contributing 👍

**Pull request merged**
