### PR TITLE
Integration tests

### LINKED ISSUE #362: Add integration tests
Add test coverage for actually executing aliases against tools.

Currently there's no test coverage to ensure that the runners for each alias actually execute the target tool property. We should add a suite of tests that provide a framework for testing tool runners against live tools and verifying the results.

See https://github.com/cake-build/cake/issues/359 as an example.

### PR DESCRIPTION
**Pull request by patriksvensson**
This is currently a work in progress where I try to add the initial code for our integration tests. Expect things to change until this is ready.

#### To run all tests

```
./tests/integration/build.ps1
```
````
./tests/integration/build.sh
```

#### To run a single test

```
./tests/integration/build.ps1 -Target "Cake.Common.IO.DirectoryAliases.CreateDirectory"
```
```
./tests/integration/build.sh -t "Cake.Common.IO.DirectoryAliases.CreateDirectory"
```

#### To skip building of Cake before running tests

````
./tests/integration/build.ps1 -SkipBuildingCake
```
```
./tests/integration/build.sh -s
```

This require Cake to be present somewhere under `./build/`.

Closes #362

### CODE REVIEW

**Comment by devlead** [comment]
@patriksvensson great, going to test some more, but currently when I run `./tests/integration/build.ps1` in repo root I get an error
`Could not find script 'C:/temp/dev/gh/devlead/cake/windows.cake'.`

See it exists in `tests/integration/windows.cake` so likely just an path issue.

**Comment by patriksvensson** [comment]
@devlead Ah, actually only run the script from the drectory itself so it's probably a working dir thing. Let me take a look.

**Comment by devlead** [comment]
Works if I run in folder, so we should just pushd, cd & popd.

**Comment by patriksvensson** [comment]
@devlead Made a mistake. Setting the absolute path to the script from the bootstrapper worked fine.

**Comment by patriksvensson** [comment]
@devlead Will push in 1 min. Just going to verify on OS X as well.

**Comment by devlead** [comment]
@patriksvensson LGTM :+1: , I'll merge as soon as travis passes.

**Pull request merged**
