### PR TITLE
Removed internal NuGet Package from Build Process

### PR DESCRIPTION
**Pull request by gep13**
Relates to #921 

@devlead does this make sense to you?

### CODE REVIEW

**Comment by patriksvensson** [comment]
I think this makes sense. We could also remove the nuspec.

**Comment by gep13** [comment]
@patriksvensson yes, that occurred to me as well.  I will get that removed too :+1:

**Comment by devlead** [comment]
Agree with @patriksvensson othwise LGTM.

**Comment by gep13** [comment]
@devlead @patriksvensson ok, I have made the suggested change :-D

**Comment by devlead** [comment]
@gep13 LGTM :+1: I'll merge once CI:s done.

**Pull request merged**
