### PR TITLE
GH2863: Add GitHub Actions workflow commands

### LINKED ISSUE #2863: Add support for GitHub Action workflow commands
### What You Are Seeing?

The [IGitHubActionsProvider](https://cakebuild.net/api/Cake.Common.Build.GitHubActions/IGitHubActionsProvider/) currently gives access to some environment values.

### What is Expected?

It should also provide [Workflow commands](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions)

### What version of Cake are you using?

0.38.5

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

N/A

### Are you running on a CI Server?  If so, which one?

GitHub Actions

### How Did You Get This To Happen? (Steps to Reproduce)

N/A

### Output Log

N/A

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #2863.

Note: implementation guided by looking at:
* https://github.com/actions/runner/blob/main/src/Runner.Common/ActionCommand.cs
* https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts

@devlead I'd love to squeeze in this pull request just in time for [Hacktoberfest](https://hacktoberfest.com). 😉

### CODE REVIEW

**Comment by devlead** [comment]
Could you add some integration tests here:
https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cake

Wonder if group / endgroup should have an IDisposable helper so one could do a using statement like TravisCI fold
https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Build/TravisCI/TravisCIDisposableExtensions.cs#L20-L28

That could be in follow up PR tomorrow if your short in time.

**Comment by gitfool** [comment]
It might take a couple of iterations to get the integration tests working satisfactorily. Bear with me.

**Comment by gitfool** [comment]
@devlead I see the group but not the [message inside the group](https://github.com/cake-build/cake/pull/4033/files#diff-92ae9ca49c2d2549ea21e64bfe626ba6bf58a241c5e9f3e90139ee997ee40004R41) for some reason. Is this something to do with how the integration tests are run? What am I missing?
```
2022-10-31T07:36:06.3862735Z ##[group]Cake group
2022-10-31T07:36:06.3863076Z ##[endgroup]
```

**Comment by devlead** [comment]
> @devlead I see the group but not the [message inside the group](https://github.com/cake-build/cake/pull/4033/files#diff-92ae9ca49c2d2549ea21e64bfe626ba6bf58a241c5e9f3e90139ee997ee40004R41) for some reason. Is this something to do with how the integration tests are run? What am I missing?
> 
> ```
> 2022-10-31T07:36:06.3862735Z ##[group]Cake group
> 2022-10-31T07:36:06.3863076Z ##[endgroup]
> ```

Think it needs to be quoted, example of the command used in wild
```cake
if (BuildSystem.GitHubActions.IsRunningOnGitHubActions)
{
    TaskSetup(context=> System.Console.WriteLine($"::group::{context.Task.Name.Quote()}"));
    TaskTeardown(context=>System.Console.WriteLine("::endgroup::"));
}
```
https://github.com/devlead/DPI/blob/2cd985ee19359486d1911f03f6066d98e99ca2cf/build/helpers.cake#L30-L34

Result:
image
https://github.com/devlead/DPI/actions/runs/3348953578/jobs/5548532403#step:5:28

**Comment by devlead** [comment]
Hmm also looks like `::` instead of `##` 🤔

**Comment by gitfool** [comment]
No, doesn't need to be quoted, and that output is from the log which seems to be related to azure pipelines legacy. Basically the group is working fine. It's the following information output that's missing. Same problem with the secret test.

**Comment by gitfool** [comment]
Annotations are working as expected. It's only the `Information` output that's missing. Good enough for now?

**Comment by devlead** [comment]
> Annotations are working as expected. It's only the `Information` output that's missing. I expect it will work fine outside of the integration tests. Good enough for now?

Ah, the information you won't see as the integration tests run at a lower verbosity.

I switched to a  `Console.WriteLine ` if it turns up I'm happy ;)

**Review by devlead — APPROVED** [review]
image

LGTM 👍

**Comment by devlead** [comment]
@gitfool your changes have been merged, thanks for your contribution 👍

**Pull request merged**
