### PR TITLE
GH900: Fix AnyCPU platform target when building a project

### LINKED ISSUE #900: Wrong platform "Any CPU" for project file (expects "AnyCPU")
### What You Are Seeing?

If I use the `MSBuild` method to build a .csproj (rather than a solution) with `PlatformTarget = PlatformTarget.MSIL`, the wrong value is passed for the `Platform` property: for a solution, the correct value is `"Any CPU"`, but for a project it's `"AnyCPU"` (no space). See [this article](http://kynosarges.org/WeirdDotNet.html#AnyCPU) for the explanation.

### What is Expected?

When the file to build is a project rather than a solution, Cake should pass "AnyCPU" as the platform.

### What version of Cake are you using?

0.11

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

Windows 8.1

### Are you running on a CI Server?  If so, which one?

Not right now

### How Did You Get This To Happen? (Steps to Reproduce)

By building a .csproj with `PlatformTarget = PlatformTarget.MSIL`

### Output Log

> "D:\path\to\the\project\MyProject.csproj" (build target) (1) ->
> (_CheckForInvalidConfigurationAndPlatform target) ->
>   C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(723,5): error : The OutputPath property is not set for project 'MyProject.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='Any CPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\path\to\the\project\MyProject.csproj]

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #900

### CODE REVIEW

**Comment by patriksvensson** [comment]
@thomaslevesque Looks good to me! Can you rebase against `develop` and I'll merge as soon as I get an opportunity.

**Comment by thomaslevesque** [comment]
> Can you rebase against develop

Done

**Comment by gep13** [comment]
@thomaslevesque apologies!  Can you rebase one more time, and I will get this merged.  Thanks!

**Comment by thomaslevesque** [comment]
> @thomaslevesque apologies! Can you rebase one more time, and I will get this merged. Thanks!

Sure, not problem. Done ;)

**Comment by gep13** [comment]
@patriksvensson @devlead  any thoughts on why the Travis build failed here?

**Comment by patriksvensson** [comment]
@gep13 Hmm. Maybe old Cake is cached for some reason. Not sure why that fails. I think that error was fixed. @devlead What do you think?

**Comment by devlead** [comment]
@gep13 @patriksvensson I've cleared all caches.

**Comment by thomaslevesque** [comment]
Now the build seems to be stuck in a loop... it keeps restarting from zero, reinstalling Mono every time. Package restoration is taking forever (very long response times from MyGet)

**Comment by devlead** [comment]
@thomaslevesque I've restarted the build, NuGet seems especially cranky on Travis Linux today 😉

**Comment by gep13** [comment]
@thomaslevesque thank you for your contribution to Cake! :+1:

**Pull request merged**
