### PR TITLE
GH856: Added pushing Code Coverage results

### PR DESCRIPTION
**Pull request by gep13**
Relates to #856

### CODE REVIEW

**Comment by gep13** [comment]
@cake-build/team I am not convinced that this is doing what I think it is, but I thought I would put it out there for review.

Thoughts?

**Comment by patriksvensson** [comment]
I think it looks good. Van't see any obvious problems with this. :+1:

**Comment by patriksvensson** [comment]
Can't* 

Can't edit comments on the phone...

**Comment by gep13** [comment]
@patriksvensson the main problem that I see just now is that the generated report only reports an 8% code coverage, which i really don't think is right:

image

I think there is an issue with running OpenCover with dotnet test, or I am simply doing something wrong.  I will need to dig into it some more.

**Comment by gep13** [comment]
@cake-build/team ok, I have just updated this PR.  The end result of the build is a code coverage report that looks like this:

image

I am waiting on the report at coveralls.io to be processed, but I suspect that it will show a similar story.

Thoughts?

**Comment by devlead** [comment]
Interesting, think Cake.Testing/Xunit should be excluded though.

**Comment by gep13** [comment]
>@devlead said...
Interesting, think Cake.Testing/Xunit should be excluded though.

To be clear, are you saying exclude both `Cake.Testing` and `Cake.Testing.XUnit`?  @patriksvensson you agree?

**Comment by patriksvensson** [comment]
@Ep13 Yes, I agree with @devlead

**Comment by patriksvensson** [comment]
Sorry, that was supposed to be to @gep13 :smile:

**Comment by devlead** [comment]
@gep13 @patriksvensson agree.

**Comment by gep13** [comment]
Here is the updated report:

image

Rebasing just now...

**Pull request merged**
