### PR TITLE
Add alias for dotnet workload install command

### LINKED ISSUE #3481: Add alias for dotnet workload install command
`dotnet workload install` - Installs optional workloads. Introduced with .NET 6 SDK.

The `dotnet workload install` command installs one or more optional workloads. Optional workloads can be installed on top of the .NET SDK to provide support for various application types, such as .NET MAUI and Blazor WebAssembly AOT.

Docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install

### PR DESCRIPTION
**Pull request by Marusyk**
Add an alias for dotnet workload list command

Fixes #3481

Please review
Thank you in advance

### CODE REVIEW

**Comment by Marusyk** [comment]
Hi @augustoproiete any plans to review it?

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by devlead** [comment]
@Marusyk your changes have been merged, thanks for your contribution 👍

**Comment by paulomorgado** [comment]
How can this be used? I couldn't find any examples or documentation.

**Comment by paulomorgado** [comment]
I was able to use it like this:

```csharp
public static class Program
{
    public static int Main(string[] args)
    {
        return new CakeHost()
            .UseSetup<Setup>()
            .InstallTool(new Uri("nuget:?package=MSBuild.SonarQube.Runner.Tool&version=4.*"))

    }
}
public class Setup : IFrostingSetup
{
    void IFrostingSetup.Setup(ICakeContext context, ISetupContext info)
    {
        context.DotNetWorkloadInstall("aspire");
    }
}
```

I was expecting it to be something like `InstallTool`.

**Pull request merged**
