### PR TITLE
GH2051: Added support for recently added MSBuild.exe /restore option

### PR DESCRIPTION
**Pull request by sanderaernouts**
Added support directly from settings API for the MSBuild /restore option. Fix for issue https://github.com/cake-build/cake/issues/2051

### CODE REVIEW

**Comment by gep13** [comment]
@sanderaernouts thank you for submitting this PR.  Was there an issue created to go along with it?  As per our contributing guidelines?

**Comment by sanderaernouts** [comment]
@gep13 I created it based on a Gitter question. I added https://github.com/cake-build/cake/issues/2051 for this PR and modified the PR description to point to the issue.

**Comment by sanderaernouts** [comment]
@gep13  thanks! We can use ArgumentCustomization as a workaround for now. Do you have an ETA for 0.27.0 already?

**Comment by devlead** [comment]
@sanderaernouts  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
