### PR TITLE
GH2369: Update Roslyn to 2.10.0

### LINKED ISSUE #2369: Update Roslyn to 2.10.0

### PR DESCRIPTION
**Pull request by devlead**
* fixes #2369

### CODE REVIEW

**Comment by gep13** [comment]
@devlead is the CLA bot broken?

**Comment by devlead** [comment]
> @devlead is the CLA bot broken?

Good question @jongalloway is it?

Looking at web hook logs getting "We couldn’t deliver this payload: Service Timeout", 

Redelivered webhook and got 200OK for this PR, so hopefully it's something temporary.

**Comment by gep13** [comment]
>@devlead said...
Redelivered webhook and got 200OK for this PR, so hopefully it's something temporary.

Does this mean that the CLA check should have been updated?

**Comment by gep13** [comment]
Obviously, I am happy to merge this, as I know that you have signed the CLA, just wondering if we need to keep this PR open to allow for testing/verification.

**Comment by devlead** [comment]
@gep13 easy enough to open a new PR to test, I'll send an email to @jongalloway and @onovotny and we can investigate more if needed.

**Comment by devlead** [comment]
> Does this mean that the CLA check should have been updated?

That was outcome I was hoping for as the initial web hook call failed, but perhaps something deeper.
GitHub has a very short timeout so could've been that it was received the first time.

**Comment by gep13** [comment]
@devlead your changes have been merged, thanks for your contribution 👍

**Comment by jongalloway** [comment]
I'm checking on the CLA bot. Config looks correct, I'm working with the support team since we've had some reports of outages on other projects.

**Comment by devlead** [comment]
@jongalloway PR after worked ( cake-build/cake#2392 ), so config indeed seems correct.

**Pull request merged**
