### PR TITLE
GH887: Add certificate subject name setting for SignTool

### PR DESCRIPTION
**Pull request by thomaslevesque**
Just another way to select a certificate

### CODE REVIEW

**Comment by gep13** [comment]
@thomaslevesque thank you for submitting a PR to Cake.

Have you raised an issue about this problem?  If so, can you link to it?  If not, can I ask that you read through our contributing guide? https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md

Thanks!

**Comment by thomaslevesque** [comment]
@gep13 sorry, forgot to create an issue. But actually someone else already opened one for this feature: #887

**Comment by gep13** [comment]
Relates to #887

**Comment by gep13** [comment]
>@thomaslevesque said...
But actually someone else already opened one for this feature: #887

Perfect, thank you.

**Comment by devlead** [comment]
@thomaslevesque your changes have been merged, thanks for contributing 👍

**Pull request merged**
