### PR TITLE
Fixing issue #497 when path includes an ampersand

### PR DESCRIPTION
**Pull request by marcosnz**
Also ties up a "TODO" comment regarding plus sign in path

### CODE REVIEW

**Comment by gep13** [comment]
@marcosnz are you in a position to rebase this change against the latest develop branch?  That will greatly help us to review this PR in order to get it merged in.  Thanks!

**Comment by marcosnz** [comment]
@gep13 ummm... will try - my GIT knowledge is a bit shakey - always a little scared of a rebase :)
Any hints appreciated

**Comment by gep13** [comment]
Sure, thing, let's see if I can help :-)

I would point you at the following, as a general guide:

https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#respond-to-feedback-on-pull-request

Specifically for Cake, you would want to do the following:

```
git remote add upstream https://github.com/cake-build/cake.git
git checkout develop
git fetch upstream
git rebase upstream/develop
git push
git checkout GlobberAmpersand
git rebase develop
git push -f
```

The above assumes that you don't already have an upstream repository configured, and that you don't have any pending/uncommitted changes.

The above will doing the following:

- "Connect" your fork to the cake repo via a remote called upstream
- Fetch the latest changes from the upstream repo, i.e. cake
- Rebase your local develop branch in your fork against the official develop branch of Cake
- Push those latest changes of the develop branch to your forked version
- Checkout the branch that you have been working on
- Rebase the latest changes from the new updated local develop branch into your branch, replaying your changes on top of them
- Force push your changes up to the GlobberAmpersand branch on your fork, which will then update this PR

Hope that all makes sense!  If not, feel free to ask any questions.

**Comment by marcosnz** [comment]
Umm... is that better?

**Comment by gep13** [comment]
Hmm, still seems to be far more commits on this branch than I would have expected.  I am just signing off for the night, but I will try to take a look tomorrow morning, and let you know what if I can figure anything out.

Unless @patriksvensson or @devlead get in before me.

**Comment by marcosnz** [comment]
I have started again and created new PR #508 
Closing this PR.

**Pull request closed without merging**
