### PR TITLE
[WIP] OMG Don't merge! - Inital work on Win32 long path support

### PR DESCRIPTION
**Pull request by devlead**
This is just an ugly hack for discussion and see what's the minimal work needen to support long paths on Windows.

Issue currently .Net only supports max 260 chars in paths and even less for folders names, this is a real issue especially in web projects and deployments which can have more complex folder structures.
Windows itself support longer paths thru other API's, there are a couple of libraries enabling this, for this prof of concept I've chosen [Pri.LongPath](https://github.com/peteraritchie/LongPath) which has drop in replacements for standard .Net classes i.e. `Path`, `DirectoryInfo`, `FileInfo`, etc.

What would have been nice would be if we could have some kind of directive or similar for replacing/patching `IFileSystem` via an add-in at runtime. This could also enable support for other foreign file systems.

What this PR adds is an new `Cake.Core.IO.LongPath` project/assembly with `Pri.LongPath` implementations of `IFileSystem`, `IFile` and `IDirectory`.

It also really adds a bad piece of code to patch the `IContext`/`IGlobber` file system via an `IContext.OmgTestFileSystemMethod(IFileSystem)` 

In `.\src\Cake.Core.IO.LongPath\` there's a `TestFileSystem.cake` that does a simple directory & globber test with standard .Net and then switches to `Cake.Core.IO.LongPath`.

The script first loads needed assemblies
```csharp
#r "bin/Debug/Pri.LongPath.dll"
#r "bin/Debug/Cake.Core.IO.LongPath.dll"
```
Then defines some test data and tests
```csharp
var binDir = Directory("bin/Debug");
var testPaths = new DirectoryPath[]
                    {
                        "so this is a quick and dirty test of handling long paths within Cake.",
                        "using Pri.LongPath for Dotnet",
                        "though it has to be very long path like a namespace",
                        "Somtehing like Cake.Core.IO.LongPath",
                        "would probably put it over the top."
                    };

Action<string, Action> test = (scope, action) =>
{
    try
    {
        Information("Test: {0}", scope);
        action();
        Information("Success!");
    }
    catch(Exception ex)
    {
        Error("Failed {0}", ex);
    }
};

Action testCreateDir = () => {
    DirectoryPath current = binDir;
    foreach(var testPath in testPaths)
    {
        Information("Start processing {0}", testPath);
        current = current.Combine(testPath);
        if (!DirectoryExists(current))
        {
            CreateDirectory(current);
        }
    }
};
```
And then executes the tests using standard .Net
```csharp
test("Create dir using standard .Net", testCreateDir);
test("Globber using standard .Net", ()=>GetFiles(binDir.Path + "/**/*.sln"));
```
Then patches/changes `IFileSystem` to use `Cake.Core.IO.LongPath` implementation.
```csharp
Context.OmgTestFileSystemMethod(new Cake.Core.IO.LongPath.FileSystem());
```
And executes same tests.
```csharp
test("Create dir using Pri.LongPath", testCreateDir);
test("Globber using Pri.LongPath", ()=>GetFiles(binDir.Path + "/**/*.sln"));
```
Output first tests are
```
Test: Create dir using standard .Net
Start processing so this is a quick and dirty test of handling long paths within Cake.
Start processing using Pri.LongPath for Dotnet
Start processing though it has to be very long path like a namespace
Start processing Somtehing like Cake.Core.IO.LongPath
Start processing would probably put it over the top.
Failed System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at Cake.Core.IO.Directory..ctor(DirectoryPath path) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Directory.cs:line 35
   at Cake.Core.IO.FileSystem.GetDirectory(DirectoryPath path) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\FileSystem.cs:line 25
   at Cake.Common.IO.DirectoryAliases.DirectoryExists(ICakeContext context, DirectoryPath path) in c:\temp\dev\gh\devlead\cake\src\Cake.Common\IO\DirectoryAliases.cs:line 377
   at Submission#0.<.ctor>b__2()
   at Submission#0.<.ctor>b__0(String scope, Action action)
Test: Globber using standard .Net
Failed System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
   at Cake.Core.IO.Directory.GetDirectories(String filter, SearchScope scope) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Directory.cs:line 51
   at Cake.Core.DirectoryExtensions.GetDirectories(IDirectory directory, String filter, SearchScope scope, Func`2 predicate, Action`1 action) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\Extensions\DirectoryExtensions.cs:line 43
   at Cake.Core.DirectoryExtensions.GetDirectories(IDirectory directory, String filter, SearchScope scope, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\Extensions\DirectoryExtensions.cs:line 24
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 172
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 183
   at Cake.Core.IO.Globber.Match(String pattern, Func`2 predicate) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\Globber.cs:line 99
   at Cake.Core.IO.GlobberExtensions.Match(IGlobber globber, String pattern) in c:\temp\dev\gh\devlead\cake\src\Cake.Core\IO\GlobberExtensions.cs:line 52
   at Cake.Common.IO.GlobbingAliases.GetFiles(ICakeContext context, String pattern) in c:\temp\dev\gh\devlead\cake\src\Cake.Common\IO\GlobbingAliases.cs:line 39
   at Submission#0.GetFiles(String pattern)
   at Submission#0.<.ctor>b__4()
   at Submission#0.<.ctor>b__0(String scope, Action acti on)
```

A bit shorter output using `Cake.Core.IO.LongPath` 
```
Test: Create dir using Pri.LongPath
Start processing so this is a quick and dirty test of handling long paths within Cake.
Start processing using Pri.LongPath for Dotnet
Start processing though it has to be very long path like a namespace
Start processing Somtehing like Cake.Core.IO.LongPath
Start processing would probably put it over the top.
Success!
Test: Globber using Pri.LongPath
Success!
```

This functionality could really affect core, want a clean and good solution we could live with, so just leaving this PR for discussion & ideas.

### CODE REVIEW

**Comment by RichiCoder1** [comment]
Random mention: the CoreFX team just merged in extend path syntax for long paths on windows and is actively works to remove other blockers. See issue https://github.com/dotnet/corefx/issues/645

**Comment by patriksvensson** [comment]
@RichiCoder1 Very interesting and good to know! :+1:

**Comment by RichiCoder1** [comment]
CoreFX just merged long path support, but I just realized I'm not sure how that get's back to us.

**Comment by devlead** [comment]
@RichiCoder1 well of they get Roslyn running on CoreFX we're all set ;)

**Comment by devlead** [comment]
Closing this now, will reopen once we have #646 fixed.

**Comment by gep13** [comment]
@devlead as per comment above, I think this needs to be re-opened, but it looks like you have deleted the source branch.

**Comment by devlead** [comment]
.Net 4.6 and CoreCLR comes with long name support, in this case it was an ugly hack, but would likely be better redone as it's own module and not incorporated into Cake core.

**Comment by gep13** [comment]
@devlead so thoughts on this issue? https://github.com/cake-build/cake/issues/599

**Comment by devlead** [comment]
@gep13 an module replacing IFileSystem and decedent interfaces for long name support utilizing Pri.LongPath seems like a good place to start. Would be a good alternative for OSs that doesn't support long names for one or another reason. Wouldn't "taint" Cake but still provide a solution.

**Pull request closed without merging**
