### PR TITLE
GH-3065: Add DOTNET_ROLL_FORWARD setting to DotNetCoreSettings

### LINKED ISSUE #3065: Add DOTNET_ROLL_FORWARD setting to DotNetCoreSettings
When running a DotNetCore command or tool via Cake, we can control the roll forward policy by setting an environment variable [DOTNET_ROLL_FORWARD](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#major-version-runtime-roll-forward) in the [tool's settings](https://github.com/cake-build/cake/blob/8bc15841e97944291946a89f335562244965247e/src/Cake.Common/Tools/DotNetCore/DotNetCoreSettings.cs).

This is important when we want to run dotnet tools that target only older versions of the .NET SDK and we don't have the SDK that the tool targets (but we have a newer one).

As an example, the [Wyam.Tool](https://www.nuget.org/packages/Wyam.Tool/) targets the .NET Core SDK 2.1, and in order to run it on a machine that doesn't have 2.1 installed (but has .NET SDK 5.0, for example) we'd need to set the roll forward policy:

```
Wyam(new WyamSettings
{
    // ...
    EnvironmentVariables = new Dictionary<string, string>
    {
        { "DOTNET_ROLL_FORWARD", "Major" },
    },
});
```

One of the following values must be specified. If the setting is omitted, Minor is the default.

| Value | Description |
|:---:| --- |
| LatestPatch | Roll forward to the highest patch version. This disables minor version roll forward.
| Minor | Roll forward to the lowest higher minor version, if requested minor version is missing. If the requested minor version is present, then the LatestPatch policy is used.
| Major | Roll forward to lowest higher major version, and lowest minor version, if requested major version is missing. If the requested major version is present, then the Minor policy is used.
| LatestMinor | Roll forward to highest minor version, even if requested minor version is present. Intended for component hosting scenarios.
| LatestMajor | Roll forward to highest major and highest minor version, even if requested major is present. Intended for component hosting scenarios.
| Disable | Don't roll forward. Only bind to specified version. This policy isn't recommended for general use because it disables the ability to roll forward to the latest patches. This value is only recommended for testing.

---

N.B.: Although there are multiple ways to set the roll forward policy (e.g. `global.json`) setting it on a per-tool basis allows for defining different policies for building the project vs. running tools. For example, you might want to use `Minor` as a roll forward policy for building the project, but `Major` for running tools.

### PR DESCRIPTION
**Pull request by Adityanr**
Add DOTNET_ROLL_FORWARD setting to DotNetCoreSettings
Closes #3065

### CODE REVIEW

**Comment by Adityanr** [comment]
hi, the status reports are stuck at waiting, but the rest of CI operations including integration tests have. Can you please tell me what i need to do to resolve this? @devlead

**Comment by devlead** [comment]
@Adityanr yes for new contributors GitHub will require maintainers to manually trigger builds. I'll rebase this PR now and that'll trigger all builds.

**Comment by Adityanr** [comment]
> @Adityanr yes for new contributors GitHub will require maintainers to manually trigger builds. I'll rebase this PR now and that'll trigger all builds.

Just noticed that..thanks for the update!

**Review by devlead — APPROVED** [review]
LGTM 👍 

I've rebased and added unit tests.

**Review by augustoproiete — APPROVED** [review]

**Comment by Adityanr** [comment]
sure, this is my twitter account: @AdityaN52843597, @augustoproiete

**Pull request merged**
