### PR TITLE
GH685: Adds support for SHA-256 code signing and timestamps in Sign…

### PR DESCRIPTION
**Pull request by mholo65**
Solves #685 

I'd like to take this for a spin (on monday) prior to merging.

ping @devlead

### CODE REVIEW

**Comment by gep13** [comment]
@mholo65 were you able to take this for a spin?

**Comment by mholo65** [comment]
Will do it now!

**Comment by mholo65** [comment]
@gep13 tested, and works like a charm! Any chance to get this into 0.17.0?

**Comment by gep13** [comment]
>@mholo65 said...
Any chance to get this into 0.17.0?

If you can rebase this onto the latest develop, then happy to merge this in (assuming CI passes).

**Comment by gep13** [comment]
@mholo65 in fact, I can do it, rather than being lazy 😄

**Comment by thomaslevesque** [comment]
This also fixes #906 

Thanks @mholo65!

**Comment by mholo65** [comment]
@thomaslevesque np. Attempted the ArgumentCustomization, and came to the conclusion that it was an ugly workaround. Therefore I took a stab at this issue.

**Pull request merged**
