### PR TITLE
(GH-569) Adding initial step for HomeBrew

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
As discussed in Gitter, let's start taking baby steps to getting a full build pipeline up and running, including creating the HomeBrew package.

Thoughts?

**Comment by patriksvensson** [comment]
Agree :)

**Comment by patriksvensson** [comment]
The `Publish-Homebrew` task should be dependent on the `Zip-Files` task.

**Comment by gep13** [comment]
>@patriksvensson said...
The Publish-Homebrew task should be dependent on the Zip-Files task.

Good point!

Updated:

image

**Comment by patriksvensson** [comment]
@gep13 Looks good to me! :+1:

**Comment by gep13** [comment]
**NOTE:** This PR doesn't close out GH-569, it is just a small step towards getting it implemented.

**Pull request merged**
