### PR TITLE
GH1995: Make In-Proc NuGet addin/tool installtion default

### LINKED ISSUE #1995: Make In-proc NuGet addin/tool installation default
Make In-proc NuGet addin/tool installation opt-out instead of opt-in.

### PR DESCRIPTION
**Pull request by devlead**
Makes new NuGet handling opt-out instead of opt-in, fixes #1995

### CODE REVIEW

**Comment by devlead** [comment]
@mholo65 rebased against latest develop.

**Comment by mholo65** [comment]
@devlead, great! Could you also send PR to website as default value have changed?

**Comment by gep13** [comment]
This would also be a PR to the resources repository as well then.

**Comment by devlead** [comment]
@mholo65 @gep13 sure, would be WIP until Cake released though.

**Comment by gep13** [comment]
https://github.com/cake-build/resources/pull/51

**Comment by gep13** [comment]
https://github.com/cake-build/website/issues/475

**Comment by gep13** [comment]
https://github.com/cake-build/website/pull/477

**Pull request merged**
