### PR TITLE
Add invariant IFormatterProvider to avoid issues based on user locale

### PR DESCRIPTION
**Pull request by devlead**
Code analytics raised CA1305, this PR fixes the potential user locale issue by:
1. Adds CultureInfo.InvariantCulture for locale insensitive "ToString"
2. string.Format handles null so removed that assignment

### CODE REVIEW

**Comment by gep13** [comment]
@devlead is there a reason to have the string Format broken out into a seperate const?

If not, if we are in this file making changes anyway, why not combine it into a single line?

**Comment by devlead** [comment]
@gep13 nothing more than readability I guess, tried to change as little as possible in the existing code.

**Comment by patriksvensson** [comment]
@gep13 Yeah, it's for readability. Don't like too long lines and it's a const so the compiler will merge it :smile:

**Comment by gep13** [comment]
@patriksvensson @devlead gotcha.  no worries, just thought I would ask.  Having to mind switch between two ways of doing things, as another project, who shall rename nameless, works slightly differently :smile:

**Comment by patriksvensson** [comment]
Looks good to me. Rebase against develop and I'll merge it :+1:

**Comment by devlead** [comment]
@patriksvensson Rebased.

**Pull request merged**
