### PR TITLE
[HOLD] GH1053: Adds ability to download scripts as nuget packages

### PR DESCRIPTION
**Pull request by robgha01**
Conversations from the first pull request can be found here https://github.com/cake-build/cake/pull/1070

### CODE REVIEW

**Comment by gep13** [comment]
@robgha01 good work on getting the feature branch created.

The errors that you are seeing are with regard to the Unit Tests that are executed on each build of the project.  Looks like the changes that you have made have broken some of those Unit Tests.  These would need to be corrected.

**Comment by gep13** [comment]
Relates to #1053

**Comment by robgha01** [comment]
@gep13 i will see what i can. :)

**Comment by robgha01** [comment]
@gep13 the result in ScriptRunner.cs line **125** when i debug the test this returns null and it wont go into the method that i created `Analyze(scriptPath.GetFilename(), out scriptAnalyzerContext)`
do i have to implament that method in the test somewere ?

**Comment by robgha01** [comment]
@gep13 nvm i found it :)

**Comment by robgha01** [comment]
@gep13 **Should_Throw_If_Path_Contains_Illegal_Characters()** in **PathTest.cs** line **92**
throws error saying it contains illigal characters i have not modified anyting in path io in the core what i can remember how do i fix this unit test ? do i need to update someting from the dev brance to the fethure brance ?

**Comment by robgha01** [comment]
@gep13 nvm, i downloaded a clone of dev and it seams it throws even there so its not my code anyway i fixed the other tests that failed related the my code :)

So what do i do know i guess i should ignore the other failures of the test that throws even in the main dev brance as its not related to this feture ?

**Comment by robgha01** [comment]
Im going to play around a bit with modularity of the processor and script runner etc.

**Comment by robgha01** [comment]
I have modified some things to make it possible for modulared processors i have added ProcessorValues it handles the actuall data for a processor ex: insteed of doing
`IList<PackageReference> Tools` in ScriptInformation.cs one can use the new
`ProcessorValues ProcessorValues` object to store its value it has one add method that looks like this:
`Add(ILineProcessor key, object value)` meaning if i create a processor i only have to do this
```
public sealed class LoadRemoteProcessor : UriDirectiveProcessor
    {
        private readonly ICakeComponentFactory _componentFactory;

        public LoadRemoteProcessor(ICakeEnvironment environment) : base(environment)
        {
            _componentFactory = new CakeComponentFactory();
        }

        protected override string GetDirectiveName()
        {
            return Constants.DirectiveName;
        }

        protected override void AddToContext(IScriptAnalyzerContext context, Uri uri)
        {
            var package = _componentFactory.CreatePackageReference(uri);
            **context.Script.ProcessorValues.Add(this, package);**
        }
    }
```

and it will save the value im not complitly done yet but later on this object will be used to resolve the actuall objects that a processor needs to process so for example the method in ScriptRunner.cs
`_processor.InstallTools(result, toolsPath);` can take its values from the ProcessorValues insteed, the tools is a core thing i took it as a example what i want to say is this opens up for external processors and script runner installers to work outside of the core but it will work with the core. open the world for extensions xD

**Comment by gep13** [comment]
@robgha01 as you will see from the below, all our CI servers are currently failing.  Before being able to look at this properly, we would need to have all of those builds passing.  Does this build correctly for you locally in Visual Studio, in both Debug/Release Configuration?

**Comment by robgha01** [comment]
@gep13 yes thay build with no errors in both debug and release.

**Comment by robgha01** [comment]
@gep13 im going through the unit tests that fails will update shortly.

**Comment by robgha01** [comment]
@gep13  I fixed the unit tests related the the PR the other thors in the main dev brance here is the debug files i use for tests https://1drv.ms/u/s!AvOXr9f-QF0pwGl_A-7MsCvFonEo

**Comment by robgha01** [comment]
@gep13 im done with the code but im going to build some modularity for PackageType its a enum but its only viable in the core and now im using NugetScript as a value im going to add a new method that takes in a fileExtension this way processor modules that want to use the installer can pass in a file extension insteed of a PackageType.

**Comment by robgha01** [comment]
@gep13 ok that is done, with this change i can move the dependency code on enum value PackageType nuget script to my written module insteed of the enum i route the logic through a string called fileExtension now i can finaly use json.net for the config file :dancers: 

I think everyting is now moved out of the core cake and the modularity sould be finished if you do howerver find anyting that need modularity just give me a shot and il look into it it dose not have to be related to this PR :) i love to refactor and make code esey and better.

**Comment by robgha01** [comment]
Cake.LoadRemote.Module is moved to my github repo here https://github.com/robgha01/Cake.Modules

**Comment by robgha01** [comment]
When this is introduced it would be nice for an additional section in cakebuild.net that lists all modules :)

**Comment by gep13** [comment]
@robgha01 yes, I had had the same thought. Haven't discussed that with the rest of the team yet though.

**Comment by robgha01** [comment]
@gep13 ok :)

**Comment by robgha01** [comment]
@gep13 Hey, i'm just checking in for some status on what is going on have anyone had time to look at this yet ?

**Comment by gep13** [comment]
@robgha01 we haven't forgotten about it.  The @cake-build/team are all busy with the port of Cake to the CoreClr, which is a reasonably large undertaking, and as a result we are not prioritizing larger Pull Requests just now, as mentioned here: http://cakebuild.net/blog/2016/07/cake-v0-15-0-released

**Comment by robgha01** [comment]
@gep13 ok, thancks for the fast status report :)

**Comment by robgha01** [comment]
Hey @gep13 how is it going and what is the status on this pull ?

**Comment by Sam13** [comment]
I'm very interested in this feature, would be glad if going to be merged and released soon... Thanks

**Comment by Sam13** [comment]
I'm not 100% sure what I'm doing but it seems to work with Cake 0.17.0
By using those two lines you can load Cake scripts from a NuGet package.

```
#tool nuget:?package=SomeId.BuildScripts.Cake&include=*.cake
#load "tools\SomeId.BuildScripts.Cake\SomethingInThePackage.cake"
```

The ugly thing is you have to replicate the tools path but as a workaround it might be ok...

**Comment by Sam13** [comment]
When the line preprocessor would come after the tool processor (`Cake.Core.Scripting.Analysis.ScriptAnalyzer`) it would be possible to have such a workaround:
```
#tool nuget:?package=SomeId.BuildScripts.Cake&include=*.cake
#load tools\SomeId.BuildScripts.Cake\Defaults.cake
```
But unfortunately this is not...

Does anybody know any other workaround which works with Cake 0.17?

**Comment by devlead** [comment]
@Sam13 currently there's no good work around, you could have an tools.cake with all tools that you execute before build.cake, or add your script nuget package to package.config.

**Comment by gep13** [comment]
@robgha01 sorry for taking so long to get back to you about this.  Put simply, other items were on my todo list, with a higher priority.

I have now had time to sit down again and look at this PR, and as I mentioned during the creation of this PR, I was considered that too many parts of the internals of Cake were changing, and as a result, there was a chance that this PR would not be pulled it.  Unfortunately, this is the case with this PR 😢 

Myself and @patriksvensson sat down this morning, and spiked out a solution to what is requested in #1053 which doesn't impact on as any areas of the system, and a PR will be coming soon in order to review it.  The PR will contain the bare minimum of functionality, mainly:

* To allow the referencing of a nuget package in the load pre-processor directive, similar to `#load nuget:?package=Cake.Recipe`
* When this is used, Cake will find that NuGet package, extract it to the tools folder, and then load all .cake files into the current script

If this doesn't cover all your use cases, the changes that will be made to the load pre-processor also mean that you can extend far more easily using a Module than was possible before, so you will have the option to use your own implementation as well.

I hope you understand why this decision was made, and we really appreciate the effort that was put into this PR, which if nothing else, started the conversation on this topic, and allowed us to include this functionality.  This functionality should be available in the 0.18.0 release of Cake.

**Comment by robgha01** [comment]
@gep13 that is strange, the required parts was extended processor and the extended script runner the factory part and some other things are irelevant im sorry that you could not consider fixing the code to youre standards and my time is wasted totally, i created this https://github.com/robgha01/Cake.LoadRemote.Module wich now is worhtless all my time and efforts trached now i know that you people dont care for stuff that you dont need to use. Thancks for nothing. im going to keep on using my own version untill i can find a new build system that suites my needs.

**Comment by robgha01** [comment]
I also see no problem with those changes in the core but i guess you folks dont care opening up 2 3 parts in the core or even building a adaptor around it to solve the issue...

**Comment by robgha01** [comment]
I need to go somewere and destress, im using anti-depresive medecine and right now i can say its not good.

**Comment by gep13** [comment]
@robgha01 I am sorry that your time has been wasted, but I distinctly remember saying during this process (perhaps in a Gitter conversation) that there was a chance that your work would not be pulled in.  This PR is dealing with some fundamental portions of the internals of Cake, and as a result, we wanted to make sure that it was done in a way that would not impact on other parts of the system.

While we were working on the spike, myself and @patriksvensson, decided that the best course of action was to start from scratch, rather than adapt this PR, as it is quite old of date compared to the latest develop branch (**NOTE:** this is our fault, as it took us a long time to get back to reviewing this), and also, we wanted to take a slightly different approach to what was suggested in this PR.

>@robgha01 said...
wich now is worhtless all my time and efforts trached now i know that you people dont care for stuff that you dont need to use.

This is quite simply not true.  We care deeply about all of our Community Members, and we take great pains to try to not upset anyone.  In this instance, we felt that this was the best option all around.  While I understand your annoyance at your Module no longer working, based on our understanding, your use case is now handled directly within Cake, and a Module is no longer required.  If this is not the case, and your use case is not met, then the extension points that have been added into Cake now make it much easier to extend to include them.

>@robgha01 said...
Thancks for nothing. im going to keep on using my own version untill i can find a new build system that suites my needs.

I am truly sorry to hear that.  I really hope you will be able to take advantage of the new functionality that is being added to Cake in this next release, and continue to be a valued member of the community.

**Comment by robgha01** [comment]
@gep13 yea we will see, im a bit unstable as you have noticed my life is not in order well more clearly i cant controll my fealings... So the next version may not use the same kind of solution but it should produce the same result if im not mistaken ?

**Comment by gep13** [comment]
@robgha01 that is correct.

You should be able to do:

`#load nuget:?package=Cake.Recipe`

(As an example)

And it will download the nuget package from NuGet.org, extract it to the tools folder, and load load each of the .cake files that were contained within it.`

**Comment by robgha01** [comment]
@gep13 Hi, its been some time have had a nice vacation sort of xD but now i got some time to upgrade my implementation "the old feature request" to this one and test that it all works nicely.

I managed to upgrade with the latest bootstrapper the none deprecated one :)
when i run the build it seams to find the .cake script that i use "#load" with but it what is not working is this:

I have some addings included in the nuget package they are not getting included in the #load process ?
else everything else seams to work so far 👍

**Comment by gep13** [comment]
@robgha01 glad to have you back!

I have been using this new functionality extensively when using Cake.Recipe, and it is happily working across almost 50 seperate repositories.

**Pull request closed without merging**
