### PR TITLE
(GH-693) Added Jenkins CI build system support

### PR DESCRIPTION
**Pull request by RLittlesII**
Added support for the following environment variables:
- BUILD_NUMBER
- BUILD_ID
- BUILD_DISPLAY_NAME
- BUILD_URL
- BUILD_TAG
- EXECUTOR_NUMBER
- NODE_NAME
- NODE_LABELS
- WORKSPACE
- JENKINS_HOME
- JENKINS_URL
- JOB_NAME
- JOB_URL
- SVN_REVISION
- SVN_URL
- GIT_COMMIT
- GIT_BRANCH
- CVS_BRANCH

### CODE REVIEW

**Comment by patriksvensson** [comment]
@RLittlesII Forgot to follow up on this. Sorry about that.

Do you feel ready with this PR? Should we review it?

**Comment by RLittlesII** [comment]
@patriksvensson I believe it's ready for review.

**Comment by patriksvensson** [comment]
Ok, on my way to go to sleep now, but I'll mark it as ready and I (or someone in the @cake-build/team) will take a look at it tomorrow.

**Comment by patriksvensson** [comment]
@RLittlesII Sorry for taking so long to get back to you. I've set up a Jenkins server now :smile: Would you mind rebasing this against develop and I'll run it there and then merge this PR :smile:

**Comment by RLittlesII** [comment]
Rebase complete.  No worries.

**Comment by devlead** [comment]
@RLittlesII Am I missing something or isn't `JenkinsNodeInfo` instantiated anywhere? Should likely be a readonly property on the `JenkinsEnvironmentInfo`.

**Comment by devlead** [comment]
@RLittlesII also `JenkinsJobInfo` seem to be missing.

**Comment by devlead** [comment]
@RLittlesII LGTM besides the missing properties :+1:  , let me now when you adjusted and rebased, after that I'll review again and merge if ok.

**Comment by RLittlesII** [comment]
Embarrassing.  I have made the changes and added JobInfo and NodeInfo to the EnvironmentInfo as properties.  Rebased.

**Comment by devlead** [comment]
@RLittlesII Thanks for your contribution :+1: This is now merged.

**Pull request merged**
