### PR TITLE
GH1686: Made root path absolute for the AssemblyLoadContext.

### LINKED ISSUE #1686: AssemblyLoadContext root path is relative
When creating the `AssemblyLoadContext`, we should use the absolute path for the directory and not the relative one.

https://github.com/phenixdotnet/cake/blob/d0428c49aea85415eb8d3f5d27e0ce0434039762/src/Cake.Core/Polyfill/AssemblyHelper.cs#L38

The initial bug fix (#1680) that we merged will only solve the cases where the loaded assembly doesn't have any dependencies on it's own. If it has and if they're in the same directory, they will fail loading.

### PR DESCRIPTION
**Pull request by patriksvensson**
Fixes #1686

### CODE REVIEW

**Comment by patriksvensson** [comment]
@phenixdotnet Can you test this PR out to make sure that it still works for you? Thanks!

**Comment by gep13** [comment]
@patriksvensson I have re-targetted this PR at a new `hotfix/0.21.1` branch.

**Comment by devlead** [comment]
@gep13 do we need a new branch as nothing has been merged yet?

**Comment by gep13** [comment]
@devlead yes, otherwise we are stopped from pulling any features into the develop branch.  For example, the PR that @pascalberger has for Chocolatey download, that I was going to look at later.

**Comment by gep13** [comment]
Plus, it is the gitflow process 😄

**Comment by devlead** [comment]
@gep13 ok! Then all PRs need to be rebased too. I'll do that with mine.

**Comment by gep13** [comment]
@devlead I have done it for both PR's 😄

**Comment by devlead** [comment]
@gep13 this still has 3 commits from develop though, whereas #1688 i rebased only has 1 commit ;)

**Pull request merged**
