### PR TITLE
#3283 - Update GitVersion alias reference page with dotnet tool usage example

### LINKED ISSUE #3283: Update GitVersion alias reference page with dotnet tool usage example
The example in the documentation ( https://cakebuild.net/api/Cake.Common.Tools.GitVersion/GitVersionAliases/ ) uses `GitVersion.CommandLine` which is a Windows-only tool.

`GitVersion.Tool` is a cross-platform .NET tool that can be consumed via the `dotnet` scheme in Cake >= 1.1

```
#tool "dotnet:?package=GitVersion.Tool&version=5.6.6"
```

### PR DESCRIPTION
**Pull request by arturcic**
Closes #3283

### CODE REVIEW

**Review by augustoproiete — CHANGES_REQUESTED** [review]
@arturcic LGTM, but needs rebase/squash... Lots of `develop` merges in the PR branch

**Comment by arturcic** [comment]
@augustoproiete I rebased

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by augustoproiete** [comment]
@arturcic your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
