### PR TITLE
GH3216: Remap NuGetLogger Verbose/Verbose to ICakeLog Debug/Diagnostic

### LINKED ISSUE #3216: Remap NuGetLogger Verbose/Verbose to ICakeLog Debug/Diagnostic
The [NuGetLogger](https://github.com/cake-build/cake/blob/b40794faaa7e2ce20248cf83906ff6a60f7391f0/src/Cake.NuGet/Client/NuGetLogger.cs#L13) remapping is inconsistent and too noisy. It's inconsistent because Information/Normal (LogLevel/Verbosity) remaps to Debug/Normal, but Verbose/Verbose still maps to Verbose/Verbose, so it leaks through _before_ Information/Normal logging, as shown in [Cake.Dungeon/runs/1999760693](https://github.com/gitfool/Cake.Dungeon/runs/1999760693#step:5:15) when using `dotnet cake --verbosity=verbose`:
```log
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
PackageSignatureVerificationLog: PackageIdentity: Cake.Docker.1.0.0 Source: /home/runner/work/Cake.Dungeon/Cake.Dungeon/.nuget/packages PackageSignatureValidity: True
Acquiring lock for the installation of Cake.FileHelpers 4.0.0
Acquired lock for the installation of Cake.FileHelpers 4.0.0
Completed installation of Cake.FileHelpers 4.0.0
PackageSignatureVerificationLog: PackageIdentity: Cake.FileHelpers.4.0.0 Source:  PackageSignatureValidity: True
Acquiring lock for the installation of Cake.Incubator 6.0.0
Acquired lock for the installation of Cake.Incubator 6.0.0
Completed installation of Cake.Incubator 6.0.0
PackageSignatureVerificationLog: PackageIdentity: Cake.Incubator.6.0.0 Source:  PackageSignatureValidity: True
Compiling build script...
```
Such logging is not normally useful anyway, so is just noise that should be remapped to Debug/Diagnostic, which is still accessible when using `dotnet cake --verbosity=diagnostic` and makes the log remapping consistent and less noisy.

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #3216.

### CODE REVIEW

**Comment by gitfool** [comment]
Unrelated build failure on `ubuntu-latest` which looks to be because "latest" has finally switched to Ubuntu 20.04!

This is good news _but_ need to be using the latest `GitVersion` for it to be compatible.

**Comment by gitfool** [comment]
And of course Bitrise [still fails](https://github.com/cake-build/cake/pull/2921#issuecomment-717768144) with the latest GitVersion. 😞

**Comment by gitfool** [comment]
I see two options:
* Use `ubuntu-18.04` label to pin Ubuntu runner to 18.04
* Fix ongoing issue with Bitrise builds using latest GitVersion (pref)

Hopefully this doesn't hold up accepting this PR as I was hoping to squeeze it into Cake 1.1.0. 😛

**Comment by augustoproiete** [comment]
Thanks for looking into this @gitfool ! We're going to [pin Ubuntu to 18.04](https://github.com/cake-build/cake/pull/3229) for now so we can unblock merging PRs, and revisit after we can make Bitrise work with the latest GitVersion.

We'd like to merge this PR today, so I'll remove your [latest commit that updates GitVersion](https://github.com/cake-build/cake/pull/3217/commits/699983dbe4aec75562f0f606a1d097a86fed3d2e) and rebase on top of `develop` once #3229 has been merged

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by augustoproiete** [comment]
@gitfool your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
