### PR TITLE
GH1280: Added Go.CD build provider

### PR DESCRIPTION
**Pull request by RehanSaeed**
Added support for Go.CD. See documentation here: https://docs.go.cd/current/faq/environment_variables.html

### CODE REVIEW

**Comment by gep13** [comment]
@RehanSaeed in line with our contributing process (https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md) can you please create an issue, and link to this PR from it?

Also, would it be possible for you to rebase your changes on top of the latest develop branch? Thanks!

**Comment by RehanSaeed** [comment]
Done.

**Comment by gep13** [comment]
Relates to #1280

**Comment by patriksvensson** [comment]
@RehanSaeed LGTM!
Could you squash your commits to a single one and rebase against the develop branch?

Thanks!

**Comment by RehanSaeed** [comment]
Done

**Comment by devlead** [comment]
Thanks @RehanSaeed, your changes have not been merged and will be available in the next release. Thanks for your contribution 👍

**Pull request merged**
