### PR TITLE
GH943: Correcting AssemblyInfo Parsing

### PR DESCRIPTION
**Pull request by gep13**
Relates to #943

### CODE REVIEW

**Comment by gep13** [comment]
@cake-build/team can I get your thoughts on this?

I am trying to add a couple tests to validate the contents of the AssemblyInfo file, but the tests are failing as the file I am trying to create isn't getting created.  Ideas?

**Comment by gep13** [comment]
@cake-build/team ok, stand down :smile: 

I have figured it out.  Now just a quick opinion on what I have cobbled together would be good. Thanks!

**Comment by devlead** [comment]
@gep13 LGTM :+1: , could you rebase against latest develop?

**Comment by gep13** [comment]
@devlead rebased as requested.

**Comment by devlead** [comment]
@gep13 thanks! Merged 👍

**Pull request merged**
