### PR TITLE
GH2894: Remove unnecessary documentation and replace it with <inheritdoc />

### PR DESCRIPTION
**Pull request by Marusyk**
Remove unnecessary documentation and replace it with `<inheritdoc />`

Issue #2894

Projects:
- [x] Cake
- [x] Cake.Core
- [x] Cake.Common
- [x] Cake.Frosting
- [x] Cake.NuGet
- [x] Cake.Testing
- [x] Cake.Testing.Xunit

Please review
Thank you in advance

### CODE REVIEW

**Comment by Marusyk** [comment]
Can anyone help with failed builds?

**Comment by devlead** [comment]
> Can anyone help with failed builds?

`src/Cake.Common/Build/TFBuild/TFBuildProvider.cs` had an inheritdoc on a private member and there was a merge conflict in `src/Cake.Core/IO/Globber.cs`.

I've sorted, rebased, and forced pushed to your branch, let see if that makes CI happier.

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by devlead** [comment]
@Marusyk your changes have been merged, thanks for your contribution 👍

**Pull request merged**
