### PR TITLE
GH1172: Adding GetStandardError to IProcess and RedirectStandardError to ProcessSettings

### PR DESCRIPTION
**Pull request by CaptainCow95**
Adds the ability to redirect the standard error in the same way that you can currently redirect standard output. Related to #1172

### CODE REVIEW

**Comment by devlead** [comment]
@CaptainCow95 Hi are you in a position to rebase this against latest develop?

**Comment by CaptainCow95** [comment]
I'll try to get to it tonight.

**Comment by CaptainCow95** [comment]
Should be all synced up now.

**Comment by devlead** [comment]
@CaptainCow95 this is now merged and will be avail in next release, thanks for contributing 👍

**Pull request merged**
