### PR TITLE
Reformat report

### PR DESCRIPTION
**Pull request by marcosnz**
Right-align task name to make it easier to associate name with time
Reduce number of leading zeros displayed
Reduce number of milliseconds displayed
so this:
```
Task                          Duration
--------------------------------------------------
Clean                         00:00:00.0317691
Restore-NuGet-Packages        00:00:00.2629602
Patch-Assembly-Info           00:00:00.0186530
Build                         00:00:04.6035797
Run-Unit-Tests                00:00:29.3326800
Copy-Files                    00:00:00.0928802
Zip-Files                     00:00:00.4412042
Create-NuGet-Packages         00:00:02.5186547
Package                       00:00:00.0092035
Default                       00:00:00.0086326
--------------------------------------------------
Total:                        00:00:37.3202172
```
becomes:
```
                  Task Duration
-------------------------------
                 Clean     0.03
Restore-NuGet-Packages     0.25
   Patch-Assembly-Info     0.01
                 Build     4.08
        Run-Unit-Tests    27.87
            Copy-Files     0.07
             Zip-Files     0.39
 Create-NuGet-Packages     1.43
               Package     0.00
               Default     0.00
-------------------------------
                Total:    34.19
```
Will handle tasks that take a long time:
```
                  Task    Duration
----------------------------------
                 Clean        0.03
Restore-NuGet-Packages        0.25
   Patch-Assembly-Info        0.01
                 Build        4.08
        Run-Unit-Tests  9:21:27.87
            Copy-Files  1:00:00.07
             Zip-Files        0.39
 Create-NuGet-Packages        1.43
               Package        0.00
               Default        0.00
----------------------------------
                Total: 10:21:34.19
```

### CODE REVIEW

**Comment by patriksvensson** [comment]
Hello @marcosnz!

Thanks for this PR, but I'm not sure that we want the report right aligned. 
I can only talk for myself, but I prefer the report to be left aligned.

Maybe we could add a custom override for reports (just like `Setup/Teardown`) to 
be able to choose how the report should be written to the console?

```csharp
FormatReport(report => {
    // Formatting logic
});
```

**Comment by devlead** [comment]
I like the custom report idea @patriksvensson , could allow reporting summary to file/ slack/ etc. 👍

**Comment by marcosnz** [comment]
>I can only talk for myself, but I prefer the report to be left aligned.

Yeah, fair enough :smile:. I am doing some auto-built task names that end up being quite long and the shorter ones end up being a long way from the time so this worked for me.
>Maybe we could add a custom override for reports

Hmm yes, that would work. TBH it's not a big deal, it has just kind of annoyed me since my last PR I did in this area. If I have time I'll look at doing the override but really there are bigger fish to fry (although I said that before starting *this* PR :smile: )

**Comment by devlead** [comment]
@marcosnz a bit late feedback here, but we're closing this for now and you can reopen when you have the time for the suggested adjustments.

**Pull request closed without merging**
