### PR TITLE
Changes nuget version bootstrapper downloads

### PR DESCRIPTION
**Pull request by devlead**
This is a suggested fix for #733

### CODE REVIEW

**Comment by daveaglick** [comment]
:+1: I did this manually in my own bootstrapper scripts, but it'll be good to get the change in the official ones.

**Comment by RichiCoder1** [comment]
Hmm. It might be ideal to lock it to a specific version rather than pulling latest, just in case.

**Comment by gep13** [comment]
@devlead what are your thoughts on @RichiCoder1 comment above?

**Comment by devlead** [comment]
Personally I prefer latest stable, it's potentially less maintenance but also with potentially greater risk. I'm fine with either, regardless we would need to test & keep up with new versions.

**Comment by gep13** [comment]
>@devlead said...
regardless we would need to test & keep up with new versions.

Yes, I agree with that.  And at least pulling in the latest will make us proactive at fixes any issues with our own build.

@patriksvensson what are your thoughts?  If you are in agreement, I am happy to merge this in.

**Comment by patriksvensson** [comment]
@gep13 I understand the reservations but this is fine by me. Easy to change if it wouldn't work for some reason.

**Comment by gep13** [comment]
:+1:

**Comment by daveaglick** [comment]
:+1:

**Pull request merged**
