### PR TITLE
GH897: Adds support for DevelopmentDependency to NuGetPackSettings

### LINKED ISSUE #897: Add DevelopmentDependency to NuGetPackSettings
Related to #895, add a flag for `DevelopmentDependency` to `NuGetPackSettings` and use it when creating the temporary .nuspec for the pack alias. I'll submit a PR for this shortly, but figured I should create a separate issue to track it.

### PR DESCRIPTION
**Pull request by daveaglick**
This resolves #897

### CODE REVIEW

**Comment by daveaglick** [comment]
On AppVeyor is looks like this failed during the build of `Cake.NuGet.Tests`. That wasn't a library I changed, and if it had something to do with code I did change I would have expected a failure during test, not build. If it was just AppVeyor I would suspect it was a fluke, but TeamCity also failed. Any idea what went wrong?

**Comment by patriksvensson** [comment]
@daveaglick Restarted the CI build.

**Comment by patriksvensson** [comment]
@daveaglick The `Cake.NuGet.Tests` project is just the last project being built. The real reason is a StyleCop error in the `NuGetPackSettings`.

```
NuGetPackSettings.cs(136,1): error : SA1623 : CSharp.Documentation : The property's 
documentation summary text must begin with: Gets or sets a value indicating whether
```

**Comment by daveaglick** [comment]
@patriksvensson Ah, totally missed that, thanks. Updated.

**Comment by devlead** [comment]
@daveaglick LGTM, could you please rebase against latest develop, Ping us when done and we'll do a final review.

**Comment by daveaglick** [comment]
@devlead Done!

**Comment by devlead** [comment]
@daveaglick LGTM :+1: Merged! Thanks for your contribution.

**Pull request merged**
