### PR TITLE
(build) Update GitVersion to 5.1.2

### PR DESCRIPTION
**Pull request by devlead**

### CODE REVIEW

**Comment by gep13** [comment]
@devlead does this bump address the issue that you mentioned previously regarding the asserted version numbers?

**Comment by devlead** [comment]
@gep13 doesn't seem so, I'll investigate some more.

**Comment by devlead** [comment]
Maybe related to this GitTools/GitVersion#1927

**Comment by devlead** [comment]
Ideally PR branches shouldn't fail the build, would be nice if it generated same as on AppVeyor `0.36.0-PullRequest2689...` instead of `0.36.0-gitversion-5-1-2...`

**Comment by gep13** [comment]
Agreed.

**Pull request merged**
