### PR TITLE
GH930: Allow XmlPeek and XmlPoke in XML files with DOCTYPE

### PR DESCRIPTION
**Pull request by fabionuno**
Added the DtdProcessing property to XmlPeekSettings and XmlPokeSettings class.
This property is used to instanciate a XmlReaderSettings used by XmlReader.Create to determine the processing of DTDs.

Relates to #930

### CODE REVIEW

**Comment by devlead** [comment]
@fabionuno PR got some style cop errors
```
C:\projects\cake\src\Cake.Common\Xml\XmlPeekAliases.cs(137,1): error : SA1507 : CSharp.Layout : The code must not contain multiple blank lines in a row. 
```
you should be able to see them locally if you do a rebuild in release mode in Visual Studio or by checking the AppVeyor build log.

**Comment by fabionuno** [comment]
Sorry, I made this changes using vscode. 
Multiple blank lines was removed.

**Comment by devlead** [comment]
@fabionuno LGTM :+1:, could you rebase & squash into 1 commit and ping us when done and we'll do a final review before merging.

**Comment by fabionuno** [comment]
@devlead  Done.

**Comment by devlead** [comment]
@fabionuno LGTM :+1: merged, thanks for contributing!

**Pull request merged**
