### PR TITLE
Corrected Class Name Associated with Unit Test

### PR DESCRIPTION
**Pull request by daveaglick**
OCD: TheGetExtensionProperty test -> TheGetExtensionMethod test

### CODE REVIEW

**Comment by gep13** [comment]
@daveaglick ha ha, well spotted!

**Comment by gep13** [comment]
@daveaglick I have no issues with pulling this in, just one quick suggestion...

Can you change the commit message to provide some further information about what changed, and why?  That way, when we are looking back at the history, we know what was done.

For instance, I would suggest something like this:

`(maint) Changed class name

- To clearly indicate the situation under test
- The previous class name suggested it was the GetExtensionProperty, but it was GetExtensionMethod`

What do you think?

**Comment by daveaglick** [comment]
:thumbsup: No problem - hopefully the new message is good.

**Comment by gep13** [comment]
@daveaglick thank you for your contribution! :+1:

**Comment by daveaglick** [comment]
Lol - I gotta tell you, this one was really tough :smile:

**Comment by gep13** [comment]
Ha ha, everything counts :smile_cat:

**Pull request merged**
