### PR TITLE
GH3352: Add DirectoryPath + ConvertableDirectoryPath operator to ConvertableDirectoryPath

### LINKED ISSUE #3352: Cake Frosting Parent DirectoryPath Fails To Combine with Slash
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake Frosting

### Cake version

1.1.0

### Operating system

Linux, Windows

### Operating system architecture

64-Bit

### CI Server

_No response_

### What are you seeing?

A NullReferenceException in the code sample below.  However, that's more the symptom than the cause.  The problem appears to be that Cake Frosting is combining `Directory("..") + Directory("temp")` into `"..temp"` rather than `"../temp"` when you capture the context and then use expression bodied properties.  

This may seem obscure, but I'm converting a large codebase of DSL Cake into Frosting and am looking for ways to accomplish it with minimal changes.

### What is expected?

It should run to completion without an exception

### Steps to Reproduce

Run this:

``` csharp
[TaskName("Fail")]
public class FailTask : FrostingTask<BuildContext>
{
    private BuildContext? _context;
    private DirectoryPath RootDir => _context.Directory("..");
    private DirectoryPath TestDir => RootDir + _context.Directory("temp");

    public override void Run(BuildContext context)
    {
        _context = context;
        context.GetFiles(TestDir + context.File("*.zip"));
    }
}
```

### Output log

```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Cake.Core.IO.Globbing.GlobVisitor.VisitParent(ParentDirectoryNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.Nodes.ParentDirectoryNode.Accept(GlobVisitor visitor, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitRelativeRoot(RelativeRootNode node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.Nodes.RelativeRootNode.Accept(GlobVisitor globber, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.Walk(GlobNode node, GlobberSettings settings)
   at Cake.Core.IO.Globber.Match(GlobPattern pattern, GlobberSettings settings)
   at Cake.Core.IO.GlobberExtensions.Match(IGlobber globber, GlobPattern pattern)
   at Cake.Common.IO.GlobbingAliases.GetFiles(ICakeContext context, GlobPattern pattern)
   ...
```

### PR DESCRIPTION
**Pull request by augustoproiete**
Closes #3352

### CODE REVIEW

**Review by nils-a — APPROVED** [review]
LGTM

**Review by devlead — CHANGES_REQUESTED** [review]
Could we add some [Directory](https://cakebuild.net/api/Cake.Common.IO/DirectoryAliases/7E77A941) tests to `tests/integration/Cake.Common/IO/DirectoryAliases.cake` to test this?

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by devlead** [comment]
@augustoproiete your changes have been merged, thanks for your contribution 👍

**Pull request merged**
