### PR TITLE
Added InspectCode Support (ReSharper Command Line Tools)

### PR DESCRIPTION
**Pull request by yvschmid**
reopen #335 after accidentally closing it.

### CODE REVIEW

**Comment by yvschmid** [comment]
fixed some bugs and added support for the config file

**Comment by patriksvensson** [comment]
Merged :+1:

**Comment by gep13** [comment]
@patriksvensson did these changes actually make it in?  It says this PR was closed, not merged.

**Comment by patriksvensson** [comment]
@gep13 Yes. I rebased the PR and this cause GitHub to not understand that it was merged.

**Comment by gep13** [comment]
Gotcha :+1:

**Pull request closed without merging**
