### PR TITLE
Fix Allow paths with spaces for OutputDirectory

### PR DESCRIPTION
**Pull request by RLittlesII**
This pull request fixes issue.   #1034

### CODE REVIEW

**Comment by gep13** [comment]
@RLittlesII hmm, I am a little confused by this PR, can you help me try to understand it?

The original issue mentions the OutputDirectory property, but seems like most of the changes you have made are with regard to the Project property?  Do you think it would be a good idea to add additional tests, or theories, where we actually include a path that contains spaces for both of these properties?

**Comment by gep13** [comment]
@RLittlesII also, if you have a chance, would you be in a position to sign our CLA?

**Comment by RLittlesII** [comment]
I checked the output directory. Then reading the issue a little closer the poster mentioned that it isn't the output directory that is the issue, he states it is the project.json file that he is passing in that has spaces in it.

**Comment by RLittlesII** [comment]
@gep13 The original poster mentioned it was the project.json he was passing in that was the problem.  I was confused by it as well by the name of the issue.  I can add some additional Theories or Tests to show a path with spaces.
Where do I go to sign the CLA?

**Comment by devlead** [comment]
@RLittlesII should come automatically but you can sign in manually here:
https://cla2.dotnetfoundation.org

/cc @martinwoodward

**Comment by gep13** [comment]
@RLittlesII looks to me like there is the potential for both the OutputDirectory and Project to contain a space, so I think both should handle this.  Could you update this PR to do both, and we can update the issue to reflect the work that it done.  I think they are related enough to do under one PR.

**Comment by RLittlesII** [comment]
@gep13 I'll take a look tonight, clean this up and get a rebased PR up.
@devlead Signed.  Waiting on email.  :smile:

**Comment by gep13** [comment]
>@RLittlesII said...
@gep13 I'll take a look tonight, clean this up and get a rebased PR up.

Perfect, thanks again for your contributions!

**Comment by RLittlesII** [comment]
@gep13 Added theories and rebased.

**Comment by gep13** [comment]
@RLittlesII LGTM! Thanks!

I have merged this here: https://github.com/cake-build/cake/commit/264936bc6c6ac5800201376834c8f36f22820987

GitHub won't follow the change, so this PR will need to be closed, but your commit is still valid. Thanks!

**Pull request closed without merging**
