### PR TITLE
GH2193: Added new maintainers

### PR DESCRIPTION
**Pull request by gep13**
Think I have got all the required places

### CODE REVIEW

**Comment by gep13** [comment]
Relates to #2193

**Comment by gep13** [comment]
@pascalberger if you are happy with this change, then you can feel free to merge it.  For a larger, code related change, we might need a couple of thumbs up, but for this, I think we are good to go.

**Comment by gep13** [comment]
The process that we follow for Cake is going to be similar to what you already follow for your other repos, but, main things would be:

* there is an associated issue created, and referenced in the PR
* issue is labelled and assigned to a milestone
* PR targets the develop branch (unless part of a hotfix)
* ideally PR only has one commit, unless compelling reason to separate them out
* Commit messages reference the issue using `(GH-xxx)` nomenclature
* CLA has been signed
* all CI checks pass
* PR comes from another branch on fork, i.e. not from develop branch

Let me know if you have any questions.

**Comment by daveaglick** [comment]
I've been stalling on my review because honestly, I was hoping to be listed as _CodeNinja McGooglyEyes_. I guess this will suffice though.

**Pull request merged**
