### PR TITLE
Fixes #1292 Roundhouse Improvements

### LINKED ISSUE #1292: Some properties for RoundhouseSettings in Cake.Common.Tools.Roundhouse are not working properly
Error: C:/Examples/Ecommerce/blanqueria/Ecommerce/build.cake(92,4): error CS0117
: 'Cake.Common.Tools.Roundhouse.RoundhouseSettings' does not contain a definitio
n for 'Drop'

I need to drop the database using this command:

RoundhouseMigrate(new RoundhouseSettings{
            ConnectionString = connectionString,
            SqlFilesDirectory = "Ecommerce\\Scripts",
	    Drop = false
        });

Cake version: 0.15.2
Windows 10 64Bits

### PR DESCRIPTION
**Pull request by phillipsj**
Made a change to the setttings file as discussed in the ticket.  Also added the missing switches that are not in the settings file.

### CODE REVIEW

**Comment by phillipsj** [comment]
Wierd, everything passed locally.  I will take a look and fix those errors.  I apologize for the errors.

**Comment by patriksvensson** [comment]
@phillipsj No need to apologize 😄 

Did you build it from Visual Studio or run the build script?
If you run from Visual Studio, you need to build the `Release` configuration for StyleCop to show any errors. When you run the build script you should see the same error as in the CI logs. If this is not the case, tell us and we will take a look at it. Not impossible StyleCop is playing tricks on us 😄

**Comment by phillipsj** [comment]
Argh, not my night.

**Comment by gep13** [comment]
@phillipsj out of curiousity, was there a reason for closing this PR?

**Comment by phillipsj** [comment]
@gep13 It was accidental, I am having one of those kind of weeks.

**Pull request closed without merging**
