### PR TITLE
Fix splitting PATH environment variable.

### PR DESCRIPTION
**Pull request by olivier-spinelli**
A friend of mine lost some time on this one: its PATH contained too much ;;...

### CODE REVIEW

**Comment by patriksvensson** [comment]
Looks good to me :+1:

**Comment by patriksvensson** [comment]
@olivier-spinelli Could you rebase this into a single commit and i'll merge it for you.

**Comment by olivier-spinelli** [comment]
@patriksvensson Done!

**Comment by patriksvensson** [comment]
Merged but have to close it manually since there was some problems with the commit message that I had to fix. Thanks for the contribution! :+1:

**Pull request closed without merging**
