### PR TITLE
GH724: Adds DotCover Report

### PR DESCRIPTION
**Pull request by mholo65**
Solves part of #724

Dependent on PR #1152

### CODE REVIEW

**Comment by gep13** [comment]
@mholo65 would you be in a position to update this PR?  I have just merged in #1152

**Comment by mholo65** [comment]
@gep13 sure thing, I'll look into it tomorrow

**Comment by mholo65** [comment]
@gep13 All done!

**Comment by gep13** [comment]
@mholo65 rebased and merged here: https://github.com/cake-build/cake/commit/bc4cd31514053f619d775b3abe254781566d4081

Thanks!

**Pull request closed without merging**
