### PR TITLE
AssemblyKeyFileAttribute

### PR DESCRIPTION
**Pull request by ckansiz**
AssemblyKeyFileAttribute property added into  AssemblyInfoSettings.cs for singing.

### CODE REVIEW

**Comment by gep13** [comment]
@ckansiz thank you for taking the time to submit a Pull Request to Cake.  Can I ask that you have a read through this please: https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md

There are a couple of things "missing" from this PR that will prove problematic in order to pull this in.  For example, you have made the changes directly on your forked develop branch, rather than on a feature branch.  Also, was there an issue created for this change?  What exactly is the change for, and why is it required?

Thanks again!

**Comment by ckansiz** [comment]
We want to sign dlls and need keyfile attribute for snk file.

**Comment by gep13** [comment]
>@ckansiz said....
We want to sign dlls and need keyfile attribute for snk file.

Yes, I understand.  However, we would prefer that an issue be opened in order to discuss this further, and also to allow that to flow through into our process for automatically creating release notes, etc.

**Comment by ckansiz** [comment]
Ok. I Understand.

**Pull request closed without merging**
