### PR TITLE
GH1988: Fix writing start and end progress messages

### PR DESCRIPTION
**Pull request by johannesegger**
According to the [docs](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-progressReportingReportingBuildProgress) there is no property "message" for "progressStart" and "progressFinish".

### CODE REVIEW

**Comment by gep13** [comment]
@agc93 can you comment on this?

**Comment by agc93** [comment]
Sorry for the delay @gep13 , this one snuck through Octobox without me noticing. I'll try and test this out, but yes looks like that property name shouldn't be there.

**Comment by gep13** [comment]
@agc93 did you have a chance to test this out?

**Comment by gep13** [comment]
@johannesegger did you create an issue to go with this PR? As per our contributing documentation, we prefer that this is the case.  Thanks for your help!

**Comment by johannesegger** [comment]
@gep13 I didn't create an issue because this was such a trivial bug that I didn't see a need to go through these formalities. If you don't want this PR without an issue, please feel free to close it. I had to work around this a long time ago and don't really need this to be merged in.

**Comment by devlead** [comment]
Relates to #1988

**Comment by devlead** [comment]
@johannesegger your changes have been merged, thanks for your contribution 👍

**Pull request merged**
