### PR TITLE
GH669: Added .gitattributes file

### PR DESCRIPTION
**Pull request by gep13**
Relates to #669

### CODE REVIEW

**Comment by gep13** [comment]
This was completed using what was suggested here:

https://github.com/GitTools/GitLink/pull/107

Specifically:

```
git clean -fdx :/
git rm --cached -r :/
git add :/ -A -f
git commit -m "Reconcile line endings"
```

**Comment by gep13** [comment]
The addition of this file is actually something that is suggested by .Net Foundation, and it was on our list of things to do after joining the foundation.

**Comment by devlead** [comment]
@gep13 this one seems to make things fail on POSIX, looks like execute bit was lost on src/build.sh, could please fix and get back when done.

**Comment by devlead** [comment]
@gep13 I'll fixup this one and will rebase/push as soon as I've merged another PR.

**Comment by devlead** [comment]
@gep13 your changes have been merged! Thanks for contributing 👍

**Comment by gep13** [comment]
@devlead it's possible that the work that was done in this PR will need to be re-done prior to completing the next release, as some of the files you merged in may not have been accounted for. Or, did you redo the above commands after rebasing the PR?

**Comment by devlead** [comment]
I just added a commit with execute bit on build.sh files and rebased against latest develop.

**Comment by gep13** [comment]
@devlead ok cool. This is a bit of a guess, but I think we should run the commands again when we are on the release branch, just to confirm. What command did you run to re-enable execution?

**Comment by devlead** [comment]
`git update-index --chmod=+x build.sh`

**Comment by gep13** [comment]
Thought it might have been that one. There might be something we can add to the gitattributes file to "protect" these files so they don't get changed.

**Pull request merged**
