### PR TITLE
setup useToolVersion override

### PR DESCRIPTION
**Pull request by narcopanda**
Added override for UseToolVersion method to take in a string param also added a helper method to map said string to the correct MSBuildToolVersion enum. It's a little big since I wasn't sure on what type of string we should expect. 
https://github.com/cake-build/cake/issues/3237

This is my first time contributing to a open source project so apologies for any mistakes with the process

### CODE REVIEW

**Comment by augustoproiete** [comment]
Want to give that a try? We already have a [UseToolsVersion](https://github.com/cake-build/cake/blob/v1.1.0/src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs#L39) that accepts an enum, so the main value proposition of this new overload would be to allow users to use an arbitrary string that Cake doesn't yet know about - assuming that can be used to locate the right MSBuild.

**Comment by narcopanda** [comment]
sure

**Comment by narcopanda** [comment]
I added to 2 new enums to MSBuildToolVersion one that is for a custom .net framework and another for a custom visual studio.
I also updated the MSBuildVersion enums to contain the new enums so that we can match it

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by devlead** [comment]
@narcopanda your changes have been merged, thanks for your contribution 👍

**Pull request merged**
