### PR TITLE
GH-3607: Add EnableCompressionInSingleFile to DotNetCorePublishSettings

### LINKED ISSUE #3607: Add `EnableCompressionInSingleFile` to `DotNetCorePublishSettings`
`EnableCompressionInSingleFile` is not yet included in `DotNetCorePublishSettings`.

>## Compress assemblies in single file app
>Starting with .NET 6, single file apps can be created with compression enabled on the embedded assemblies. Set EnableCompressionInSingleFile property to true to achieve this. The produced single-file will have all of the embedded assemblies compressed which can significantly reduce the size of the executable. Compression comes with a performance cost. On application start, the assemblies must be decompressed into memory, which takes some time. It's recommended to measure both the size impact and startup cost impact of enabling compression before using it as the impact varies a lot between different applications.
https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#compress-assemblies-in-single-file-app

_Originally posted by @SIkebe in https://github.com/cake-build/cake/discussions/3606_

### PR DESCRIPTION
**Pull request by SIkebe**
Fixes #3607

### CODE REVIEW

**Comment by devlead** [comment]
@SIkebe your changes have been merged, thanks for your contribution 👍

**Comment by SIkebe** [comment]
@augustoproiete Thanks! [This](https://twitter.com/v_intestine) is my account.

**Comment by SIkebe** [comment]
@augustoproiete @devlead Hi! This PR and the issue (#3607) are not included in the v2.0.0-rc0001 release note. Am I missing something?

image

**Comment by augustoproiete** [comment]
Sorry @SIkebe, the release notes are auto-generated and we forgot to add the issue https://github.com/cake-build/cake/issues/3607 to the v2.0.0 milestone so our process didn't include it. I've just updated the release notes to include this one and will update the blog post as well

**Comment by SIkebe** [comment]
@augustoproiete I've verified that the blog had been updated. Thanks!

**Pull request merged**
