### PR TITLE
GHxxx: Implemented changes to GetCommandLineArgs()

### PR DESCRIPTION
**Pull request by SteveGTR**
Changes make for the EnvironmentHelper.GetCommandLineArgs() changes.

### CODE REVIEW

**Comment by SteveGTR** [comment]
I messed up the commit. It required the additional change to Program.cs that I put in my next commit. Sorry about that, I just couldn't figure out how to include more than 1 file in my commit using the online tool.

To answer your question regarding the need for this change. It came about by me trying to debug the actual cake code. The default version when pulled into Visual Studio 2017 uses the .NET Core framework. When I setup everything in the Cake Project's Debug window and ran it, the Cake.exe is run through the dotnet.exe program. I discovered that that program doesn't put double quotes around the executable name (cake.exe). This is a problem when there are spaces in the fully qualified path. For instance:

c:\My Projects\cake-main\src ... etc

The original code joins all of the Environment.GetCommandLineArgs() with spaces. This results in:

[0] c:\My
[1] Projects\cake-main\src ...
[2] actual first parameter

The code plucks off the first parameter that it figures is the cake executable and goes about parsing the parameters. The code rejects the parameters as include.

I had a version that would double-quote the first parameter (if necessary) and go on to call the QuoteAwareStringSplitter method like before. This seemed crazy since the Environment.GetCommandLineArgs() already had everything ready for processing. So, I streamlined the code and move some of the nittygritting-ness to the helper functions.

Anyway, sorry for the mess I created.

**Comment by gep13** [comment]
>@SteveGTR said...
I messed up the commit. It required the additional change to Program.cs that I put in my next commit. Sorry about that, I just couldn't figure out how to include more than 1 file in my commit using the online tool.

You can't.  That currently isn't supported through the GitHub UI.

**Comment by SteveGTR** [comment]
Actually you can. At least using the main branch. You have to disable the Add-ins and there's one other modification to the parameters.cake file that allows the code to find the dotnet.exe. It works flawlessly and is very helpful (to me) in understanding the cake project.

**Comment by gep13** [comment]
@SteveGTR are you in a position to update this PR with all the changes that you would like to see in it so that we can review it properly?

**Comment by devlead** [comment]
Closed due inactivity please feel free to reopen this pull request, ping us and we'll review it again.

**Pull request closed without merging**
