### PR TITLE
GH1086: raw version line text in ReleaseNotes

### LINKED ISSUE #1086: Added raw version string property in ReleaseNotes class
This is kind of a follow-on from #885

@Redth's [SemVer package](https://github.com/Redth/Cake.SemVer) is great for parsing strings.
Built-in `ReleaseNotesParser` is great for extracting strings from a MarkDown file, but `ReleaseNotes` contains a typed `Version` property, with anything like `-preview3-rc8-0002938` stripped off.
If the Parser included the raw string that the Version was parsed from, we could send it off to SemVer for more complex parsing.

### PR DESCRIPTION
**Pull request by markrendle**

### CODE REVIEW

**Comment by markrendle** [comment]
Gosh, that's a lot of checks. How exciting.

**Comment by gep13** [comment]
>@markrendle said...
Gosh, that's a lot of checks. How exciting.

We like to be thorough :smile:

**Comment by gep13** [comment]
Relates to #1086

**Comment by gep13** [comment]
@markrendle thanks again for your contribution!  I am going to go ahead and pull this in, and it will be in the next release of Cake.  If you want to play with it before then, you will be able to grab the package from our MyGet Feed once the CI build finishes.

**Pull request merged**
