### PR TITLE
GH3485: Add alias for dotnet workload search command

### LINKED ISSUE #3485: Add alias for dotnet workload search command
`dotnet workload search` - Searches for optional workloads. Introduced with .NET 6 SDK.

The `dotnet workload search` command lists available workloads. You can filter the list by specifying all or part of the workload ID you're looking for.

Docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-search

### PR DESCRIPTION
**Pull request by Marusyk**
Add alias for dotnet workload search command

Fixes #3485

Please review
Thank you in advance

### CODE REVIEW

**Comment by Marusyk** [comment]
After merging this, I'm going to work on 

- dotnet workload update #3487
- dotnet workload uninstall #3486
- dotnet workload restore #3484
- dotnet workload repair #3483
- dotnet workload list #3482
- dotnet workload install #3481

Please assign all to me

**Comment by devlead** [comment]
I'm wondering how I would use this in a Cake script. Being `void` there's not much more than console output, so wondering what the use case is and if it might would make more sense to try to parse the output so it could be used in the script in some way.

I.e. the output for `dotnet workload search maui` is 
```
Workload ID           Description
-----------------------------------------------------
maui                  .NET MAUI SDK for all platforms
maui-android          .NET MAUI SDK for Android
maui-desktop          .NET MAUI SDK for Desktop
maui-ios              .NET MAUI SDK for iOS
maui-maccatalyst      .NET MAUI SDK for Mac Catalyst
maui-mobile           .NET MAUI SDK for Mobile
maui-windows          .NET MAUI SDK for Windows
```

Would it then make more sense to instead of
`void DotNetWorkloadSearch(this ICakeContext context, string searchString)`
have 
`ICollection<DotNetWorkload> DotNetWorkloadSearch(this ICakeContext context, string searchString)`

where `DotNetWorkload ` looked something like
```csharp
public class DotNetWorkload
{
    public string Id { get; }
    public string Description { get; }
    public DotNetWorkload(string id, string description)
    {
        Id = id;
        Description = description;
    }
}
```

So one could do something like
```csharp
var workloads = DotNetWorkloadSearch("maui");
foreach (var workload in workloads)
{
    Information(
            "Id: {0}, Description: {1}",
            workload.Id,
            workload.Description
            );
}
```

To get the stdout the DotNetWorkloadSearcher would have code something like
```csharp
...
            var processSettings = new ProcessSettings
            {
                RedirectStandardOutput = true
            };

            IEnumerable<string> result = null;
            RunCommand(settings, GetArguments(searchString, settings), processSettings,
                process => result = process.GetStandardOutput());

            return ParseResult(result)
                        .ToArray();
...
```
a naive parser could roughly look something like this as the table positions varies depending on data
```csharp
static IEnumerable<DotNetWorkload> ParseResult(IEnumerable<string> result)
{
    bool first = true;
    int descriptionIndex = -1;
    foreach (var line in result)
    {
        if (first)
        {
            if (line?.StartsWith("Workload ID") == true
                && (descriptionIndex = line?.IndexOf("Description") ?? -1) > 11)
            {
                first = false;
            }
            continue;
        }

        if (string.IsNullOrWhiteSpace(line))
        {
            continue;
        }

        var trimmedLine = line.Trim();

        if (trimmedLine.Trim().All(c => c == '-'))
        {
            continue;
        }

        yield return new DotNetWorkload(
            string.Concat(trimmedLine.Take(descriptionIndex)).TrimEnd(),
            string.Concat(trimmedLine.Skip(descriptionIndex))
            );
    }
}
```

Also, I would expect an overload `DotNetWorkloadSearch` that took an `DotNetWorkloadSearchSettings` parameter, now there's no way to access the `ToolSettings`.

**Comment by Marusyk** [comment]
Hi @gep13 
Thanks for the suggestions and help. 
Please review

**Review by devlead — APPROVED** [review]
LGTM

**Comment by devlead** [comment]
@Marusyk  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
