### PR TITLE
GH568: Added Gitter and Twitter Notifications

### PR DESCRIPTION
**Pull request by gep13**
Relates to #568

### CODE REVIEW

**Comment by gep13** [comment]
@devlead I have a suspicion, yes.  I suspect that my local copy had the gitattributes applied to all the files when I did this change.

Let me try rebasing on latest to see if that fixes it up.

**Comment by gep13** [comment]
hmm, ok, that doesn't seem to have done anything.  I suspect it is due to the gitattribute changes, but not really sure how best to verify/correct that :-(

**Comment by devlead** [comment]
Ok I'll take a quick look.

**Comment by devlead** [comment]
@gep13 better now right?

**Comment by gep13** [comment]
@devlead Yes, very much so! 😄 

What did you do?

**Comment by devlead** [comment]
Did following
```bash
git checkout develop
git checkout feature/GH-568V2
git diff bcf5fd2be09891e8aeaa928444a64369932dcb29 b3936392308c7faaef4606600c4ecf4f51848f72|Out-File -Encoding ascii C:\temp\patch.diff
git apply --ignore-whitespace c:\temp\patch.diff
git add .
git commit -m "(GH-568) Added Gitter and Twitter Notifications" -m "- When the build succeeds and it is a tagged master branch build, a tweet will be sent to Twitter and a message sent to Gitter room" --author "Gary Ewan Park <gep13@gep13.co.uk>"
git push -f origin feature/GH-568V2:feature/GH-568
```

**Comment by devlead** [comment]
@gep13 merged! Thanks for contributing 👍

**Comment by gep13** [comment]
@devlead and you knew how to do all of that because...

**Comment by devlead** [comment]
@gep13 done it before ;)

**Comment by gep13** [comment]
@devlead so was it due to the .gitattributes change, or something else?  i.e. what would have caused it at my end?

**Comment by devlead** [comment]
yes likely attributes issue

**Comment by gep13** [comment]
hmm, may have to remember this, as it might be required on existing PR's

**Pull request merged**
