### PR TITLE
GH3182: Update build to addin&modules targeting Cake 1.0

### LINKED ISSUE #3182: Update build addins and modules to versions targeting Cake 1.0
- Cake.DotNetTool.Module - 0.4.0 ➡️ ~~1.0.0~~ 1.0.1 
- Cake.Coveralls - 0.10.2 ➡️ 1.0.0 
- Cake.Twitter - 0.10.1➡️ 1.0.0 
- Cake.Gitter - 0.11.1➡️~~1.0.0~~ 1.0.1 

```
The assembly 'Cake.DotNetTool.Module, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.33.0).
For best compatibility it should target Cake.Core version 1.0.0.
The assembly 'Cake.Coveralls, Version=0.10.2.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.33.0).
For best compatibility it should target Cake.Core version 1.0.0.
The assembly 'Cake.Twitter, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.33.0).
For best compatibility it should target Cake.Core version 1.0.0.
The assembly 'Cake.Gitter, Version=0.11.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.33.0).
For best compatibility it should target Cake.Core version 1.0.0.
```

### PR DESCRIPTION
**Pull request by devlead**
- [x] Cake.DotNetTool.Module - 0.4.0 ➡️ ~~1.0.0~~ 1.0.1 
- [x] Cake.Coveralls - 0.10.2 ➡️ 1.0.0
- [x] Cake.Twitter - 0.10.1 ➡️ 1.0.0
- [x] Cake.Gitter - 0.11.1 ➡️ ~~1.0.0~~ 1.0.1 
- fixes #3182

### CODE REVIEW

**Comment by devlead** [comment]
Interesting errors on this one will need to investigate.

**Comment by gep13** [comment]
This could be down to me. I need to ship a 1.0.1 that only targets .netstandard for the module, rather than cross compiling.

**Comment by devlead** [comment]
I see, this one interesting too

```diff
- (3188,29): error CS0122: 'GitterChatApi' is inaccessible due to its protection level
- (3195,29): error CS0122: 'GitterChatApi' is inaccessible due to its protection level
```

**Comment by gep13** [comment]
Hmm, that might have been a change that I made as well... 😢

**Comment by gep13** [comment]
@devlead yes, this was as a result of a change that I made.  I added the CakeAddin.Analyzer package, which suggested that I needed the CakeMethodAlias added on some methods:

https://github.com/cake-contrib/Cake.Gitter/commit/3ef7e572b750ced153fd41397c4cff343737a39e

Looking again now, those are internal, so I shouldn't have added those.  Perhaps the analyzer shouldn't report on internal methods?

What are your thoughts @admiringworm?

**Comment by devlead** [comment]
Also maybe Cake shouldn't generate proxies for non public members 🤔

**Comment by gep13** [comment]
Hmm, yes, perhaps...

**Comment by AdmiringWorm** [comment]
@gep13 you are right, the analyzer shouldn't have recommended it on internal and private methods, only public methods and classes should be taken into account.
Can I ask you do crate an issue over at https://github.com/WormieCorp/Cake.Addin.Analyzer regarding this?

**Comment by gep13** [comment]
@AdmiringWorm issue raised here: https://github.com/WormieCorp/Cake.Addin.Analyzer/issues/22

**Comment by devlead** [comment]
@gep13 issue seems to be solved with Cake.DotNetTool.Module `1.0.1` and Cake.Gitter `1.0.1`. Rebased and pushed.

**Review by augustoproiete — APPROVED** [review]
LGTM

**Pull request merged**
