### PR TITLE
GH3681: Move `ScriptAssemblyResolver` logging to debug/diagnostic level

### LINKED ISSUE #3681: `ScriptAssemblyResolver` logging should be at debug/diagnostic level
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake .NET Tool

### Cake version

1.3.0

### Operating system

Windows

### Operating system architecture

64-Bit

### CI Server

GitHub Actions

### What are you seeing?

This has been noisy for a little while but is now exacerbated by dotnet 6.0 which logs about even more unused assemblies:
```
========================================
PublishToS3
========================================
Executing task: PublishToS3
Resolving assembly 'Xamarin.Forms.Core, Culture=neutral, PublicKeyToken=null' using runtime installed at 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0-rc.2.21480.5\'...
Exception occurred while resolving assembly Xamarin.Forms.Core: Could not load file or assembly 'Xamarin.Forms.Core, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Assembly 'Xamarin.Forms.Core, Culture=neutral, PublicKeyToken=null' not resolved
Resolving assembly 'UnityEngine.CoreModule, Culture=neutral, PublicKeyToken=null' using runtime installed at 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0-rc.2.21480.5\'...
Exception occurred while resolving assembly UnityEngine.CoreModule: Could not load file or assembly 'UnityEngine.CoreModule, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Assembly 'UnityEngine.CoreModule, Culture=neutral, PublicKeyToken=null' not resolved
Resolving assembly 'log4net, Culture=neutral, PublicKeyToken=null' using runtime installed at 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0-rc.2.21480.5\'...
Exception occurred while resolving assembly log4net: Could not load file or assembly 'log4net, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Assembly 'log4net, Culture=neutral, PublicKeyToken=null' not resolved
...
```
I'm not using any of the above assemblies: `Xamarin.Forms.Core`, `UnityEngine.CoreModule` or `log4net`; and I always run Cake builds at the verbose logging level, which is still reasonably quiet apart from these irrelevant (and hence noisy) assembly resolution failures.

### What is expected?

```
========================================
PublishToS3
========================================
Executing task: PublishToS3
...
```

### Steps to Reproduce

.

### Output log

_No response_

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #3681.

### CODE REVIEW

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by gitfool** [comment]
@augustoproiete any chance this could slip into `v2.0.0` along with other fixes? 🙏

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by devlead** [comment]
@gitfool  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
