### PR TITLE
Add dotnet sln and list commands

### PR DESCRIPTION
**Pull request by megakid**
This adds some additional commands for inspection and manipulation of solution and csproj files using the `dotnet` SDK CLI.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3817) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3817) before we can accept your contribution.<br/><br/>:x: megakid [sign now](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3817)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/cake?pullRequest=3817) it.</sub>

**Comment by gep13** [comment]
@megakid are you in a position to look at the failing CI builds, and to figure out what the issues with them are?

In addition, we discussed this internally, and we feel that this PR would be broken into two, one for the `sln` command, and one for the `list` command.  That will make it much easier to review and provide feedback.  In addition, as per the contributing guidelines, can you please create issues for this functionality that you would like to add?  Thanks!

**Comment by Marusyk** [comment]
if there is no answer from the author, let's create 2 issues (one for the sln command, and one for the list command) and I will try to prepare PRs
@gep13

**Comment by DmitryLukyanov** [comment]
I would love to see this merged, do you have any updates here?

**Comment by devlead** [comment]
> I would love to see this merged, do you have any updates here?

@DmitryLukyanov This PR currently waiting for issuer feedback as there are still some issues and missing tests with the proposed code that will need to be corrected before it can be merged.

In Cake 4.1 added dotnet list reference and list package with 
- #4353 
- #4224

So there's some overlap here already available in Cake, that also needs to be taken into account.

Unsure if @megakid has the cycles/opportunity to do so, if not we're open to reviewing alternative PRs.

**Comment by Marusyk** [comment]
Hi @DmitryLukyanov, 
`sln add` and `sln list` are already available in [Cake v5.0.0](https://cakebuild.net/blog/2024/11/cake-v5.0.0-released)
`sln remove` will be added in the next version ([PR is here](https://github.com/cake-build/cake/pull/4392))

**Comment by devlead** [comment]
> @devlead I suppose this PR can be closed

Yes.

 @megakid thanks for your contribution 👍

**Pull request closed without merging**
