### PR TITLE
Added information to summary tag

### PR DESCRIPTION
**Pull request by gep13**
- About how to include the necessary tool to get the aliases working correctly

Relates to #601

### CODE REVIEW

**Comment by gep13** [comment]
@devlead @patriksvensson what do you think about the following changes?  Good? Bad?

**Comment by gep13** [comment]
This is related to this as well: https://github.com/cake-build/cake/issues/491

If we can decide what we want to achieve, then I can go back and update all the summary tags.

**Comment by gep13** [comment]
@devlead @patriksvensson still looking for some thoughts on how to proceed with this.  Can I get your thought in this issue, and I can update PR. Thanks!

**Comment by devlead** [comment]
I think we should change  `#tool "ILRepack"` to `#tool "nuget:?package=ILRepack"` to make it more clear.

Also wonder if it would be enough if that was added too sample code though? I.e. here.
https://github.com/gep13/cake/blob/Issue-601/src/Cake.Common/Tools/ILMerge/ILMergeAliases.cs#L30

**Comment by gep13** [comment]
@devlead yip, that makes sense, and yes, I agree that is should **also** be added to sample code.

I think we should also have a `<see>` link as well, which takes you to the main site of the tool.  Thoughts?

**Comment by devlead** [comment]
@gep13 for me a see href makes sense.
@patriksvensson Thoughts?

**Comment by patriksvensson** [comment]
@gep13 A <see> tag to the tool would be very useful indeed.

**Comment by patriksvensson** [comment]
@gep13 @devlead I *think* I added support for `<see href=...">` but I'm not sure. Will check.

**Comment by patriksvensson** [comment]
@gep13 @devlead Yes, it's supported! :smile:

**Comment by devlead** [comment]
@gep13 this PR is out-of-date with the develop branch, could you please review, rebase and ping us when you think it's ready for review again.

**Comment by gep13** [comment]
@devlead I have just updated this.  Let me know what you think, and if you are happy with it, I can go ahead (at some point) and do the same thing for other aliases as well.

**Comment by devlead** [comment]
LGTM 👍

**Pull request merged**
