### PR TITLE
GH2778: Bump dependencies

### LINKED ISSUE #2778: Update Roslyn to 3.6.0
Currently, we use a beta version 3.6.0 in now released.

https://github.com/cake-build/cake/blob/0bed030ffb11ceb428ab65f7b9ef132c01768515/src/Cake/Cake.csproj#L30

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #2778.

### CODE REVIEW

**Comment by gitfool** [comment]
Notes:
* Held Autofac at `4.9.4` due to breaking changes
* Tests changed to target minimum `netcoreapp2.1` for [Microsoft.NET.Test.Sdk/16.6.1](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/16.6.1)
* Fixed new StyleCop warnings like [SA1629: DocumentationTextMustEndWithAPeriod](https://documentation.help/StyleCop/SA1629.html)

**Comment by gitfool** [comment]
@devlead `Azure Pipelines - Build Cake Windows` failure is unrelated to my changes. Please retry.

**Comment by gitfool** [comment]
Running `dotnet-outdated` after changes:
```
Cake/src on  gh2778 via •NET v3.1.300
❯ dotnet outdated
» Cake
  [.NETCoreApp,Version=v3.0]
  Autofac  4.9.4 -> 5.2.0
  [.NETCoreApp,Version=v2.0]
  Autofac  4.9.4 -> 5.2.0
  [.NETFramework,Version=v4.6.1]
  Autofac  4.9.4 -> 5.2.0
  [.NETCoreApp,Version=v2.1]
  Autofac  4.9.4 -> 5.2.0

Version color legend:
<red>   : Major version update or pre-release version. Possible breaking changes.
<yellow>: Minor version update. Backwards-compatible features added.
<green> : Patch version update. Backwards-compatible bug fixes.

You can upgrade packages to the latest version by passing the -u or -u:prompt option.
Elapsed: 00:00:06.2767355
```

**Comment by gitfool** [comment]
Sure. I'll suppress the StyleCop warnings in the first commit of this PR.

**Comment by devlead** [comment]
@gitfool we

> 
> Sure. I'll suppress the StyleCop warnings in the first commit of this PR.

As we use issues for release notes and changelog, we would prefer dependency bump to be a bit more focused, so not about suppressing issues, but just have the work for style copy dependency upgrade and fixes in a separate issue and PR.

**Comment by gitfool** [comment]
Understood. I'll keep `StyleCop.Analyzers` at `1.1.0-beta004` for this PR.

**Comment by devlead** [comment]
@gitfool your changes have been merged, thanks for your contribution 👍

**Comment by gep13** [comment]
@devlead the issue associated with this PR is marked as having been fixed in 0.38.0.  Does that need to be updated?

**Comment by devlead** [comment]
I will add a new issue, linked issue is for roslyn and aldready shipped.

**Pull request merged**
