### PR TITLE
Add support for IncludeReferencedProjects to NuGetPacker

### LINKED ISSUE #818: Add NuGetPacker support for IncludeReferencedProjects
[NuGetPacker.cs](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs) is missing support for `IncludeReferencedProjects`.

I need this now and there's no escape hatch to pass arbitrary command-line parameters.

References:
* [NuGet Pack](https://docs.nuget.org/consume/command-line-reference#pack-command)

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #818

### CODE REVIEW

**Comment by gitfool** [comment]
Sorry, first commit I somehow got the name around the wrong way. Could squash the commits before merge?

**Comment by gitfool** [comment]
Why did Bitrise - Ubuntu Cake fail?

**Comment by gep13** [comment]
>@gitfool said...
Why did Bitrise - Ubuntu Cake fail?

This was due to this:

```
Abort reason:
Timeout: Build took more than 600 seconds.
```

We have been seeing issues with Bitrise lately, and it's ability to resolve packages from NuGet.  This doesn't look like an issue with the PR itself.

**Comment by gep13** [comment]
>@gitfool said...
Could you squash the commits before merge?

If possible, can you please rebase your branch against the current develop branch, and correct the commits yourself.  That way, we can review the PR as it was intended.

**Comment by gitfool** [comment]
@gep13 Sure. Done.

**Comment by gep13** [comment]
@gitfool thanks for fixing this up, and thanks for the contribution to Cake.

**Comment by gep13** [comment]
**NOTE:** This PR was merged even though there was a failing build, as there are known issues with bitrise just now.

**Pull request merged**
