### PR TITLE
This closes #936

### LINKED ISSUE #936: IFile is missing a modified date
Cake currently has no way to compare the modified date of files using the filesystem interface.

Resolved in #911

### PR DESCRIPTION
**Pull request by phillipsj**
Took this pull request WRONG BRANCH: File Last Modified  #911 from @SharpeRAD and applied it to the current develop branch.  Didn't want this hanging out there as it is useful and it has been a few months.

### CODE REVIEW

**Comment by gep13** [comment]
@phillipsj looks like there are some StyleCop problems with this PR.  Can you fix them up?  You should be able to "see" them if you run the build in Release Configuration in Visual Studio?  Thanks!

**Comment by gep13** [comment]
@phillipsj I wanted to thank you again for taking the time to implement this, however...

I have spoken with both @devlead and @patriksvensson and at the minute, we are not going to pull this in.  The thinking behind this is that we don't think it is right in provide this single piece of functionality, without also doing work to pull in the rest of the File API surface area, and we don't think that this is correct direction for Cake.  For now, we want the Core of Cake to contain the base functionality, and then expose other functionality through addin's.  To this end, we think that the best place for this piece of work would be here:

https://github.com/Redth/Cake.FileHelpers

I am going to go ahead and close this Pull Request, and associated issue.  Thanks again!

**Comment by phillipsj** [comment]
@gep13 That is cool, totally respect the decision.  I am just grapping anything that I think I can handle and trying to contribute to a tool that I love.

**Comment by gep13** [comment]
>@phillipsj said...
@gep13 That is cool, totally respect the decision. I am just grapping anything that I think I can handle and trying to contribute to a tool that I love.

Very happy to hear that you are enjoying using it!

**Comment by SharpeRAD** [comment]
Glad to see its not just me that thinks this is useful @phillipsj. I appreciate that you don't want to pull in the entire File API @gep13 but code shouldn't have to be this [ugly](https://github.com/SharpeRAD/Cake.AWS.S3/blob/master/src/S3/Manager/S3Manager.cs#L336) :disappointed:

**Comment by gep13** [comment]
@SharpeRAD and I take your point, and an addition to the Cake.FileHelpers addin to include this method would allow your code to not be quite as verbose.

**Pull request closed without merging**
