### PR TITLE
GH1422: Add support for Unicode globbing

### PR DESCRIPTION
**Pull request by tom-dudley**
I've added Unicode support to the Globber by rewriting the `GlobTokenizer`. This fixes https://github.com/cake-build/cake/issues/1422

- Tokens are lazily loaded into a queue
- `GlobTokenizer` now specifies 'non-identifier characters' rather than 'identifier characters'
- Globbing is 15% faster
- Unicode supported

### CODE REVIEW

**Comment by tom-dudley** [comment]
If the OS X bitrise error is genuine (I read elsewhere you might be having issues with bitrise), could you make the output publicly viewable or let me know what the failure was? Thanks!

**Comment by patriksvensson** [comment]
@tom-dudley I took a look at it and it doesn't seem to be related to your changes.

**Comment by devlead** [comment]
@tom-dudley @patriksvensson reran the Bitrise Mac Build and it completed successfuly

**Comment by SIkebe** [comment]
@tom-dudley Thanks for taking this issue up!

**Comment by devlead** [comment]
@tom-dudley  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
