### PR TITLE
Added AppVeyor support.

### PR DESCRIPTION
**Pull request by patriksvensson**
**Support for:**

* Environment variables.
* Updating build version.
* Uploading build artifacts.

**Usage example:**

```csharp
if(!BuildSystem.IsLocalBuild)
{
    if(AppVeyor.IsRunningOnAppVeyor)
    {
        // Environment information.
        Information("APPVEYOR_API_URL: {0}", AppVeyor.Environment.ApiUrl);
        Information("APPVEYOR_JOB_ID: {0}", AppVeyor.Environment.JobId);
        Information("APPVEYOR_SCHEDULED_BUILD: {0}", AppVeyor.Environment.ScheduledBuild);
        Information("PLATFORM: {0}", AppVeyor.Environment.Platform);
        Information("CONFIGURATION: {0}", AppVeyor.Environment.Configuration);

        // Project information.
        Information("APPVEYOR_PROJECT_ID: {0}", AppVeyor.Environment.Project.Id);
        Information("APPVEYOR_PROJECT_NAME: {0}", AppVeyor.Environment.Project.Name);
        Information("APPVEYOR_PROJECT_SLUG: {0}", AppVeyor.Environment.Project.Slug);

        // Build information.
        Information("APPVEYOR_BUILD_FOLDER: {0}", AppVeyor.Environment.Build.Folder);
        Information("APPVEYOR_BUILD_ID: {0}", AppVeyor.Environment.Build.Id);
        Information("APPVEYOR_BUILD_NUMBER: {0}", AppVeyor.Environment.Build.Number);
        Information("APPVEYOR_BUILD_VERSION: {0}", AppVeyor.Environment.Build.Version);

        // Pull request information.
        if(AppVeyor.Environment.PullRequest.IsPullRequest)
        {
            Information("APPVEYOR_PULL_REQUEST_NUMBER: {0}", AppVeyor.Environment.PullRequest.Number);
            Information("APPVEYOR_PULL_REQUEST_TITLE: {0}", AppVeyor.Environment.PullRequest.Title);
        }

        // Repository information.
        Information("APPVEYOR_REPO_PROVIDER: {0}", AppVeyor.Environment.Repository.Provider);
        Information("APPVEYOR_REPO_SCM: {0}", AppVeyor.Environment.Repository.Scm);
        Information("APPVEYOR_REPO_NAME: {0}", AppVeyor.Environment.Repository.Name);
        Information("APPVEYOR_REPO_BRANCH: {0}", AppVeyor.Environment.Repository.Branch);

        // Tag information.
        if(AppVeyor.Environment.Repository.Tag.IsTag)
        {
            Information("APPVEYOR_REPO_TAG_NAME: {0}", AppVeyor.Environment.Repository.Tag.Name);
        }    

        // Commit information.
        Information("APPVEYOR_REPO_COMMIT: {0}", AppVeyor.Environment.Repository.Commit.Id);
        Information("APPVEYOR_REPO_COMMIT_AUTHOR: {0}", AppVeyor.Environment.Repository.Commit.Author);
        Information("APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL: {0}", AppVeyor.Environment.Repository.Commit.Email);
        Information("APPVEYOR_REPO_COMMIT_TIMESTAMP: {0}", AppVeyor.Environment.Repository.Commit.Timestamp);
        Information("APPVEYOR_REPO_COMMIT_MESSAGE: {0}", AppVeyor.Environment.Repository.Commit.Message);
        Information("APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED: {0}", AppVeyor.Environment.Repository.Commit.ExtendedMessage);

        // Upload artifact.
        AppVeyor.UploadArtifact("./file.zip");

        // Update build version.
        AppVeyor.UpdateBuildVersion("1.2.3");
        Information("New build version: {0}", AppVeyor.Environment.Build.Version);
    }
}
```

### CODE REVIEW

**Comment by gep13** [comment]
Sweet! :+1: 

@feodorfitsner will love this! :-)

**Comment by RichiCoder1** [comment]
Seems rather odd to have otherwise generic envvar functions in src/Cake.Common/Build/AppVeyor/AppVeyorInfo.cs

**Comment by patriksvensson** [comment]
@gep: Thanks! :smile: 

@RichiCoder1: This code might look reusable at first glance, but it actually does some things that are not very generic (such as returning 0 if a string is not an integer). This is ok for the AppVeyor stuff, but I wouldn't want it as generic functionality. It's more of a utility base class (which isn't pretty but removes a lot of clutter) :smile:

**Comment by FeodorFitsner** [comment]
Looks cool! Thanks, guys, for your support!

**Comment by RichiCoder1** [comment]
In that case, it looks awesome overall but with two comments:

1. Looking at the BuildSystem items, it looks like it was intended to eventually support another build system, but is completely coded for AppVeyor. What's the story there? I'd love to introduce TeamCity support, as it's also largely console & envvar based.

2.  Building off my last comment, it'd be great if that afformentioned class could be pulling out into some sort of EnviromentBaseBuildSystem base class or something. I'd see using many of those methods for TC.

Looks good otherwise! I may poke you some more later :3

**Comment by devlead** [comment]
Excellent functionality 👍  Now just rebase and merge ;)

**Comment by patriksvensson** [comment]
@RichiCoder1 Was so eager to merge that I forgot to write you an answer :smile: 

1. BuildSystem is meant to be expanded to take other build systems into account in the future. i.e. The property `IsLocalBuild` should return false later on, if the build isn't running on AppVeyor or TeamCity.

2. Agree, but it's better to introduce that base class when there's a need for it (i.e. when we implement TeamCity support and see that this functionality is shared).

**Comment by gep** [comment]
Guys, please, stop mentioning me. @patriksvensson, I always receive emails when you mention me like `@gep`. I'm not a cake developer.

Thanks in advance.

**Comment by patriksvensson** [comment]
@gep Always? Have I made that mistake more than once? Message was ment for @gep13.

**Comment by gep** [comment]
@patriksvensson, yeah, you did it more than once.

**Comment by patriksvensson** [comment]
@gep Sorry about that. Will try to be more careful in the future. You could always block me to prevent this from happening again.

**Comment by gep13** [comment]
You might also want to throw MyGet into the mix as well :-)

I have just added some MyGet helpers to psake:

https://github.com/psake/psake-contrib/blob/develop/myget.psm1

They expose similar Service Messaging to what TeamCity does.

**Pull request merged**
