### PR TITLE
WIP: Add SonarQube analysis

### PR DESCRIPTION
**Pull request by jairbubbles**
SonarQube is a static analysis tool for different languages (you can see here the dashboard for Roslyn https://sonarqube.com/dashboard/index?id=roslyn). SonarQube.com is now free for open source projects.

 I've made a very simple integration. Please let me know if you're interested and I'll improve the code. I'm very new to cake so I've probably made some stupid choices.

MSBuild Runner is not compatible with .xproj so I couldn't make an analysis for cake project.

The analysis is as three steps process (http://docs.sonarqube.org/display/SCAN/From+the+Command+Line#FromtheCommandLine-Analyzeaproject)

### CODE REVIEW

**Comment by gep13** [comment]
@jairbubbles thank you for taking the time to submit this.  As per our contributing process, can you please raise an issue for this, if there isn't one already and reference it from here?

https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md

Thanks!

**Comment by jairbubbles** [comment]
It seems addin are more suited for something like SonarQube.

**Comment by gep13** [comment]
@jairbubbles sorry that no-one got back to you about this.  Everyone has been pretty busy.

Yes, as you suggest, an addin might be the best option for this tool.

Let me know if you have any questions about creating an addin for it.  Also, if you haven't seen it, can I encourage you to read this: http://cakebuild.net/blog/2016/08/cake-contribution-organization before starting.  If you have any concerns about anything in there, again, feel free to reach out.

Thanks!

**Comment by jairbubbles** [comment]
@gep13 No problem !

If I want to add my addin to https://github.com/cake-contrib what should I do ? Is there a template depot I should copy to get CI working with NuGet packaging and so on ?

**Comment by gep13** [comment]
@jairbubbles the best bet would be to look at one of the repos that are already in the org, for example Cake.Gem, or Cake.Twitter, and use them as a template.  Once you are happy, we can move the repo into the org, and I can hook up all the permissions, and CI, to make everything come together.

**Pull request closed without merging**
