### PR TITLE
GH2623: Make Logger a collection

### PR DESCRIPTION
**Pull request by RehanSaeed**
Fixes https://github.com/cake-build/cake/issues/2623

### CODE REVIEW

**Comment by RehanSaeed** [comment]
@devlead What's the process for breaking changes?

**Comment by devlead** [comment]
@RehanSaeed haven't reviewed this PR in depth yet, but in general we try to obsolete stuff with warning one version,  with error next version and remove after that.

One way to not break could be to add a new property called Loggers concat it with Logger, obsolete Logger with warning.


But only took a quick look at the code, could be Loggers should be more typed i.e. FilePath and a trx/html/etc be a report type enum of some kind.

**Comment by gitfool** [comment]
Turns out I need this for multiple `Loggers` too, and now I think I should make the recently added `Collector` plural as well, before the next release though to avoid the breaking change dance.

Is `ICollection<string>` the preferred property type - which would play nicely with C# collection initializers?

Finally, there's a recent addition to add [`-e|--environment`](https://github.com/dotnet/sdk/blob/7d267abebfb4ff8b970158e38cd30045da85bd05/src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs#L37), which will also be accepted multiple times by `dotnet test`, so I'd add support for that the same way.

**Comment by azchohfi** [comment]
@RehanSaeed what is the status on this PR? The Logger**s** approach seems the best so far.
I'm up for helping get this to the finishing line. Let me know if you are doing the work or if you want me to help here.

**Comment by RehanSaeed** [comment]
I got snowed under by other work. Please feel free to take over this PR or raise a new one.

**Comment by gitfool** [comment]
@RehanSaeed @azchohfi I've submitted a new PR that covers this (multiple loggers) and multiple collectors.

**Comment by devlead** [comment]
Fixed by #2867

**Pull request closed without merging**
