### PR TITLE
GHxxx: Changes for .NET Core parsing issue

### PR DESCRIPTION
**Pull request by SteveGTR**
Make a mess of this upload. There are two files that I changed. I couldn't figure out how to coordinate this very well. Sorry for the mess.

### CODE REVIEW

**Comment by gep13** [comment]
@SteveGTR am I right in saying that this PR isn't required, and it is connected with the other PR that you raised?  If so, can you please provide some feedback about how you would like to continue?

**Comment by SteveGTR** [comment]
I haven't done anything with regard to these or any of my suggested changes. Moved on to other work items. I wish you all the best and thanks for the Cake :)

**Comment by gep13** [comment]
@SteveGTR how would you like for us to proceed with these PR's?  I don't think any of them are in a position to be merged, as they either have outstanding questions, or concerns.

**Comment by SteveGTR** [comment]
Are you referring to the .NET core parsing problem? You mention PRs, I'm not sure exactly what you mean.

**Comment by devlead** [comment]
Closed due inactivity please feel free to reopen this pull request, ping us and we'll review it again.

**Pull request closed without merging**
