### PR TITLE
(GH644) Added Bitrise CI build system support

### PR DESCRIPTION
**Pull request by RLittlesII**
Pull Request exposes the following environment variables from the Bitrise CI System.

References #644 

**Variable** | **Comment**
------------ | -------------
BITRISE_BUILD_NUMBER | build number of the build on bitrise.io
GIT_REPOSITORY_URL | git repository URL
BITRISE_APP_TITLE | app title on bitrise.io
BITRISE_APP_URL | app URL on bitrise.io
BITRISE_APP_SLUG | app slug on bitrise.io
BITRISE_BUILD_URL | build's URL on bitrise.io
BITRISE_BUILD_SLUG | build's slug on bitrise.io
BITRISE_BUILD_TRIGGER_TIMESTAMP | triggered at timestamp of the build
BITRISE_GIT_BRANCH | the branch which triggered the build
BITRISE_GIT_TAG | tag which triggered the build (if any)
BITRISE_GIT_COMMIT | commit hash which triggered the build (if any)
BITRISE_PULL_REQUEST | Pull Request ID, which triggered the build (if any)
BITRISE_PROVISION_URL | Provisioning Profile(s) URL - the ones uploaded to bitrise.io
BITRISE_CERTIFICATE_URL | Certificate / Identity URL - the one uploaded to bitrise.io
BITRISE_CERTIFICATE_PASSPHRASE | Certificate / Identity's password / passphrase, the one specified on bitrise.io

- [x]  Implement Bitrise Alias
- [x] Unit Test
- [x] Add code example comments

### CODE REVIEW

**Comment by devlead** [comment]
@RLittlesII Great :+1: I've taken a quick look and at least code compiles on BitRise :wink:, let us know when it's not WIP anymore or if you want us to review something.
I have setup a Bitrise account so I'm ready to test the bits.

A little feedback, some variables that could be good to include in PR too

| Variable                         | Sample value                                    | Comment                                              |
|----------------------------------|-------------------------------------------------|------------------------------------------------------|
| BITRISE_SOURCE_DIR               | /Users/vagrant/git                              | DirectoryPath to where project is cloned             |
| BITRISE_DEPLOY_DIR               | /Users/vagrant/deploy                           | DirectoryPath to store artifacts / files for deploy. |
| BITRISE_BUILD_STATUS             | 0                                               | boolean current status of the build - "0" if there are no failed steps yet, "1" if there's at least one failed step |
| BITRISE_TRIGGERED_WORKFLOW_ID    | Build & Test Cake on BitRise                    | the Workflow's ID which was triggered                |
| BITRISE_TRIGGERED_WORKFLOW_TITLE | Build & Test Cake on BitRise                    | the Workflow's title which was triggered             |

**Comment by RLittlesII** [comment]
@devlead I have a Bitrise account, and want to make sure it works in Bitrise.  I need to finish the unit tests and in the effort of having code examples in comments I want to add those to support that initiative.  I'll ping you when it's ready.

**Comment by devlead** [comment]
@RLittlesII superb :+1:

**Comment by RLittlesII** [comment]
@devlead I added the variables you requested. I wasn't able to test it on Bitrise.  I was able to test it with local environment variables.  I may try and see if I can test it with the Bitrise Cli.  Regardless, you're welcome to review this.

**Comment by devlead** [comment]
@RLittlesII Inital tests looks good, will do some more testing and merge if I don't find any issues.
```json
{
  "IsRunningOnBitrise": true,
  "Environment": {
    "Application": {
      "ApplicationTitle": "devlead/cake",
      "ApplicationUrl": "https://www.bitrise.io/app/f9b2d0fbcae85d3b",
      "AppSlug": "f9b2d0fbcae85d3b"
    },
    "Build": {
      "BuildNumber": "9",
      "BuildUrl": "https://www.bitrise.io/build/127f16fb5fc6a4b8",
      "BuildSlug": "127f16fb5fc6a4b8",
      "BuildTriggerTimestamp": "1458219040",
      "BuildStatus": false
    },
    "Directory": {
      "SourceDirectory": "/Users/vagrant/git",
      "DeployDirectory": "/Users/vagrant/deploy"
    },
    "Provisioning": {
      "ProvisionUrl": "https://s3-us-west-2.amazonaws.com/concrete-core-production/cert-profiles/BuildAnything.mobileprovision",
      "CertificateUrl": "https://s3-us-west-2.amazonaws.com/concrete-core-production/cert-profiles/Certificates.p12",
      "CertificatePassphrase": "Concrete"
    },
    "Repository": {
      "GitRepositoryUrl": "git@github.com:devlead/cake.git",
      "GitBranch": "RLittlesII-GH644",
      "GitTag": "",
      "GitCommit": "",
      "PullRequest": ""
    },
    "Workflow": {
      "WorkflowId": "Build & Test Cake on BitRise",
      "WorkflowTitle": "Build & Test Cake on BitRise"
    }
  }
}
```

**Comment by devlead** [comment]
@RLittlesII merged, thanks for your contribution :+1:

**Pull request merged**
