### PR TITLE
GH2524: Added support for XSL arguments in XmlTransform

### LINKED ISSUE #2524: XmlTransform support for xsl arguments
The XmlTransform aliases seem to be a bit restricted for our scenario. We have some advanced xsl scripts that expect xslt arguments to be passed to the transformer. Using the .NET libraries that would be the `System.Xml.Xslt.XsltArgumentList` which can be passed to the `Transform` method of `XslCompiledTransformation`. (which is used by the XmlTransform alias)
Any change for getting an update with support for transfromation arguments?

### PR DESCRIPTION
**Pull request by deqenq**
fixes #2524

I added two overloaded XmlTransform methods that accept XsltArgumentList as arguments for XSL tranformation.  Also new unit tests were added - I tried to use existing input/output sample data as much as possible so there are only two new XSL definitions (with arguments) needed.

### CODE REVIEW

**Comment by deqenq** [comment]
Just curious, did I something wrong with this pull request? Please tell me...

**Comment by devlead** [comment]
@deqenq sorry, you've done nothing wrong, current status it's on the Cake team to fully review this, which we've unfortunately not gotten around to yet.

**Comment by deqenq** [comment]
Should I try to resuscitate this pull request or not? That's the question.

**Review by nils-a — CHANGES_REQUESTED** [review]
@deqenq sorry for this late feedback. The changes look good. 

However, there are - in addition to the static `XmlTransformation.Transform()` methods - also corresponding overloads in `XmlTransformationAlias` to be used as extensions to the `ICakeContext`.

Are you in a position to add those, as well?

**Comment by deqenq** [comment]
@nils-a Thank you for your suggestions, I will try to fix it.

**Review by nils-a — APPROVED** [review]
LGTM!

**Comment by nils-a** [comment]
@deqenq your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
