### PR TITLE
GH1293: Add mechanism to validate addins

### PR DESCRIPTION
**Pull request by patriksvensson**
* Added verification of addins, modules and directly references assemblies.

~~Haven't added functionality for letting addins decide what version of Cake they require yet.~~
I will add the attribute now for addins to use to require and we'll add the check in a later version.

### CODE REVIEW

**Comment by devlead** [comment]
@patriksvensson are you in a position to rebase against latest development and add the last bits so we can review this PR for merging?

**Comment by patriksvensson** [comment]
I'll rebase it in a couple of hours.

**Comment by patriksvensson** [comment]
Rebased against develop.

**Comment by devlead** [comment]
Relates to #1293

**Pull request merged**
