### PR TITLE
GH1614:  Corrected inheritance issue.

### PR DESCRIPTION
**Pull request by phillipsj**
This just changes the inheritance to the correct abstract class.

### CODE REVIEW

**Comment by kcamp** [comment]
Since this is technically a breaking change, could we potentially coordinate this change with another change to TeamCity objects in the same release/milestone?

Ideally, there are some changes outlined in GH-1431 that would go a long way in opening up the service message API on the `TeamCityProvider` in an effort to complete that API; more details are outlined in that issue.  Apologies for the random comment, but it seems opportune.  Thanks!

**Comment by phillipsj** [comment]
@kcamp I agree if we have more teamcity updates that can go in.  I think the TeamCity provider needs some love compared to the others.

**Comment by gep13** [comment]
Relates to #1614 1614

**Comment by devlead** [comment]
@phillipsj  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
