### PR TITLE
Added support for Roundhouse DB Migrations

### PR DESCRIPTION
**Pull request by ChrisMissal**
Initial implementation for Roundhouse support (Issue #285).

### CODE REVIEW

**Comment by ChrisMissal** [comment]
@patriksvensson This does the trick to get RH tool support. I can imagine more aliases being created once I start using this more, or from others using it, but I wanted to keep things simple to start.

:cake:

**Comment by patriksvensson** [comment]
I think that the alias should be called `RoundhouseMigrate` rather than just `Migrate`. This would be good so it won't be ambiguous with other tools like EF migrations or FluentMigrator if we want to introduce support for them in the future.

Is any of the data sensitive in the sense that you wouldn't want them to appear in a build log such as database connection strings? In that case I would suggest appending a [SecretArgument](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/IO/Arguments/SecretArgument.cs). 

The ProcessArguments are composable so you could do like this:

```csharp
var secret = new SecretArgument(new TextArgument("--amg=986b0e4a"));
builder.AppendQuoted(secret);
```

This would appear as `rh.exe "[REDACTED]"` in the build log.

Great work btw :+1:

**Comment by ChrisMissal** [comment]
@patriksvensson Good catches, fixed, thanks!

**Comment by RichiCoder1** [comment]
Random food for thought might also be making Roundhouse a property like AppVeyor and such, and then expose the methods on it rather then have them be straight aliases. I won't the be the end user though, so it's just a thought.

**Comment by ChrisMissal** [comment]
I'm open to that, but I've only just begun using Cake, but that seems to make sense to me.

**Comment by patriksvensson** [comment]
I think it would fit in better with the other tool if we just exposed alias methods like it is now.

AppVeyor is a little bit special since it has a lot of nested properties - and to be honest I'm not super happy with it since discoverability is really bad.

Good idea though :smile:

**Comment by ChrisMissal** [comment]
Digging in a bit more, I'm not sure there's much to be gained by that approach. Since everything needed is on the settings object, the method calls wouldn't have arguments, so passing the settings in would essentially be the same thing. Here's an example of how I'm using it now:

```csharp
var target = Argument("target", "Migrate");

var settings = new RoundhouseSettings {
    ToolPath = @"path\to\rh",
    Environment = "LOCAL",
    ConnectionString = "Server=localhost;Database=Blarg;Trusted_Connection=True;MultipleActiveResultSets=true",
    SqlFilesDirectory = @"src\DatabaseMigration",
    Silent = true,
};

Task("Rebuild")
  .IsDependentOn("Drop")
  .IsDependentOn("Migrate");

Task("Migrate")
  .Does(() => {
    Migrate(settings);
  });

Task("Drop")
  .Does(() => {
    Drop(settings);
  });

RunTarget(target);
```

Correct me if I'm wrong, but that change would look more like this:

```csharp
var target = Argument("target", "Migrate");

var settings = new RoundhouseSettings {
    ToolPath = @"path\to\rh",
    Environment = "LOCAL",
    ConnectionString = "Server=localhost;Database=Blarg;Trusted_Connection=True;MultipleActiveResultSets=true",
    SqlFilesDirectory = @"src\DatabaseMigration",
    Silent = true,
};
var rh = Roundhouse.Create(settings); // or something to get a context based on settings?

Task("Rebuild")
  .IsDependentOn("Drop")
  .IsDependentOn("Migrate");

Task("Migrate")
  .Does(() => {
    rh.Migrate();
  });

Task("Drop")
  .Does(() => {
    rh.Drop();
  });

RunTarget(target);
```

If that hurts discoverability, I'd vote against it.

***Mostly just thinking out loud here...***

**Comment by RichiCoder1** [comment]
Oh, I was thinking more like:
```c#
var target = Argument("target", "Migrate");

var settings = new RoundhouseSettings {
    ToolPath = @"path\to\rh",
    Environment = "LOCAL",
    ConnectionString = "Server=localhost;Database=Blarg;Trusted_Connection=True;MultipleActiveResultSets=true",
    SqlFilesDirectory = @"src\DatabaseMigration",
    Silent = true,
};

Task("Rebuild")
  .IsDependentOn("Drop")
  .IsDependentOn("Migrate");

Task("Migrate")
  .Does(() => {
    Roundhouse.Migrate(settings);
  });

Task("Drop")
  .Does(() => {
    Roundhouse.Drop(settings);
  });

RunTarget(target);
```

Interesting thought creating an object though.

**Comment by patriksvensson** [comment]
Yes, but I think it would be better to keep to the conventions used by the other tools. AppVeyor and TeamCity have so many properties and methods that it made sense at the tim. 

If I could break stuff like crazy I would probably remove alias properties completely :smile:

**Comment by ChrisMissal** [comment]
Sounds like changes for the v1.0 release ;)

I don't have any more commits to add, so unless anybody has any other feedback, I'd call this PR good to go.

**Comment by patriksvensson** [comment]
Merged! :+1:

**Pull request closed without merging**
