### PR TITLE
DNU doesn't like semi-colons anymore.  It uses multiple args for the same flag.

### PR DESCRIPTION
**Pull request by adamhathcock**
Same as https://github.com/cake-build/cake/pull/834

Rebased on develop for release with 0.11.0

Thanks!

### CODE REVIEW

**Comment by devlead** [comment]
@adamhathcock could you squash into one commit and ping me when done and I'll review for merging.

**Comment by adamhathcock** [comment]
@devlead I think this is good to go now.  Thanks!

**Comment by devlead** [comment]
@adamhathcock thanks, I'll review and merge if all's ok.

**Comment by devlead** [comment]
Relates to #839

**Comment by devlead** [comment]
@adamhathcock merged :+1: Thanks for your contribution!

**Pull request merged**
