### PR TITLE
GH1908: Octo improvements - list-deployments implementation for octo.exe

### PR DESCRIPTION
**Pull request by CRuppert**
reference feature request #1908 

I am guessing you might want something cleaner for the stuff for the string in src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctopusDeploymentQueryTests.cs line 260+.

I'm open to ideas as to how you approach that, since most of the source I read was write-heavy and doesn't do too much parsing, relying mostly on return codes when you have to shell out. I figured that I'd leave it until you said otherwise, since it's pretty darn specific and going the whole embedded resource route or similar seemed a bit overkill.

### CODE REVIEW

**Comment by CRuppert** [comment]
You should find I have signed the CLA at this point. :)

**Comment by gep13** [comment]
@dnfclas @dnfgituser can you please confirm that this is the case?

@CRuppert sorry, just need to make sure

**Comment by gep13** [comment]
@CRuppert we have been seeing some issues with the CLA bot that we are using.

**Comment by CRuppert** [comment]
I was preemptive on the license. my bad. :) now it's done for sure.

**Comment by devlead** [comment]
@CRuppert  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
