### PR TITLE
GH1294: Added signing of artifacts.

### PR DESCRIPTION
**Pull request by patriksvensson**
Signs the following:

* Zip files (for GitHub and Homebrew)
* NuGet packages
* Chocolatey packages

Signing will only occur at a real release.
You can suppress signing by passing the `--skipsigning=true` parameter to the bootstrapper.

Related to #1294

### CODE REVIEW

**Comment by devlead** [comment]
@patriksvensson Merged! Thanks for contributing 👍

**Comment by gep13** [comment]
fyi... @onovotny @martinwoodward

**Comment by onovotny** [comment]
Only thought -- you don't really need the `signclient.filter` file as by default it'll try to sign all known/signable file types in the package. That's more for when you want to specifically not sign something, like a 3rd party library included in the package.

**Comment by devlead** [comment]
Got some third parties in the Cake/Cake.CoreCLR packages though.

**Comment by patriksvensson** [comment]
Yes exactly. We don't want to sign third party assemblies in the Cake and Cake.CoreClr packages.

**Pull request merged**
