### PR TITLE
GH1471: Modified the order of resolution of the NuGet tool in the NuGetToolResolver class

### PR DESCRIPTION
**Pull request by Texernie**
This will fix issue #1471.

I simply changed the NuGetToolResolver class to prefer the environment's override if available.

### CODE REVIEW

**Comment by devlead** [comment]
Hi @Texernie,
Thanks for contributing to Cake 👍 
We've discussed this internally within @cake-build/team and think changing tool ordering precedence for NuGet in this case  brings more risk than benefit.
So unfortunately I'll not accept the proposed PR.

That said as a work around it's still possible to solve your use case within Cake by in your script setup task register the path from the environment variable, that will override the default tool resolution behavior for all aliases using the nuget.exe.
Example below:
```cake
Setup(
    context => {
    var nugetExe = EnvironmentVariable("NUGET_EXE");
    if (!string.IsNullOrEmpty(nugetExe))
    {
        context.Tools.RegisterFile(nugetExe);
    }
});


Task("My-NuGetTask")
    .Does(()=> {
    Information("{0}", Context.Tools.Resolve("nuget.exe"));
});


RunTarget("My-NuGetTask");
```

Yet again, thanks for taking the time to contribute to Cake, all contributions and feedback is appreciated.

**Comment by Texernie** [comment]
If I may inquire then, what is the purpose of saving the nuget.exe path to environment to be available to child processes in the bootstrap https://raw.githubusercontent.com/cake-build/resources/master/build.ps1 if it will not be used by the tools inside of Cake? Why save it to the environment if the filesystem will override the setting?

**Comment by devlead** [comment]
Unified tool resolution wasn't avail when script was initially written.

**Comment by Texernie** [comment]
The environment pull was added in https://github.com/cake-build/cake/commit/b4f2fd3ac30bc8fae9a72aa6454a2b6bdd8746f8 when the whole class was rewritten for the new resolution scheme. So the feature was added after INuGetToolResolver was added?

**Comment by Texernie** [comment]
I'm not necessarily trying to be difficult, I am just trying to understand why the file system takes priority at the whim of whichever file it happens to find over a setting described exactly for this purpose.

**Comment by Texernie** [comment]
As an end user, when I see a setting in the bootstrap file with the comment of "Save nuget.exe path to environment to be available to child processed", I would expect that executable to be used as a priority.

**Comment by devlead** [comment]
No worries, appreciate the feedback.

Yes but if registered using `context.Tools.RegisterFile(nugetExe);` or via tool override in your script you would expect that to be used.

NUGET_EXE is a convention used by some tools, Cake supports but it's unified way to look for tools is
1. Use explicitly set tool path on [ToolSettings](http://cakebuild.net/api/Cake.Core.Tooling/ToolSettings) [ToolPath](http://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/F6956DA8) property.
2. Via [IToolLocator](http://cakebuild.net/api/Cake.Core.Tooling/IToolLocator/) registered path (see example above).
3. Try to find the tool by searching `./tools/**/mytool.exe`.
4. Look through all paths in the `PATH` environment variable and look for `mytool.exe`.
5. Ask the tool wrapper for additional, alternative paths.

Main reason is though that the risk if regression is too big, as many use custom or no bootstrappers with their CI.

Tool resolution is documented at http://cakebuild.net/docs/tools/tool-resolution , but I'm going to look att improving that using the feedback given here.

**Comment by Texernie** [comment]
Mattias, I totally understand the regression test issue. You have given me a work around that will work at least. That work around should probably be included in the documentation somewhere. I also understand your comment that if context.Tools.RegisterFile was used that the specific file registered would be expected to be used instead of a registry setting. Thank you for taking the time to explain the other ramifications and providing a work around.

**Pull request closed without merging**
