### PR TITLE
Use new OutputDirectory Setting for Chocolatey Pack

### PR DESCRIPTION
**Pull request by gep13**
Relates to GH-505

### CODE REVIEW

**Comment by gep13** [comment]
@patriksvensson does the build process not grab the latest version of Cake from MyGet?  #lazydeveloper

**Comment by patriksvensson** [comment]
@gep13 No, it grabs the latest official version at the moment. Should add separate CI  for this.

**Comment by gep13** [comment]
Related to this, do we want to add the environment variables for Chocolatey/Nuget into the AppVeyor yaml file, so that we can push the packages out automatically when the master branch is being built?

**Comment by patriksvensson** [comment]
We can add the tasks, but I think it could be a manual step like NuGet for
the moment.

**Pull request closed without merging**
