### PR TITLE
Fixed debugging of CoreCLR scripts.

### PR DESCRIPTION
**Pull request by patriksvensson**
- [x] Added portable pdb:s
- [x] Added module for Common project (temporary workaround)

### CODE REVIEW

**Comment by mholo65** [comment]
Great job hunting this down. Can you explain why Cake.Common needs to be a module in order to watch variables of types it contains?

**Comment by patriksvensson** [comment]
@mholo65 The assembly seems to have to be loaded in the default assembly load context. Making sure that Cake loads it solved the problem. The problem remains for addins and modules though, so we will need to solve this in the long run. I need to understand load contexts better but the documentation is sparse at best...

**Comment by devlead** [comment]
Yay! LGTM!
image
I'll merge shortly :+1:

**Comment by gep13** [comment]
@devlead @patriksvensson @mholo65 yip, worked for me during the demo today, so I would say it is good to go :smile:

**Comment by mholo65** [comment]
@gep13 great that you dared to demo debugging in VS Code :+1:

**Comment by gep13** [comment]
>@mholo65 said...
@gep13 great that you dared to demo debugging in VS Code :+1:

Almost all of the demo is done in VSCode, so I wanted to throw in the debugging in VSCode as well.  The last time I gave the talk I jumped to using Visual Studio to do it, but it was a much better story to show it happening in VSCode as well :smile: 

It was even done using the Light Theme :smile: in VSCode.  It shows up a lot better on the projector, typically I use the dark theme.

**Comment by gep13** [comment]
Relates to #1237

**Pull request merged**
