### PR TITLE
Signtool: Add support for certificates from the certificate store bas…

### PR DESCRIPTION
**Pull request by apmorton**
…ed on thumbprint

Signed-off-by: Austin Morton <amorton@eaglabs.com>

### CODE REVIEW

**Comment by devlead** [comment]
@apmorton could you please rebase against latest and ping back when that's done.

**Comment by apmorton** [comment]
@devlead ping

**Comment by devlead** [comment]
@apmorton #812 is now merged i to develop, you'll need to rebase this PR, ping me when done and I'll merge.

**Comment by apmorton** [comment]
@devlead done. Thanks for reviewing these PR's quickly!

**Comment by devlead** [comment]
@apmorton I'm just waiting for CI to complete and I'll merge.

**Comment by devlead** [comment]
refers to #832

**Pull request merged**
