### PR TITLE
GH-3081: Add netcoreapp3.1 target to Cake

### LINKED ISSUE #3081: Add netcoreapp3.1 target to Cake
`netcoreapp3.1` is LTS.

[image](https://dotnet.microsoft.com/download/dotnet-core)

https://dotnet.microsoft.com/download/dotnet-core

### PR DESCRIPTION
**Pull request by augustoproiete**
Tests already target `netcoreapp3.1` so changes needed there.

---

Closes #3081

### CODE REVIEW

**Comment by devlead** [comment]
In phone, but this probably relates to / maybe duplicates #2873

**Comment by augustoproiete** [comment]
@devlead It's definitely related, but #2873 is breaking and doesn't seem we'll merge until Cake v2.0. This PR is additive, only to help devs that don't have `netcoreapp3.1` and higher only, and don't want to deal with roll-forward.

**Comment by devlead** [comment]
@augustoproiete back at computer, agreed 👍

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by devlead** [comment]
@augustoproiete your changes have been merged, thanks for your contribution 👍

**Pull request merged**
