### PR TITLE
#406: Adding ProcessAliases.StartProcess overload taking process arguments as string

### PR DESCRIPTION
**Pull request by danielrozo**
Implementing #406.

### CODE REVIEW

**Comment by patriksvensson** [comment]
Looks good to me :+1: 
Would you mind rebasing (synchronize) against develop and squash this to a single commit and I'll merge it? Thanks :smile:

**Comment by danielrozo** [comment]
It should have a linear history now :)

**Comment by patriksvensson** [comment]
Perfect. Will merge later tonight when I have access to a computer :+1:

**Comment by patriksvensson** [comment]
Merged :+1: 
(Have to close it manually since I had to rebase it against the develop branch which was ahead)

**Pull request closed without merging**
