### PR TITLE
Changed NUnit argument prefix from '/' to '-'.

### PR DESCRIPTION
**Pull request by samvik**
This according to nunit documentation.
http://www.nunit.org/index.php?p=consoleCommandLine&r=2.6

Also renamed file with incorrect capitalization to be able to build on Linux.

### CODE REVIEW

**Comment by patriksvensson** [comment]
@samvik Good catch! :+1: 

Since Windows support both hyphen and slash, maybe it would be better to simply change the argument to a hyphen?

**Comment by samvik** [comment]
That would be the most clean solution. I'm all for that. Just wasn't sure if that would introduce any side effects on windows.

**Comment by patriksvensson** [comment]
@samvik Good thinking! Just update the PR when you have time and I'll merge it :smile:

**Comment by devlead** [comment]
Hi @samvik, please when you have the opportunity update PR and rebase against latest and we'll look at merging this.

**Comment by samvik** [comment]
I should be up to date with develop now.

**Comment by devlead** [comment]
@samvik merged! Thanks :+1:

**Pull request merged**
