### PR TITLE
GH1245: Added % to alphanumeric chars allowed in glob

### LINKED ISSUE #1245: Globber exception when glob contains %
### What You Are Seeing?
When running cake from inside a folder containing a % sign in the name like:
C:\Some%2FDirectory\cake.exe build.cake
The "Installing tools" step fails with a NotSupportedException:  "Unknown token"
### What is Expected?
GlobTokenizer should treat the % sign as alphanumeric and allow the directory to be globbed.

### What version of Cake are you using?
Version 0.15.2+Branch.main.Sha.c2ca4f7ca51c59dc9c47c9830125b4e66cf14e7a
### Are you running on a 32 or 64 bit system?
64bit
### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
Yes, Jenkins. But able to reproduce locally as well.

### How Did You Get This To Happen? (Steps to Reproduce)
Try to run cake inside a folder that has a encoded slash in the name: "%2F"

### Output Log
~~~sh
F:\JenkinsDevSlave\workspace\CSP\CSP Multibranch pipeline\feature%2Ftestingmodifiedpipeline>powershell -NoLogo -NonInteractive -File setup.ps1 -Verbosity Diagnostic 
Preparing to run build script...
Running build script...
Module directory does not exist.
Analyzing build script...
Analyzing F:/JenkinsDevSlave/workspace/CSP/CSP Multibranch pipeline/feature%2Ftestingmodifiedpipeline/build.cake...
Processing build script...
Installing tools...
Installing NuGet package OpenCover...
Executing: "F:/JenkinsDevSlave/workspace/CSP/CSP Multibranch pipeline/feature%2Ftestingmodifiedpipeline/tools/nuget.exe" install "OpenCover" -OutputDirectory "F:/JenkinsDevSlave/workspace/CSP/CSP Multibranch pipeline/feature%2Ftestingmodifiedpipeline/tools" -ExcludeVersion -NonInteractive -NoCache
Error: System.NotSupportedException: Unknown token
   at Cake.Core.IO.Globbing.GlobTokenizer.ScanToken()
   at Cake.Core.IO.Globbing.GlobTokenizer.Scan()
   at Cake.Core.IO.Globbing.GlobParserContext.Accept()
   at Cake.Core.IO.Globbing.GlobParserContext.Accept(GlobTokenKind[] kind)
   at Cake.Core.IO.Globbing.GlobParserContext.Accept(GlobTokenKind kind)
   at Cake.Core.IO.Globbing.GlobParser.ParseIdentifier(GlobParserContext context)
   at Cake.Core.IO.Globbing.GlobParser.ParseSubSegment(GlobParserContext context)
   at Cake.Core.IO.Globbing.GlobParser.ParseSegment(GlobParserContext context)
   at Cake.Core.IO.Globbing.GlobParser.Parse(GlobParserContext context)
   at Cake.Core.IO.Globbing.GlobParser.Parse(String pattern, Boolean caseSensitive)
   at Cake.Core.IO.Globber.Match(String pattern, Func`2 predicate)
   at Cake.Core.IO.GlobberExtensions.Match(IGlobber globber, String pattern)
   at Cake.Core.IO.GlobberExtensions.GetFiles(IGlobber globber, String pattern)
   at Cake.NuGet.NuGetContentResolver.GetFiles(DirectoryPath path, PackageReference package)
   at Cake.NuGet.NuGetContentResolver.GetToolFiles(DirectoryPath path, PackageReference package)
   at Cake.NuGet.NuGetContentResolver.GetFiles(DirectoryPath path, PackageReference package, PackageType type)
   at Cake.NuGet.NuGetPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path)
   at Cake.Core.Scripting.ScriptProcessor.InstallTools(ScriptAnalyzerResult analyzerResult, DirectoryPath installPath)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
~~~

### PR DESCRIPTION
**Pull request by ZanMgtZack**
Modified GlobTokenizer to allow % sign as an alphanumeric character. Fixes #1245

### CODE REVIEW

**Comment by gep13** [comment]
@ZanMgtZack thank you very much for your contribution to Cake, we really appreciate it.

We have had a quick discussion about this, and we think that rather than adding characters on a case by case basis, it might be better to query the `Path.GetInvalidPathChars` method, and construct a regex to ensure that these are not included.

Would you be in a position to modify this PR to use this slightly different approach?  Thanks!

**Comment by patriksvensson** [comment]
@gep13 I agree with what you're saying, but perhaps we can get this change merges and add a new issue to fix the globbing properly later. What do you think?

**Comment by gep13** [comment]
@patriksvensson sure thing.

**Comment by gep13** [comment]
@ZanMgtZack thank you for taking the time to submit this.

I have rebased and merged your PR here: https://github.com/cake-build/cake/commit/042bd46cf6e161c8ad13eec364454a994bd2dc44

As a result, I am going to manually go this PR, however, your contribution has been correctly attributed.  Thanks!

**Comment by gep13** [comment]
Thanks again for your contribution!

**Pull request closed without merging**
