### PR TITLE
GH2585: Helpcommand includes help about Target

### PR DESCRIPTION
**Pull request by Roadrunner67**
Usage: Cake.exe [script] **[--target=value]** [--verbosity=value]
                [--showdescription] [--dryrun] [..]

Example: Cake.exe
Example: Cake.exe build.cake --verbosity=quiet
Example: Cake.exe build.cake --showdescription

Options:
    **--target=value       Specifies the target to build. Surround with quotes if target contains special chars.**
    --verbosity=value    Specifies the amount of information to be displayed.
                         (Quiet, Minimal, Normal, Verbose, Diagnostic)
    --debug              Performs a debug.
    --showdescription    Shows description about tasks.
    --showtree           Shows the task dependency tree.
    --dryrun             Performs a dry run.
    --exclusive          Execute a single task without any dependencies.
    --bootstrap          Download/install modules defined by #module directives
    --version            Displays version information.
    --info               Displays additional information about Cake execution.
    --help               Displays usage information.

### CODE REVIEW

**Comment by gep13** [comment]
@Roadrunner67 thank you for submitting this PR, we really appreciate your contribution.

I have one problem with this addition, and I would like to discuss it further...

Cake.exe, Cake.CoreClr.dll, and Cake.Tool don't have a `--target` argument.  By this, I mean that nothing in the internals of the Cake Engine will do anything with that argument.  Unlike the other arguments, which the Cake Engine will do something with directly, like show the help menu, or include descriptions for tasks, etc.  The `--target` argument is a convention, which needs to be implemented within your Cake script, which is ultimately either passed to the `RunTarget` method, or not.

For example, it is perfectly valid to have a Cake script that *doesn't* have a target argument, in which case, this addition to the help menu wouldn't do anything.

As a result, I have a problem with adding this directly into the help menu for Cake.

I agree that we might need to better document this convention "somewhere" but I don't think this is the right place.

@cake-build/cake-team what are your thoughts?

**Comment by Roadrunner67** [comment]
@gep13 You are right, it is completely a conventional thing, that we divide our Cake scripts into tasks.

I think on the other hand, that the answer given to VictorioBerra in issue #2585 was less than optimal, as he also seems to be unaware about this.

**Comment by devlead** [comment]
@Roadrunner67 @gep13 IMHO I think target is such a common parameter so it would be good if it was documented. That said it must be clear that it's up to the script to support this. i.e something like.
`--target <TARGET>  Target task to invoke. Script must support this explicitly`

Also we don't need to have quotes mentioned explicitly as this is the same for all shell commands.

**Comment by Roadrunner67** [comment]
> @Roadrunner67 @gep13 IMHO I think target is such a common parameter so it would be good if it was documented. That said it must be clear that it's up to the script to support this. i.e something like.
> `--target <TARGET> Target task to invoke. Script must support this explicitly`
> 
> Also we don't need to have quotes mentioned explicitly as this is the same for all shell commands.

@devlead @gep13 Tell me if you want me to change this in my PR, or should I just close it.

**Comment by patriksvensson** [comment]
@devlead @gep13 Perhaps I should add this to my CLI PR?

**Comment by gep13** [comment]
>@devlead said...
IMHO I think target is such a common parameter so it would be good if it was documented. 

The ideal would be if it was _only_ shown if the Cake script expected a target argument.  However, the same could be said about any "expected" arguments from the Cake script.

@patriksvensson would your CLI PR be able to generate automatically some additional documentation based on first inspecting the cake script for any Argument aliases?

**Comment by patriksvensson** [comment]
@gep13 That would be difficult since the help arguments are displayed before any cake script or any other variables have been specified. Let me think about it a little.

**Comment by devlead** [comment]
> > @Roadrunner67 @gep13 IMHO I think target is such a common parameter so it would be good if it was documented. That said it must be clear that it's up to the script to support this. i.e something like.
> > `--target <TARGET> Target task to invoke. Script must support this explicitly`
> > Also we don't need to have quotes mentioned explicitly as this is the same for all shell commands.
> 
> @devlead @gep13 Tell me if you want me to change this in my PR, or if I should just close it.

@Roadrunner67 yes please, make that change, and we can do a more refined improvement later.

**Comment by devlead** [comment]
@Roadrunner67 your changes have been merged, thanks for your contribution 👍

**Pull request merged**
