### PR TITLE
GH1357: Removed StyleCop SA1633 rule supression

### LINKED ISSUE #1357: Remove suppression of StyleCop rule SA1633
Will make sure that the header text is correct in each file (which it isn't at the moment).

### PR DESCRIPTION
**Pull request by patriksvensson**
Closes #1357

### CODE REVIEW

**Comment by patriksvensson** [comment]
@gep13 Sure! I'll do this a bit later tonight.

**Comment by gep13** [comment]
@patriksvensson I have just rebased your branch.  Assuming all the CI's pass, I will pull this in.

**Comment by patriksvensson** [comment]
I completely forgot to do this... 😢

**Comment by gep13** [comment]
Not a problem 🙂

**Pull request merged**
