### PR TITLE
GH2784: Added NugetDelete function to Cake.Common.Tools.Nuget

### PR DESCRIPTION
**Pull request by DaisyDave**
Added NuGet Delete function to NuGet tools. I based my changes on the Push function implementation.

Relates to #2784

### CODE REVIEW

**Comment by devlead** [comment]
@DaisyDave is there an existing issue this proposed change addresses?

**Comment by DaisyDave** [comment]
There was no issue. I would like to replace a external script so made the PR without creating one.

I hope that’s OK

**Comment by gep13** [comment]
@DaisyDave apologies for not getting back to you sooner about this.  Our contributing process, as mentioned here: https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md#get-buyoff-or-find-open-community-issues-or-features, including information about first raising an issue, before working on a PR.  Could you raise an issue, and reference it from this PR, so that we have traceability about what is being done, and why?

**Comment by DaisyDave** [comment]
@gep13 Sorry I missed that I have created issue #2784 which should provide some history for the PR

**Comment by gep13** [comment]
@DaisyDave your changes have been merged, thanks for your contribution 👍

**Pull request merged**
