### PR TITLE
Cleaned up ReSharper Inspect warnings.

### PR DESCRIPTION
**Pull request by patriksvensson**
Related to #735.

### CODE REVIEW

**Comment by gep13** [comment]
@patriksvensson love it! I have kicked the CI builds again, and if these pass, I will merge :-D

**Comment by gep13** [comment]
@patriksvensson woot, this one finally passed as well.  Can you rebase and I can merge this one too?

**Comment by patriksvensson** [comment]
@gep13 Rebased against develop.

**Comment by gep13** [comment]
@patriksvensson can you do a quick rebase here, and I will get this one pulled in as well.

**Comment by gep13** [comment]
Nice one!

**Pull request merged**
