### PR TITLE
(GH-852) Added information about mono flag

### PR DESCRIPTION
**Pull request by gep13**
Relates to #852

### CODE REVIEW

**Comment by gep13** [comment]
@patriksvensson you mentioned that this should "only" be shown when running on Windows.  What are your suggestions for best way to achieve this?  Where can I get that information from?  Thanks!

**Comment by devlead** [comment]
@gep13 this could be a good place to start
https://github.com/cake-build/cake/blob/4e120409682be28609b43d2a3b6ec8745ec02389/src/Cake.Common/EnviromentAliases.cs#L124

**Comment by patriksvensson** [comment]
@gep13 Use `IsUnix` from `ICakeEnvironment`.

**Comment by gep13** [comment]
@patriksvensson @devlead when you have a minute, can you have a look at the new changes in this PR? Thanks!

**Comment by patriksvensson** [comment]
@gep13 Taking a look now.

**Comment by patriksvensson** [comment]
Merged :+1:

**Pull request merged**
