### PR TITLE
GH1719: Cleaned old and added new Jenkins variables

### PR DESCRIPTION
**Pull request by Roemer**
See  #1719.

### CODE REVIEW

**Comment by Roemer** [comment]
I'm not totally sure if it makes sense to keep the different JenkinsXXXInfo.cs files and classes. Wouldn't it be easier to have all information in one class? What do you think?

**Comment by patriksvensson** [comment]
@Roemer It might be easier, but it would also be a breaking change so I think we should leave it as is for now.

**Comment by patriksvensson** [comment]
@cake-build/cake-team Any opinions about this?

**Comment by devlead** [comment]
@patriksvensson there's several breaking changes already in this PR, but I'm unsure it's better to flatten out though.

**Comment by devlead** [comment]
@Roemer your changes have been merged, thanks for your contribution 👍

**Pull request merged**
