### PR TITLE
GH-4107: Add OS to DotNetPublishSettings

### LINKED ISSUE #4107: `DotNetPublishSettings` is missing a way to set the `--os` option
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake Frosting

### Cake version

3.0.0

### Operating system

Windows

### Operating system architecture

64-Bit

### CI Server

_No response_

### What are you seeing?

Using dotnet version:
```sh
$ dotnet --version
6.0.404
```
when I run
```sh
$ dotnet publish --help
Description:
  Publisher for the .NET Platform

Usage:
  dotnet publish [<PROJECT | SOLUTION>...] [options]

Arguments:
  <PROJECT | SOLUTION>  The project or solution file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
...
  --os <os>                            The target operating system.
...
```

I get an option to set the the target operating system.

However, [DotNetPublishSettings.cs](https://github.com/cake-build/cake/blob/ca6699c4c0b3a57c9ca04bdfc687158fe112215e/src/Cake.Common/Tools/DotNet/Publish/DotNetPublishSettings.cs) does not provide access to the option. ([DotnetMSBuildSettings.cs](https://github.com/cake-build/cake/blob/ca6699c4c0b3a57c9ca04bdfc687158fe112215e/src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildSettings.cs) does not either).

### What is expected?

I should be able to set the target OS using the `DotNetPublishSettings`. e.g,

```cs
var publishSettings = new DotNetPublishSettings
{
    Os = "win"
};
```

### Steps to Reproduce

```cs
var publishSettings = new DotNetPublishSettings
{
    Os = "win"
};
```
does not compile.

### Output log

```txt
'DotNetPublishSettings' does not contain a definition for 'Os'
```

### PR DESCRIPTION
**Pull request by Marusyk**
Add `--os <OS>` to [dotnet-publish](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)

Fixes #4107

Please review.
Thank you in advance

### CODE REVIEW

**Comment by Marusyk** [comment]
Please review

**Review by augustoproiete — DISMISSED** [review]
LGTM overall. Just a small suggestion on the name of the property

**Comment by augustoproiete** [comment]
We're looking into the impact on addins, as this is a breaking change to the public API, to decide if we can merge it now for v3.1.0 or if it has to wait for the next major.

**Review by devlead — APPROVED** [review]
LGTM

**Pull request merged**
