### PR TITLE
GHxxx: Add WiX Insignia Support

### PR DESCRIPTION
**Pull request by jdbohrman**
Hello,

This is my first PR (Sortof). I learned so much by working through this, and I want to thank everyone who helped me out. The only thing I wasn't sure about was whether I needed to add Insignia into the `WixAlias.cs` file, that can easily be fixed if it's unnecessary however.

### CODE REVIEW

**Comment by gep13** [comment]
@jdbohrman thank you for your contribution to the Cake project, we really appreciate it!  Are you in a position to add unit tests to cover the changes that you have made in this PR?  If you can, we should be in a position to get this merged.  Thanks

**Comment by jdbohrman** [comment]
> @jdbohrman thank you for your contribution to the Cake project, we really appreciate it! Are you in a position to add unit tests to cover the changes that you have made in this PR? If you can, we should be in a position to get this merged. Thanks
Hey just saw this, I've got some time to work on this soon so I'll add those unit tests.

**Comment by augustoproiete** [comment]
Hey @jdbohrman it's been a long time, but are you still interested in moving forward with WiX Insignia support in Cake in some fashion (and would be willing to write the unit tests)?

**Comment by augustoproiete** [comment]
I took a deeper look at this PR today with the goal of adding the missing tests and missing XML Doc comments to it, in order to get it merged in.

Before doing that I tried to get myself acquainted with the [WiX Toolset v3.11.2](https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm) and [Insignia](https://wixtoolset.org/documentation/manual/v3/overview/insignia.html) in particular and run a few integration tests, and it seems that Insignia changed a lot over time and the arguments it expects no longer match match what this PR currently implements, including the input files:

```
Windows Installer XML Toolset Inscriber version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

 usage: insignia.exe [-?] [-nologo] [-o[ut] outputPath] [@responseFile]
           [-im databaseFile|-ib bundleFile|-ab bundlePath bundleWithAttachedContainerPath]
   -im        specify the database file to inscribe
   -ib        specify the bundle file from which to extract the engine.
              The engine is stored in the file specified by -o
   -ab        Reattach the engine to a bundle.
   -nologo    skip printing insignia logo information
   -o[ut]     specify output file. Defaults to databaseFile or bundleFile.
              If out is a directory name ending in '\', output to a file with
               the same name as the databaseFile or bundleFile in that directory
    -sw[N]     suppress all warnings or a specific message ID
               (example: -sw1009 -sw1103)
    -swall     suppress all warnings (deprecated)
    -v         verbose output
    -wx[N]     treat all warnings or a specific message ID as an error
               (example: -wx1009 -wx1103)
   -wxall     treat all warnings as errors (deprecated)
   -? | -help this help information

For more information see: http://wixtoolset.org
```

Given that, I'm closing this for now, and @jdbohrman or anyone else interested in getting WiX [Insignia](https://wixtoolset.org/documentation/manual/v3/overview/insignia.html) support added to Cake, feel free to open a new PR that aligns with with the current version of Insignia.

**Pull request closed without merging**
