### PR TITLE
#2030 - Fix case-sensitive nuget url compare

### PR DESCRIPTION
**Pull request by coder2213**
#2030 
Made string comparison case insensitive to fix the issue.

### CODE REVIEW

**Comment by augustoproiete** [comment]
@coder2213 Looks good. Could you please squash the commits and push --force?

**Comment by coder2213** [comment]
> 
> 
> @coder2213 Looks good. Could you please squash the commits and push --force?

@augustoproiete 
I don't know how to do this.
Tried a few, where I squashed all the commits on this PR into one but the merged commit of #1663 is making my feature branch of out-of-date. So have to update branch and that merge commit is showing up on this PR.
Please provide any resource that can help me with this.

**Comment by coder2213** [comment]
Just checked again and this is unavoidable since this is #3400  is part of develop branch and it will definitely show up.
I squashed rest of commits and this should be okay.

**Comment by augustoproiete** [comment]
@coder2213 [How do I rebase?](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#add-the-official-repo-as-a-remote-first-time-only)

**Comment by coder2213** [comment]
@augustoproiete 
Rebase is done.
Please check.

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by augustoproiete** [comment]
@coder2213 your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
